Implement slashing protection interchange format
sigp/lighthouse pull request #1544
Opened 2020-08-18 09:09 UTC by michaelsproul

## Issue Addressed

Implements support for importing and exporting the slashing protection DB interchange format described here:

https://hackmd.io/@sproul/Bk0Y0qdGD

## Proposed Changes

* [x] Support for serializing and deserializing the format
* [x] Support for importing and exporting Lighthouse's database
* [ ] CLI commands to invoke import and export

Bonus!

* [x] A fix to a potentially nasty bug involving validators getting re-registered each time the validator client ran! Thankfully, the ordering of keys meant that the validator IDs used for attestations and blocks remained stable -- otherwise we could have had some slashings on our hands! :scream:

2020-08-20 13:09 UTC, djrtwo commented
Are you implementing both formats from the doc? Or should teku instead just use the first format and just provide one stubbed message for attestations and blocks

2020-08-20 23:21 UTC, michaelsproul commented
@djrtwo Yeah I've already implemented both! I just need to write some tests and a CLI porcelain, but have been distracted by fixing some DB issues

2020-08-27 08:02 UTC, michaelsproul commented
I'm planning to try a different approach to importing the minimal format. Rather than filling the DB with fake blocks for every slot from 0 to `last_signed_block_slot` (which is really slow), I want to add the last signed block slot as a first-class entity in slashing protection, which we can set with one query. This would also allow us to prune the DB, although I might not implement that yet.

A similar low watermark for attestations will obsolete the need for the `source >= max_source` check on attestations, and the "clever" attestation import strategy with an attestation spanning `0->last_signed_attestation_target_epoch`. I realised that this strategy was going to get even messier, because in addition to the attestation from `0->N` which blocks `i->j` for `i`, `j` in `[1..N]`, we need one with a source greater than 0 to block `0->j` for `j` in `1..N` that isn't mutually slashable with the `0->N` one. I think there's a hacky way to do it with 2 attestations, but the low watermark really seems simpler and less error prone.

Glossary:

* `i->j` is an attestation with source epoch `i` and target `j`

2020-09-06 23:36 UTC, michaelsproul commented
Blocked on #1588

2020-09-07 07:42 UTC, michaelsproul commented
This is ready for review!

There's one FIXME that depends on https://github.com/sigp/lighthouse/pull/1532, but that should be straight-forward to resolve once one of these PRs is merged.

2020-09-17 23:35 UTC, michaelsproul commented
Marking this as WIP again, because it needs updating for v4 of the spec

2020-09-28 06:21 UTC, michaelsproul commented
This is ready to roll again, just waiting on resolution of merge conflicts in #1532

2020-09-28 06:22 UTC, michaelsproul commented
This PR closes an A0 issue (#1584), but the fix is relatively well-contained in https://github.com/sigp/lighthouse/pull/1544/commits/1dbd5379d4fa433fdcabf5606fae7ba4cea2af99 if we want to cherry-pick it and merge it before reviewing+merging this PR.

2020-10-01 06:13 UTC, paulhauner requested changes
Impressive, especially with all the test vectors and interop contribution!

I just have a few comments. I played around with it and it worked great, I had a couple of suggestions for logs that might reduce our support load.

2020-10-01 06:42 UTC, michaelsproul commented on validator_client/slashing_protection/src/slashing_database.rs
> +    serde_json::from_str(&format!("\"{}\"", s))
Yes!!

2020-10-01 06:55 UTC, michaelsproul commented on validator_client/slashing_protection/src/interchange.rs
> +pub struct CompleteInterchangeData {
Yeah, I think I'll delete it in v5 of the spec, but as it's a breaking change, I figured it could stay a bit longer

2020-10-01 06:56 UTC, michaelsproul commented on validator_client/slashing_protection/build.rs
> +    let exit_status = std::process::Command::new("make")
Thanks!

2020-10-01 06:56 UTC, michaelsproul commented on account_manager/src/validator/slashing_protection.rs
> +
Done!

2020-10-01 06:56 UTC, michaelsproul commented on account_manager/src/validator/slashing_protection.rs
> +            Ok(())
Done!

2020-10-02 01:09 UTC, michaelsproul commented on lighthouse/tests/account_manager.rs
> +    assert!(
Done

2020-10-02 01:09 UTC, michaelsproul commented
All comments addressed :tada:

2020-10-02 01:41 UTC, paulhauner approved these changes
Approved! :tada:

2020-10-02 01:42 UTC, michaelsproul commented
Thanks!

bors r+

2020-10-02 02:47 UTC, closed without merging