Implement slasher
sigp/lighthouse pull request #1567
Opened 2020-08-25 07:44 UTC by michaelsproul

This is an experimental/unfinished implementation of a slasher that lives inside the BN and can be enabled via `lighthouse bn --slasher`. It is missing many features and needs cleaning up and testing before merging (to be documented SOON).

2020-11-14 08:11 UTC, paulhauner requested changes
This is an impressive research and engineering piece! It was a pleasure to read and a real contribution to Lighthouse and Eth2 :1st_place_medal: 

I must admit I'm not 100% across the theory of the schema, but I don't think that should prevent a merge. The slasher is a best-effort component; as long as it does not crash then it is better than nothing. That being said, I see no reason to believe this implementation is lacking.

Although I'm not fully across the slasher theory, I did go through the whole implementation and have left several comments and suggestions. I would be happy to merge 

:rocket:

2020-11-17 23:29 UTC, michaelsproul commented on slasher/src/array.rs
> +        if source_epoch > current_epoch - config.history_length as u64 {
Yeah, all of this arithmetic is saturating arithmetic on epochs, and it _used_ to be full of bugs but I'm fairly sure the fuzz testing in `tests/random.rs` got them all.

2020-11-17 23:29 UTC, michaelsproul commented on slasher/src/array.rs
> +            epoch -= 1;
Yeah, its saturating

2020-11-17 23:32 UTC, michaelsproul commented on book/src/slasher.md
> +* Default: 8192 epochs
Oh cool, I don't know where I got 8192 from. I thought I saw it in Aditya's HackMD

2020-11-17 23:33 UTC, michaelsproul commented on book/src/slasher.md
> +of the immaturity of the slasher UX and the extra resources required.
Haha, as we found out on Toledo, this might actually be something of a problem :grimacing:

2020-11-17 23:38 UTC, michaelsproul commented on beacon_node/beacon_chain/src/attestation_verification.rs
> +                    &head.beacon_state,
Yeah, great catch. Switching to the pubkey cache now.

2020-11-18 01:34 UTC, michaelsproul commented on book/src/slasher.md
> +* Flag: `--slasher-max-db-size GIGABYTES`
Went down a bit of a rabbithole on this one https://hackmd.io/@sproul/slasher-internals#How-much-disk-space

I'll include the total formula in the doc

2020-11-22 23:15 UTC, michaelsproul commented on beacon_node/src/cli.rs
> +                    "Run a slasher alongside the beacon node [EXPERIMENTAL]."
I updated the message along the lines of your suggestion

2020-11-22 23:16 UTC, michaelsproul commented on book/src/slasher.md
> +of the immaturity of the slasher UX and the extra resources required.
Having run the slasher a bit more, I think we can conclude that the issue was the database compaction interfering with all disk writes. So I think it's OK. If users have issues they can always disable the slasher by removing the `--slasher` flag.

2020-11-22 23:18 UTC, michaelsproul commented
This is ready for re-review and merge IMO. The only outstanding issue is https://github.com/sigp/lighthouse/issues/1890, which I'll try to get to before 1.0, but isn't a blocker for users running with the default configuration, or experienced users (who can drop their DB if they set a max DB size too low).

2020-11-23 03:13 UTC, michaelsproul commented
Will fix the merge conflict ASAP, just finishing off some slashing protection stuff

2020-11-23 03:31 UTC, paulhauner approved these changes
Awesome, LGTM!

Happy for you to bors whenever, assuming merge conflict change is trivial :)

2020-11-23 03:43 UTC, michaelsproul commented
Indeed the merge commit was trivial (https://github.com/sigp/lighthouse/pull/1567/commits/97228b5f5eae7484e73a1ac2ad9b42ea7ea75851)

I can't believe we're finally merging this :open_mouth: :open_mouth: :open_mouth: 

:rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: 

Summoning Señor Bors...

bors r+

2020-11-23 04:58 UTC, closed without merging