Ssz state
sigp/lighthouse pull request #1749
Opened 2020-10-08 23:14 UTC by paulhauner

## Issue Addressed

NA

## Proposed Changes

Adds a `lighthouse/beacon/states/:state_id/ssz` endpoint to allow us to pull the genesis state from the API.

## Additional Info

NA

2020-10-13 03:58 UTC, paulhauner commented
@realbigsean this is along the lines of what you're working on, do you mind giving it a review? :)

2020-10-21 19:50 UTC, realbigsean commented on beacon_node/http_api/src/lib.rs
> +    // GET lighthouse/beacon/state/{state_id}/ssz
```suggestion
    // GET lighthouse/beacon/states/{state_id}/ssz
```

2020-10-21 20:11 UTC, realbigsean requested changes
Sorry it took me so long to review this! I missed it initially.  Left a few minor doc comments.

Another note: I don't think this'll work properly for genesis until #1783 is merged (I didn't test it out though)

2020-10-21 20:11 UTC, realbigsean commented on book/src/api-lighthouse.md
> +### `/lighthouse/beacon/states/{state_id}/ssz`
Adding the state_id options here might be good, or referencing the eth2 api. Might not be clear otherwise.

2020-10-21 23:54 UTC, paulhauner commented
Thanks! All review comments addressed, I'll go ahead and merge assuming I have approval (changes are trivial).

bors r+

2020-10-22 05:01 UTC, paulhauner commented
bors retry

2020-10-22 07:19 UTC, closed without merging