Normalize keystore passwords
sigp/lighthouse pull request #1972
Opened 2020-11-25 14:50 UTC by pawanjay176

## Issue Addressed

Resolves #1879 

## Proposed Changes

Do NFKD normalization for keystore passwords.

2020-11-25 18:58 UTC, pawanjay176 commented
@kirk-baird with https://github.com/sigp/lighthouse/pull/1928 , we are returning an error if we try encrypting using a password with control chars.
However, eip 2335 says 
> The C0, C1, and Delete control codes are not valid characters in the password and should therefore be **stripped** from the password.

This is what the deposit-cli seems to be doing here
https://github.com/ethereum/eth2.0-deposit-cli/blob/ed5a6d33a16bf7ef71a4d541212ab2896c7c0fc0/eth2deposit/key_handling/keystore.py#L116-L123

So if the user entered a password with control characters in the deposit-cli, it seems they would get stripped and fail with the import in lighthouse.

Made c5daab7 to strip the characters instead of throwing an error. Can you please check if I understood the spec correctly here? :)

2020-11-26 06:34 UTC, kirk-baird commented
> Made c5daab7 to strip the characters instead of throwing an error. Can you please check if I understood the spec correctly here? :)

Yep I'm happy with your interpretation to strip away any control characters rather than error.

Thanks for fixing this up! I had a look through `is_control()` too and it matches exactly the control characters we wish to remove :D

2020-11-26 06:36 UTC, kirk-baird approved these changes
Happy with the changes :)

2020-11-26 15:27 UTC, pawanjay176 commented
Added normalization to the `eth2_keystore` instead of normalizing user input. This is in line with the eip 2335 specs.

2020-12-02 23:47 UTC, michaelsproul commented on crypto/eth2_keystore/src/keystore.rs
> +    password.retain(|c| !is_control_character(c));
The comment at the top of this function

> (Errors) if `password` uses utf-8 control characters.

Is out of date

2020-12-03 00:15 UTC, michaelsproul requested changes
Looks really good! Just that one doc comment to fix before merge

2020-12-03 00:16 UTC, michaelsproul commented on crypto/eth2_keystore/src/keystore.rs
> +    c.is_control()
Haha just saw Kirk's comment. Oh well, now we've triple checked it

2020-12-03 11:15 UTC, michaelsproul approved these changes

2020-12-03 22:06 UTC, michaelsproul commented
bors r+

2020-12-03 23:09 UTC, closed without merging