Detailed validator monitoring
sigp/lighthouse pull request #2151
Opened 2021-01-08 05:33 UTC by paulhauner

## Issue Addressed

NA

## Proposed Changes

Adds a `ValidatorMonitor` struct which provides additional logging and Grafana metrics for specific validators.

Use `lighthouse bn --validator-monitor` to automatically enable monitoring for any validator that hits the [subnet subscription](https://ethereum.github.io/eth2.0-APIs/#/Validator/prepareBeaconCommitteeSubnet) HTTP API endpoint.

Also, use `lighthouse bn --validator-monitor-pubkeys` to supply a list of validators which will always be monitored.

## TODO

- [ ] Track validator balance, `slashed` status, etc.
- [ ] Self-review, tidy.
- [ ] Publish Grafana dashboard

2021-01-19 18:27 UTC, realbigsean requested changes
This is awesome! Can't wait till it's in :rocket: 

I left a bunch of comments, most of them are just typos. The only sort of major thing I would be concerned about is opening a read lock on `ValidatorMonitor` whenever we register something, and subsequently opening a write lock on the `SummaryMap` (which is held in the `ValidatorMonitor` struct) during this registration. I'm not exactly sure if/how it could deadlock but wanted to bring it up

2021-01-20 00:34 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                let production_delay = slot_clock.slot_duration() / 2;
Great catch!

2021-01-20 02:51 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                        if validator.slashed { 0 } else { 1 },
Good catch!

2021-01-20 03:04 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +        let mut summaries = self.summaries.write();
Thanks for pointing this out. I believe it's safe though.

The order of lock acquisition is always `lock(external) -> lock(internal) -> unlock(internal) -> unlock(external)`. We provide no method to expose the `internal` lock, so this always holds.

I've added a comment to warn the user of a potential internal deadlock with `with_epoch_summary`. though!

2021-01-20 03:54 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +    pub fn add_validators_from_file<P: AsRef<Path>>(&mut self, path: P) -> Result<(), Error> {
Removed!

2021-01-20 03:54 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +    pub fn register_block_attester_slashing(
I've fixed this here: https://github.com/sigp/lighthouse/pull/2151/commits/82cd92129671a4765de8fdff77317beaab573bf7

2021-01-20 03:54 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +    pub fn register_block_proposer_slashing(
I've fixed this here: https://github.com/sigp/lighthouse/pull/2151/commits/82cd92129671a4765de8fdff77317beaab573bf7

2021-01-20 06:19 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +    pub fn add_validator_pubkey(&mut self, pubkey: PublicKeyBytes) {
In https://github.com/sigp/lighthouse/pull/2151/commits/bfcb6fe6981d4026ca00b758f34d83ef623f9af5 I've made it so `new` takes a list of validators and the `BeaconChainBuilder` adds the canonical head state to the validator monitor when it's being built.

2021-01-20 06:24 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                gross_delay.checked_sub(production_delay)
I agree, I think I might leave it for later works though. I'm not exactly sure how Prom/Graf will handle negative a duration and I'm keen to get this out the door.

2021-01-20 06:45 UTC, paulhauner commented
All comments addressed! Thanks for the review, super helpful.

I added a couple of extra metrics in 16d1f089f, so I'll have to update the dashboard and replace the PR you made (sorry!).

2021-01-20 17:14 UTC, realbigsean approved these changes
Nice! Everything looks good

2021-01-20 19:19 UTC, paulhauner commented
bors r+

2021-01-20 20:15 UTC, closed without merging