Validator import password flag
sigp/lighthouse pull request #2228
Opened 2021-02-26 16:43 UTC by realbigsean

## Issue Addressed

#2224

## Proposed Changes

Add a `--password-file` option to the `lighthouse account validator import` command. The flag requires `--reuse-password` and will copy the password over to the `validator_definitions.yml` file. I used #2070 as a guide for validating the password as UTF-8 and stripping newlines.

## Additional Info

2021-03-01 04:59 UTC, paulhauner requested changes
Nice one! Just one little typo.


Also, it might be pretty easy and valuable to duplicate this test and get it to use a password file:

https://github.com/sigp/lighthouse/blob/46920a84e857d6c086adf4b42810ac03de94ed3e/lighthouse/tests/account_manager.rs#L407-L497

2021-03-01 04:59 UTC, paulhauner commented on account_manager/src/validator/import.rs
> +                    keystores being imported. This flag must be used with the `--reuse-password`. \
```suggestion
                    keystores being imported. This flag must be used with `--reuse-password`. \
```

2021-03-02 18:59 UTC, realbigsean commented
Comments addressed!

2021-03-14 22:55 UTC, paulhauner approved these changes
Nice one!

bors r+

2021-03-14 23:32 UTC, paulhauner commented
@realbigsean seems bors doesn't like this, potentially for valid reasons. It might be worth merging `unstable` and then seeing if it passes CI.

2021-03-16 23:55 UTC, realbigsean commented
got a green check!

2021-03-17 04:14 UTC, paulhauner approved these changes
Awesome!

bors r+

2021-03-17 05:09 UTC, paulhauner commented
I'll batch this

bors r-

2021-03-17 05:09 UTC, paulhauner commented
bors r+

2021-03-17 06:05 UTC, closed without merging