Reduce outbound requests to eth1 endpoints
sigp/lighthouse pull request #2340
Opened 2021-05-12 00:15 UTC by macladson

## Issue Addressed

#2282 

## Proposed Changes

Reduce the outbound requests made to eth1 endpoints by caching the results from `eth_chainId` and `net_version`.
Further reduce the overall request count by increasing `auto_update_interval_millis` from `7_000` (7 seconds) to `60_000` (1 minute). 
This will result in a reduction from ~2000 requests per hour to 360 requests per hour (during normal operation). A reduction of 82%.

## Additional Info

If an endpoint fails, its state is dropped from the cache and the `eth_chainId` and `net_version` calls will be made for that endpoint again during the regular update cycle (once per minute) until it is back online.

2021-05-12 00:32 UTC, macladson commented
Excuse the x-axis (the second test was run for a few hours less so the total request count isn't indicative of the actual changes, however the percentages will be accurate), but these screenshots from Infura show the results of the changes.

Both tests were run (on Goerli) for over 12 hours in regular operating conditions (post initial deposit/block cache sync).

### Before
![eth1](https://user-images.githubusercontent.com/58379419/117899702-054ee200-b30b-11eb-8b4a-f159628296b6.png)

Almost 50% percent of all requests were redundant requests for `eth_chainId` and `net_version`


### After
![eth1_with_more_changes](https://user-images.githubusercontent.com/58379419/117899721-0bdd5980-b30b-11eb-96a2-6a3a4f659a90.png)

Redundant requests have been removed and the overall request counts per hour have been massively reduced.

2021-05-19 12:00 UTC, pawanjay176 reviewed
Amazing reductions! :tada: 
I had a minor comment, let me know what you think :)

The increase in the update interval works super well once the eth1 cache is fully synced. However, it seems like it would be unnecessarily slow during the initial sync phase.
`update_deposit_cache` fetches deposits from `blocks_per_log_query * max_log_requests_per_update` blocks in a single invocation. With the current values, that's 100,000 blocks in a single update. 

With 1 minute intervals, it would take around 8x time to complete the initial sync compared to 7 second intervals. 
A simple way to get around this would be to increase the `max_log_requests_per_update` to 1000 (or maybe even more) so that a single update covers more blocks.

2021-05-19 12:00 UTC, pawanjay176 commented on beacon_node/eth1/src/service.rs
> +    async fn reset_endpoint_state(&self, endpoint: &EndpointWithState) {
Not sure why this is a method on `EndpointsCache`.

2021-05-19 12:00 UTC, pawanjay176 commented on beacon_node/eth1/src/service.rs
> +    async fn get_state(&self, endpoint: &EndpointWithState) -> Option<EndpointState> {
same as above.

2021-05-20 00:07 UTC, macladson commented
Hey thanks for checking it out :)

> The increase in the update interval works super well once the eth1 cache is fully synced. However, it seems like it would be unnecessarily slow during the initial sync phase.

Ahh, I checked for this and didn't notice a major change in initial sync times. I obviously messed something up because I checked again and you're right.

> A simple way to improve this would be to increase the `max_log_requests_per_update` to 1000 (or maybe even more) so that a single update covers more blocks.

This will work great for local nodes, but services like Infura limit the max allowed size of the response, so I'm not sure it will be that simple.
```
ERRO Failed to update eth1 cache             error: Failed to update eth1 deposit cache: 
"All fallback errored: https://goerli.infura.io/ => GetDepositLogsFailed(\"Eth1 node returned error: 
{\\\"code\\\":-32005,\\\"message\\\":\\\"query returned more than 10000 results\\\"}\")", retry_millis: 60000, service: eth1_rpc
``` 
Obviously if someone were using Infura, they could pass `--eth1-blocks-per-log-query 150` or something to limit it, but that's an unwieldy solution and even then the sync would still be much slower. 

We might just have to find a way to bypass the auto update period while syncing initially, which would allow us to have smaller, but more frequent requests.

2021-05-20 11:34 UTC, pawanjay176 commented
> services like Infura limit the max allowed size of the response

Yeah, fair point. Even if we set `max_log_requests_per_update` to a very high number, it's no use if even a single request to the infura node fails(quite a few infura requests failing during the initial sync from what I have seen) and we have to wait for another minute to retry. 

Bypassing the auto update duration during initial sync seems like the way to go.

2021-05-24 23:27 UTC, macladson commented
After some testing, (thanks to @pawanjay176 for helping out) I believe that increasing `max_log_requests_per_update` to a much higher value will be a safe solution here.

The concerns around Infura's max response size do not seem to affect pulling in deposit logs from Mainnet as deposit density is low enough. They do affect Göerli since deposit density is so high, but even using `stable` requires setting `--eth1-blocks-per-log-query` to `150` to avoid these errors, and so it will be an equally effective mitigation here as well.

Both @pawanjay176 and I ran multiple tests across Mainnet and Pyrmont and found that increasing `max_log_requests_per_update` to `5_000` mitigated the downsides of increasing `auto_update_interval_millis`,  so the code in its current state does not significantly impact initial sync times (or the number of requests made while syncing).

2021-05-31 02:13 UTC, paulhauner requested changes
Looking good! Great gainz!

I do have one suggestion, which I've prepared here: https://github.com/paulhauner/lighthouse/commit/93e4e2e26aa089dfc6f12ad5cb49231b13cb6d88.

I that commit I've raised the `Arc` from per-endpoint to a single at the highest level. This for two reasons:

1. `Arc` is not necessarily a simple object, it involves atomic variables and has some overhead. So, it's nice to have as few as possible.
1. In terms of structure, it ensures that an `EndpointWithState` can only belong to one `EndpointsCache`. If we have multiple `Arc`s then it's possible to have multiple caches sharing endpoints. Not an issue now, but it's defensive for the future.

Interested to hear your thoughts on my suggestion :)

2021-05-31 02:13 UTC, paulhauner commented on beacon_node/eth1/src/service.rs
> +            drop(endpoints_cache);
Nice lock hygiene here :+1:

2021-05-31 02:13 UTC, paulhauner commented on beacon_node/eth1/src/service.rs
> +pub struct EndpointWithState {
Nice work on making this a struct with named fields, much more readable than the tuple :+1:

2021-05-31 02:33 UTC, paulhauner commented
FYI we could probably get this included in the release later this week if we can get this merged in the next couple of hours :)

2021-05-31 03:45 UTC, macladson commented
> I that commit I've raised the Arc from per-endpoint to a single at the highest level.

Ahh yes, that makes total sense! Thanks for the suggestion :)

2021-05-31 03:59 UTC, paulhauner approved these changes
Nice one!

bors r+

2021-05-31 04:13 UTC, paulhauner commented
bors r-

2021-05-31 04:14 UTC, paulhauner commented
bors r+

2021-05-31 04:15 UTC, paulhauner commented
bors r-

2021-05-31 04:15 UTC, paulhauner commented
bors r+

2021-05-31 04:16 UTC, paulhauner commented
bors -

2021-05-31 04:17 UTC, paulhauner commented
bors r-

2021-05-31 04:18 UTC, paulhauner commented
bors r+

:crossed_fingers:

2021-05-31 05:41 UTC, closed without merging