Adjust timeout duration for VC attestation duties
sigp/lighthouse pull request #2352
Opened 2021-05-19 01:49 UTC by macladson

## Issue Addressed

#2313 

## Proposed Changes

Provide `BeaconNodeHttpClient` with access to the `slots_per_second` of the network.
This will allow granular adjustment (relative to the slot duration) of the timeout duration for different calls made from the VC to the BN by utilizing a timeout ratio.

## Additional Info

Additionally set the default `BeaconNodeHttpClient` timeout to the be the slot duration of the network, rather than a constant 12 seconds. This will allow it to adjust to different network specifications.

2021-05-19 02:33 UTC, macladson commented
A few additional notes:
- As per the `reqwest` documentation, timeout duration can be adjusted on a [per-request basis](https://docs.rs/reqwest/0.11.0/reqwest/struct.RequestBuilder.html#method.timeout) without overwriting the default client timeout.

- We should probably have a discussion around what kind of timeouts are desired here to ensure proper fallback behavior. As a start I've put in a ratio of 3 (which is a 4 second timeout on mainnet spec networks) for all calls relevant to attestation production.

- Something we should also keep in mind is the use of remote beacon nodes (like Infura) and needing to account for
the additional latency involved there. A timeout suitable for a local node, might not be suitable for a remote one.
To see the sorts of constraints we are working with, I ran this overnight using an Infura beacon node with a ratio of 12 (so a 1 second timeout per attestation request) and didn't have any attestation timeouts, so I suspect we will generally be fine.

2021-05-19 03:28 UTC, macladson commented
Just had an attestation timeout in the `eth1-simulator-ubuntu` test the first time it ran (but not the second). Not sure if it was a once off issue or if it means that this specific test isn't consistently able to handle shorter timeouts.

2021-06-18 04:54 UTC, paulhauner requested changes
Heyo! Looking good, I'm sure this would work fine as-is. I must made a few nitpicks.

I've also added some metrics via this commit: https://github.com/sigp/lighthouse/commit/0e7ac92e1179d16333e30c51ee9a0dd43b9e601c I'd suggest cherry-picking it here so we can have them in the future too.

I'm running some metrics on a couple of Prater nodes. Here's the info so far:

![http_times](https://user-images.githubusercontent.com/6660660/122508001-9882e200-d044-11eb-839f-72dcaa874561.png)

We can let it run over the wekeend and see what sort of times we're seeing on those requests. From an initial glance it looks like your suggestions are pretty good. I'll give you access to the metrics nodes when were both online again (probably Monday).

2021-06-18 04:54 UTC, paulhauner commented on common/eth2/src/lib.rs
> +    pub fn new(
I would be tempted to do away with this `new` function and make the fields `pub` so it can be initialized "manually".

Whenever there's a string of identical types going into a function I worry about making a mistake with the ordering. I feel that ...

```rust
Thing {
  x: 1,
  y: 2,
  z: 3
}
```

... reads a bit better than ...

```rust
Thing::new(1, 2, 3)
```

... especially when the `new` function isn't doing anything else.

It's stylistic suggestion, feel free to do as you see fit :)

2021-06-18 04:54 UTC, paulhauner commented on common/eth2/src/lib.rs
> +    pub fn default(seconds_per_slot: u64) -> Self {
Another stylistic suggestion; I'd avoid using `default`. I feel the [`Default`](https://doc.rust-lang.org/std/default/trait.Default.html) trait already has a monopoly on that function name.

Suggestion: `pub fn all(duration: Duration)`. Not in love with that name though..

Once again, just a suggestion.

2021-06-18 04:54 UTC, paulhauner commented on validator_client/src/cli.rs
> +                        made to the beacon node.")
To help nudge users in the right direction, perhaps we could append:

> This flag is generally not recommended, longer timeouts can caused missed duties when fallbacks are used.

2021-06-18 04:54 UTC, paulhauner commented on validator_client/src/lib.rs
> +const HTTP_ATTESTATION_TIMEOUT: u64 = 1;
The [`Duration::from_secs`](https://doc.rust-lang.org/std/time/struct.Duration.html#method.from_secs) and other functions are `const`, so you can do this:

```rust
const HTTP_ATTESTATION_TIMEOUT: Duration = Duration::from_secs(1);
```

Same goes for `HTTP_ATTESTER_DUTIES_TIMEOUT` below.

2021-06-18 04:54 UTC, paulhauner commented on validator_client/src/lib.rs
> +                let timeouts = if url.full != last_beacon_node.full && !config.use_long_timeouts {
I see what you're doing here and I think it works, but I do notice that we're satisfying *"is this the last item in the list"* by asking *"is this the same value as the last item in the list"*. Perhaps we're better served by a solution that doesn't make assumptions about the list containing duplicates.

Here's a suggestion:

```rust
let last_index = config
  .beacon_nodes
  .len()
  .checked_sub(1)
  .ok_or_else(|| "No beacon nodes defined.".to_string())?;

config
  .beacon_nodes
  .iter()
  .enumerate()
  .map(|(i, url)| {
      if i < last_index {
        // smol timeouts
      } else {
        // chonky timeouts
      }
  })
```

2021-06-21 01:07 UTC, macladson commented on validator_client/src/lib.rs
> +                let timeouts = if url.full != last_beacon_node.full && !config.use_long_timeouts {
Ah yes, good call. This is definitely a smarter way to do this.

2021-06-21 01:17 UTC, macladson commented
Thanks for the suggestions, and for the additional metrics! Let me know if you feel the timeout durations need any more adjustment.

2021-06-21 08:37 UTC, paulhauner commented
Here's the latest times:

![http_times](https://user-images.githubusercontent.com/6660660/122732474-a85a2a80-d2bf-11eb-8a5d-49f985a3ff03.png)

I'll make a commit with some suggestions based off this and drop it here :slightly_smiling_face:

2021-06-21 08:57 UTC, paulhauner commented
Actually, I think this view is better. It's the maximum times during the last 2 days on Prater:

![Uploading http_times_vals.png…]()

2021-06-21 09:14 UTC, paulhauner commented
Here's my suggested timeouts :slightly_smiling_face: Please double check and let me know if I've done anything stupid :pray: 

https://github.com/paulhauner/lighthouse/commit/02e4b82662dd66857cb3f9f2ef9365062e0b64fe

2021-06-22 01:04 UTC, macladson commented
Looks good to me! I'll pull it in

2021-06-25 05:46 UTC, paulhauner commented
I'm running this on our European Prater nodes. After that's been running a while, I'll merge this in :)

2021-07-07 06:37 UTC, paulhauner commented
This ran well on the testnet nodes! I'd like to check with @michaelsproul before merging. We *might* want to block this on #2279.

2021-07-09 06:13 UTC, paulhauner commented
#2279 should merge today or early next week, we can merge this after :slightly_smiling_face:

2021-07-12 01:47 UTC, paulhauner commented
#2279 has merged! :tada: No conflicts visible yet, let's try bors.

bors r+

2021-07-12 01:48 UTC, paulhauner approved these changes

2021-07-12 03:14 UTC, closed without merging