Add `http-address` flag to VC
sigp/lighthouse pull request #2467
Opened 2021-07-18 06:37 UTC by macladson

## Issue Addressed

#2454 

## Proposed Changes

Adds the `--http-address` flag to allow the user to use custom HTTP addresses. This can be helpful for certain Docker setups.

Since using custom HTTP addresses is unsafe due to the server being unencrypted,  `--unencrypted-http-transport` was also added as a safety flag and must be used in tandem with `--http-address`. This is to ensure the user is aware of the risks associated with using non-local HTTP addresses.

2021-07-19 15:09 UTC, realbigsean requested changes
Looks good! Only thing is the docs here need a couple of updates: https://github.com/sigp/lighthouse/blob/stable/book/src/api-vc.md

2021-07-19 23:49 UTC, macladson commented
> Looks good! Only thing is the docs here need a couple of updates: https://github.com/sigp/lighthouse/blob/stable/book/src/api-vc.md

Good catch!

2021-07-20 00:48 UTC, realbigsean approved these changes

2021-07-21 03:27 UTC, michaelsproul approved these changes
LGTM

2021-07-21 07:10 UTC, michaelsproul commented
bors r+

2021-07-21 08:27 UTC, closed without merging