Improve ergonomics of adding a new network config
sigp/lighthouse pull request #2489
Opened 2021-08-02 06:06 UTC by paulhauner

## Issue Addressed

NA

## Proposed Changes

This PR adds some more fancy macro magic to make it easier to add a new built-in (aka "baked-in") testnet config to the `lighthouse` binary.

Previously, a user needed to modify several files and repeat themselves several times. Now, they only need to modify two files:

- `eth2_config/src/lib.rs`
- `eth2_network_config/src/lib.rs`

This means we still repeat ourselves once, however I can't figure out how to get rid of that. The repetition is because we need to provide the `build.rs` in `eth2_network_config` a list of files to include (we do this via `eth2_config`), then we need to provide the *actual* eth2_network_config` crate with the list of files we included in the `build.rs` (because a crate can't import its own build script).

## TODO

- [ ] Wait for CI to pass.
- [ ] Add more tests

2021-08-10 20:36 UTC, realbigsean requested changes
This looks sweet! Quite the macro rabbit hole here, didn't realize how much one can do.  Just found some small things.

2021-08-10 20:36 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        paste! {
I don't see any `paste!` identifiers `[< .. >]` in the macro so not sure it's necessary here

2021-08-10 20:36 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +    ($this_crate: tt, $mod: ident, $include_file: tt) => {{
```suggestion
    ($this_crate: ident, $mod: ident, $include_file: tt) => {{
```

Seems like this works as is, but should this be `ident`?

2021-08-10 20:36 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +/// It also defines a `include_<title>_bytes!` macro which provides a wrapper around
```suggestion
/// It also defines a `include_<title>_file!` macro which provides a wrapper around
```

2021-08-30 00:13 UTC, paulhauner commented
Thanks @realbigsean, great suggestions. Ready for review!

2021-08-30 13:52 UTC, realbigsean approved these changes
LGTM!

2021-08-30 23:27 UTC, paulhauner commented
bors r+

2021-08-31 01:13 UTC, closed without merging