Reduce validator monitor logging verbosity
sigp/lighthouse pull request #2606
Opened 2021-09-20 13:24 UTC by pawanjay176

## Issue Addressed

Resolves #2541

## Proposed Changes

Reduces verbosity of validator monitor per epoch logging by batching info logs for multiple validators.

2021-09-25 07:43 UTC, paulhauner requested changes
Nice, this should save lots of log lines.

I made a few very minor suggestions. I'm happy to merge after they're applied :)

2021-09-25 07:43 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                "Previous epoch attestations had sub-optimal inclusion delay";
```suggestion
                "Previous epoch attestation(s) had sub-optimal inclusion delay";
```

2021-09-25 07:43 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                "Previous epoch attestation failed to match target";
```suggestion
                "Previous epoch attestation(s) failed to match target";
```

2021-09-25 07:43 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                "Previous epoch attestation failed to match head";
```suggestion
                "Previous epoch attestation(s) failed to match head";
```

2021-09-25 07:43 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                "Previous epoch attestation missing";
```suggestion
                "Previous epoch attestation(s) missing";
```

2021-09-25 07:43 UTC, paulhauner commented on beacon_node/beacon_chain/src/validator_monitor.rs
> +                "Previous epoch attestation success";
```suggestion
                "Previous epoch attestation(s) success";
```

2021-09-30 01:10 UTC, michaelsproul commented
@pawanjay176 I think this should be ready for review again once #2618 is merged and this PR is updated for those changes?

2021-10-12 03:37 UTC, paulhauner approved these changes
Nice one!

bors r+

2021-10-12 07:00 UTC, closed without merging