Don't log errors on resubscription of gossip topics
sigp/lighthouse pull request #2613
Opened 2021-09-22 12:17 UTC by pawanjay176

## Issue Addressed

Resolves #2555

## Proposed Changes

Don't log errors on resubscribing to topics. Also don't log errors if we are setting already set attnet/syncnet bits.

2021-09-30 06:42 UTC, michaelsproul commented
Assuming this is ready for review?

2021-09-30 12:35 UTC, pawanjay176 commented
Ohh yeah this guy is ready. Sorry forgot to mark it.

2021-10-01 00:00 UTC, AgeManning requested changes
I think we want to return early if the id is already set. 
Re-setting it will increase our ENRs seq id and all our nodes will have to re-download our ENR. 

So I think for both cases (subnet field and current bitfield) we should only change the ENR (and subsequently inform discv5) if something needs to be changed

2021-10-05 00:10 UTC, AgeManning approved these changes
Nice

2021-10-05 22:56 UTC, michaelsproul commented
bors r+

2021-10-06 02:38 UTC, closed without merging