Prevent double import of blocks
sigp/lighthouse pull request #2647
Opened 2021-09-29 14:03 UTC by pawanjay176

## Issue Addressed

Resolves #2611 

## Proposed Changes

Adds a duplicate block root cache to the `BeaconProcessor`. Adds the block root to the cache before calling `process_gossip_block` and `process_rpc_block`. Since `process_rpc_block` is called only for single block lookups, we don't have to worry about batched block imports.

The block is imported from the source(gossip/rpc) that arrives first. The block that arrives second is not imported to avoid the db access issue.
There are 2 cases:
1. Block that arrives second is from rpc: In this case, we return an optimistic `BlockError::BlockIsAlreadyKnown` to sync.
2. Block that arrives second is from gossip: In this case, we only do gossip verification and forwarding but don't import the block into the the beacon chain.

Splits up `process_gossip_block` function to `process_gossip_unverified_block` and `process_gossip_verified_block`.

2021-09-30 06:42 UTC, michaelsproul commented
Is this ready for review too?

2021-09-30 06:57 UTC, pawanjay176 commented
Hey @michaelsproul ran this locally on mainnet last night. Logs are looking good. Wanted to check on some metrics and run this on prater before requesting a review.

2021-09-30 07:02 UTC, michaelsproul commented
Ok cool. Would you mind holding off running it on all the Prater nodes until ~12h from now? I'm testing the v2.0.0-rc there :pray:

2021-09-30 07:03 UTC, pawanjay176 commented
Sure thing, I'll run it on my local node for now.

2021-10-04 07:09 UTC, pawanjay176 commented
Some graphs after running for ~2 days on prater

RPC block processing times for node running this PR
![Screenshot from 2021-10-04 11-41-58](https://user-images.githubusercontent.com/9890508/135804676-99b07298-64c3-487b-8b57-5fb49efd785d.png)

RPC block processing times for nodes running unstable
![Screenshot from 2021-10-04 11-42-33](https://user-images.githubusercontent.com/9890508/135804723-63fb28a0-da66-4144-8c29-20a960d018e5.png)

Gossip block processing times for node running this PR
![Screenshot from 2021-10-04 12-32-20](https://user-images.githubusercontent.com/9890508/135807481-6d5402ed-f941-4550-aaa2-56d7dee76aff.png)

Gossip block processing times for nodes running unstable
![Screenshot from 2021-10-04 11-44-57](https://user-images.githubusercontent.com/9890508/135804732-f1cd7491-b9d9-48f6-9d99-112f67e808b9.png)


The RPC block processing times have come down significantly but there's a slight increase in gossip processing times compared to unstable.

2021-10-08 02:57 UTC, paulhauner requested changes
Nice one, glad to see this is showing positive results on the testnets :tada: I reckon it'll help drop our disk IO significantly.

I have a few minor comments. I'd also be tempted to move this new logic out of the `BeaconProcessor::spawn_worker` function and into the `Worker::process_gossip_block` and `Worker::process_rpc_block` functions. The `spawn_worker` fn doesn't really do anything except spawn the task and it would be cool if we could keep it that way, IMO. Not a big deal if it turns out to be a big issue. We might get some clippy warns for too many function args, I'm happy to ignore those.

2021-10-08 02:57 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/mod.rs
> +    inner: Arc<RwLock<HashSet<Hash256>>>,
This `RwLock` could be a `Mutex` since we never call `read()` on it.

2021-10-08 02:57 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/mod.rs
> +        if !inner.contains(&block_root) {
[HashSet::insert](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.insert) thoughtfully already returns the `bool` you desire. I think you can skip the `contains` call.

2021-10-08 02:57 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/mod.rs
> +#[derive(Default)]
I'm pretty sure you could add `Clone` here and avoid the hand-written `Clone` impl.

2021-10-08 02:57 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/mod.rs
> +                            let block_root = gossip_verified_block.block.canonical_root();
The root is already available on `GossipVerifiedBlock` so we can avoid recomputing it:

https://github.com/sigp/lighthouse/blob/7c88f582d955537f7ffff9b2c879dcf5bf80ce13/beacon_node/beacon_chain/src/block_verification.rs#L400-L404

2021-10-11 09:13 UTC, pawanjay176 commented on beacon_node/network/src/beacon_processor/mod.rs
> +        if !inner.contains(&block_root) {
Neat!

2021-10-11 22:01 UTC, divagant-martian commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                warn!(
Is this worth a `warn` from an user perspective?

2021-10-12 03:33 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                warn!(
Indeed, a `warn` might be a bit concerning for users.

2021-10-12 03:39 UTC, pawanjay176 commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                warn!(
Ahh meant to change this before final review. Thanks for catching it :)

2021-10-18 23:58 UTC, paulhauner requested changes
This is looking good, but I did think up an edge-case with panics whilst doing another read over. Let me know what you think :)

2021-10-18 23:58 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                self.process_gossip_verified_block(
In the scenario where `Worker::process_gossip_verified_block` panics, we're going to be stuck with an expired entry in the duplicate cache. Whilst this *should* never happen, it's some pretty complex stuff happening when processing a gossip block.

If we were to return a "handle" from `DuplicateCache::check_and_insert` which removes the entry on drop, then the the unwinding from the panic will result in the entry being removed from the cache (see [example play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a8dc36915ecd9c356111da6add20a2ad)).

Although it would be pretty terrible if we panic-ed during block import, it would be even worse if we weren't able to import that block again. Especially if the panic was due to some transient IO with the database that would succeed on the next run. I'd guess that we'd eventually import it via a chain-segment/batch sync, but it would be nice to avoid relying on that.

2021-10-19 03:08 UTC, pawanjay176 commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                self.process_gossip_verified_block(
Nice, will make the changes. 
I'm curious if we have seen panics while importing blocks before though?

2021-10-19 19:51 UTC, pawanjay176 commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                self.process_gossip_verified_block(
@paulhauner Realised when testing the fix that we currently shut down the process if any thread panics since #2596 . 
I don't see any non-panic scenario where we would end up with an expired entry in the cache so not sure if we need this?

2021-10-20 07:00 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                self.process_gossip_verified_block(
> I'm curious if we have seen panics while importing blocks before though?

Not that I can remember...

> I don't see any non-panic scenario where we would end up with an expired entry in the cache so not sure if we need this?

That is a very good point. I'll think on this and come back to it.

2021-10-22 19:12 UTC, pawanjay176 commented on beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
> +                self.process_gossip_verified_block(
@paulhauner implemented the handle approach as per our discussion. Doing some additional testing by inducing panics in the worker threads.

2021-10-25 20:05 UTC, divagant-martian commented on beacon_node/network/src/beacon_processor/mod.rs
> +pub struct DuplicateCacheHandle {
Leaving this here for documentation purposes. I would go with generalizing `SendOnDrop` with an `Item = ()` parameter and using that one

2021-10-26 02:57 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/mod.rs
> +    tx: mpsc::Sender<Hash256>,
Instead of this `mpsc::Sender`, it might be simpler to take a clone of the `DuplicateCache` instead. What are your thoughts? It would remove the need to pass the `Sender` around and also avoid the `Receiver` handling code.

2021-10-26 22:06 UTC, pawanjay176 commented on beacon_node/network/src/beacon_processor/mod.rs
> +    tx: mpsc::Sender<Hash256>,
This actually looks cleaner. Implemented it in b7598f3

2021-10-28 03:35 UTC, paulhauner approved these changes
Love it! Let's get this into production :rocket: 

bors r+

2021-10-28 05:38 UTC, closed without merging