[Merged by Bors] - Add fork choice EF tests
sigp/lighthouse pull request #2737
Opened 2021-10-20 06:46 UTC by paulhauner

## Issue Addressed

Resolves #2545

## Proposed Changes

Adds the long-overdue EF tests for fork choice. Although we had pretty good coverage via other implementations that closely followed our approach, it is nonetheless important for us to implement these tests too.

During testing I found that we were using a hard-coded `SAFE_SLOTS_TO_UPDATE_JUSTIFIED` value rather than one from the `ChainSpec`. This caused a failure during a minimal preset test. This doesn't represent a risk to mainnet or testnets, since the hard-coded value matched the mainnet preset.

## Failing Cases

There is one failing case which is presently marked as `SkippedKnownFailure`:

```
case 4 ("new_finalized_slot_is_justified_checkpoint_ancestor") from /home/paul/development/lighthouse/testing/ef_tests/consensus-spec-tests/tests/minimal/phase0/fork_choice/on_block/pyspec_tests/new_finalized_slot_is_justified_checkpoint_ancestor failed with NotEqual:
head check failed: Got Head { slot: Slot(40), root: 0x9183dbaed4191a862bd307d476e687277fc08469fc38618699863333487703e7 } | Expected Head { slot: Slot(24), root: 0x105b49b51bf7103c182aa58860b039550a89c05a4675992e2af703bd02c84570 }
```

This failure is due to #2741. It's not a particularly high priority issue at the moment, so we fix it after merging this PR.

2021-11-02 03:02 UTC, paulhauner commented
This is ready for review! (Pending one last CI run :crossed_fingers:)

2021-11-03 05:09 UTC, michaelsproul requested changes
This is awesome! Really nice clean implementation!

2021-11-03 05:09 UTC, michaelsproul commented on testing/ef_tests/check_all_files_accessed.py
> -    "tests/minimal/altair/fork_choice",
This is so satisfying, well done :clap:

2021-11-03 05:09 UTC, michaelsproul commented on testing/ef_tests/src/handler.rs
> +    // Reuse the blocks case runner.
```suggestion
```

2021-11-03 05:09 UTC, michaelsproul commented on testing/ef_tests/src/handler.rs
> +    // Reuse the blocks case runner.
```suggestion
```

2021-11-03 05:09 UTC, michaelsproul commented on testing/ef_tests/src/cases/fork_choice.rs
> +            // `BeaconChainHarness` and create a hard failure so we can deal with it then.
Yeah I think this is reasonable trade-off. Doing a checkpoint start of the harness should be straight-forward when we need to

2021-11-03 05:09 UTC, michaelsproul commented on testing/ef_tests/src/cases/fork_choice.rs
> +        self.harness.set_current_slot(slot);
I think we should tick to the actual time so that we can observe sub-slot behaviour. E.g. for proposer boosting the boost only applies to blocks which arrive in the first 4 seconds, and I expect we'll be implementing and testing that soon.

We have `set_current_time` on the slot clock, could we use that to set the exact time while also setting fork choice's slot to the result of `tick_to_slot`?

2021-11-08 00:39 UTC, paulhauner commented on testing/ef_tests/src/cases/fork_choice.rs
> +        self.harness.set_current_slot(slot);
Good idea! I noticed the slot duration for the harness was hard-coded. I've modified it to use the value from the spec. I'm not sure why we didn't do that originally, but I'll see what CI thinks of that change.

2021-11-08 00:40 UTC, paulhauner commented
Thanks for the comments! Everything is addressed, I think it's worth waiting for a clean CI run before jumping into a review though :)

2021-11-08 05:14 UTC, michaelsproul approved these changes
Nice!

2021-11-08 07:28 UTC, paulhauner commented
bors r+

2021-11-08 09:00 UTC, closed without merging