[Merged by Bors] - Check proposer index during block production
sigp/lighthouse pull request #2740
Opened 2021-10-21 00:08 UTC by pawanjay176

## Issue Addressed

Resolves #2612 

## Proposed Changes

Implements both the checks mentioned in the original issue. 
1. Verifies the `randao_reveal` in the beacon node
2. Cross checks the proposer index after getting back the block from the beacon node.

## Additional info
The block production time increases by ~10x because of the signature verification on the beacon node (based on the `beacon_block_production_process_seconds` metric) when running on a local testnet.

2021-10-25 05:24 UTC, michaelsproul commented
> The block production time increases by ~10x because of the signature verification on the beacon node (based on the beacon_block_production_process_seconds metric) when running on a local testnet.

I think we should deploy to Prater to see what the impact is there. What time are we talking in absolute terms? Hopefully only a few milliseconds?

Block production on Prater takes 380ms, so the relative impact is probably very small.

2021-10-26 22:14 UTC, pawanjay176 commented
Running this on prater,  `per_block_processing` has jumped to take ~10 ms more than before.

![Screenshot from 2021-10-26 15-08-25](https://user-images.githubusercontent.com/9890508/138968257-6bd6ab7c-ed9f-4123-bd33-bf60c845c641.png)

Total block production times seems to be almost similar

![Screenshot from 2021-10-26 15-12-50](https://user-images.githubusercontent.com/9890508/138968484-4f8bda33-ce79-439a-93d2-a8ebcc1680ed.png)

(Binary was updated at around 18:50 25/10 in the metrics)

2021-10-27 03:03 UTC, michaelsproul commented
Yeah, agree. The impact isn't even visible on the mean/median graph, so I think we're good to go! Will wait for @paulhauner's blessing before merging

2021-10-27 03:06 UTC, michaelsproul requested changes

2021-10-27 03:06 UTC, michaelsproul commented on consensus/state_processing/src/per_block_processing.rs
> +    let verify_randao = if let BlockSignatureStrategy::VerifyRandao = block_signature_strategy {
Ooh, I think this should also be `True` in the case of `BlockSignatureStrategy::VerifyIndividual`. We could use `verify_signatures` in the `else` case to accomplish this (and guard against future additions).

2021-10-27 03:07 UTC, michaelsproul commented on consensus/state_processing/src/per_block_processing/tests.rs
> +        BlockSignatureStrategy::VerifyRandao,
This should probably stay as `VerifyIndividual` as I think this test failure is pointing to the issue I raised above

2021-10-27 03:48 UTC, pawanjay176 commented on consensus/state_processing/src/per_block_processing.rs
> +    let verify_randao = if let BlockSignatureStrategy::VerifyRandao = block_signature_strategy {
Thanks for catching this. Fixed it.

2021-10-27 03:53 UTC, michaelsproul approved these changes
Nice! LGTM

2021-11-01 06:56 UTC, paulhauner approved these changes
Looks good!

2021-11-01 06:57 UTC, paulhauner commented
bors r+

2021-11-01 09:42 UTC, closed without merging