Merge devnet 3
sigp/lighthouse pull request #2859
Opened 2021-12-07 21:52 UTC by pawanjay176

## Issue Addressed

N/A

## Proposed Changes

Changes required for the `merge-devnet-3`. Added some more non substantive renames on top of @realbigsean 's commit. 

This devnet isn't running with the proposer boosting fork choice changes so if we are looking to merge https://github.com/sigp/lighthouse/pull/2822 into `unstable`, then I think we should just maintain this branch for the devnet temporarily.

2021-12-08 10:59 UTC, michaelsproul commented
I actually think it would be fine to merge this. We can hold off merging proposer boosting a bit longer

2021-12-08 21:00 UTC, pawanjay176 commented
I would assume passing the ef tests would require the proposer boosting implementation as well though?

2021-12-09 01:24 UTC, michaelsproul commented
Ah, true. It would be nice to get Docker images though. I guess we could revive the Kintsugi Docker image builder? Alternatively we could mark the proposer boost tests as known failures and merge to `unstable`

2021-12-09 21:11 UTC, paulhauner requested changes
Looks good, thanks for this! I agree with @michaelsproul that we could merge this and then merge #2822 afterwards.

I got the EF tests passing (with some ignored tests) over here: https://github.com/paulhauner/lighthouse/commit/7fe54a6ed7c4bc1340c19132446e38596df711ff

2021-12-09 21:11 UTC, paulhauner commented on beacon_node/execution_layer/src/engine_api/http.rs
> +        dbg!(&body);
```suggestion
```

2021-12-09 21:11 UTC, paulhauner commented on beacon_node/execution_layer/src/engine_api/http.rs
> +
```suggestion
```

2021-12-09 21:11 UTC, paulhauner commented on testing/ef_tests/check_all_files_accessed.py
> +print(missed)
```suggestion
```

I believe each missed file is already printed on [L71](https://github.com/sigp/lighthouse/blob/e19f0cdb49f46e0fd5485c10a4ddfa23c4fcb0c6/testing/ef_tests/check_all_files_accessed.py#L71).

2021-12-09 21:32 UTC, pawanjay176 commented
@paulhauner Done! You can merge when CI passes.

2021-12-10 11:23 UTC, paulhauner commented
bors r+

2021-12-12 09:04 UTC, michaelsproul commented
bors retry

2021-12-12 10:56 UTC, closed without merging