Allow to set validator password via reimport
sigp/lighthouse pull request #2868
Opened 2021-12-17 17:23 UTC by eklm

## Issue Addressed

#2854 

## Proposed Changes

If validator was imported first without entering password and then imported again with valid password update the password in validator_definitions.yml

## Additional Info

There can be other cases for updating existing validator during import. They are not covered here.

2021-12-20 06:44 UTC, michaelsproul requested changes
This is looking great overall! Thanks again!

Other than the minor formatting issue with `rustfmt` the only thing that would be good to add would be a regression test.

We have some account manager tests that you could draw inspiration from here:

https://github.com/sigp/lighthouse/blob/90d5ab15660e62e16390731d92c74b640a70bed9/lighthouse/tests/account_manager.rs#L407

You could start by copying that test, and then modifying it so that no password is input during the first import. Write a blank line here: https://github.com/sigp/lighthouse/blob/90d5ab15660e62e16390731d92c74b640a70bed9/lighthouse/tests/account_manager.rs#L452

Then do a second import writing the actual password, and assert that it makes it into the validator definitions.

Let me know if you run into any issues and I'm more than happy to help. If you're short on time I'm also happy to take your code as-is and add the test myself

2021-12-20 06:44 UTC, michaelsproul commented on account_manager/src/validator/import.rs
> +                    defs.save(&validator_dir).map_err(|e| format!("Unable to save {}: {:?}", CONFIG_FILENAME, e))?;
`rustfmt` wants to split this across two lines, you can apply the diff automatically with `cargo fmt --all`

2021-12-20 15:59 UTC, eklm commented on account_manager/src/validator/import.rs
> +                    defs.save(&validator_dir).map_err(|e| format!("Unable to save {}: {:?}", CONFIG_FILENAME, e))?;
Indeed, applied it.

> Other than the minor formatting issue with rustfmt the only thing that would be good to add would be a regression test.
Ok, cool. Was looking the tests in package directory and didn't find, thanks for pointing to it. No problem, I will add it.

2021-12-21 04:05 UTC, michaelsproul commented on account_manager/src/validator/import.rs
> +                    eprintln!("Update password for public key {}", voting_pubkey);
```suggestion
                    eprintln!("Password updated for public key {}", voting_pubkey);
```

2021-12-21 06:45 UTC, michaelsproul approved these changes
Awesome work, thanks!

2021-12-21 06:45 UTC, michaelsproul commented
bors r+

2021-12-21 10:15 UTC, closed without merging