allow value for fee-recipient argument
sigp/lighthouse pull request #2884
Opened 2021-12-25 16:43 UTC by pk910

## Issue Addressed

The fee-recipient argument of the beacon node does not allow a value to be specified:

> $ lighthouse beacon_node --merge --fee-recipient "0x332E43696A505EF45b9319973785F837ce5267b9"
> error: Found argument '0x332E43696A505EF45b9319973785F837ce5267b9' which wasn't expected, or isn't valid in this context
> 
> USAGE:
>    lighthouse beacon_node --fee-recipient --merge
>
> For more information try --help

## Proposed Changes

Allow specifying a value for the fee-recipient argument in beacon_node/src/cli.rs

## Additional Info

I've added .takes_value(true) and successfully proposed a block in the kintsugi testnet with my own fee-recipient address instead of the hardcoded default. I think that was just missed as the argument does not make sense without a value :)

2021-12-25 16:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=2884) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=2884) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=2884) it.</sub>

2022-01-04 15:00 UTC, realbigsean commented
Oh, nice one! Yeah, looks like it was just missed initially.  Thanks :slightly_smiling_face:

2022-01-06 01:57 UTC, michaelsproul requested changes
Great find, thank you.

To prevent a regression it would be good to add a test next to this one:

https://github.com/sigp/lighthouse/blob/0b54ff17f209e2a627d9b5664bd25cf9566b948c/lighthouse/tests/beacon_node.rs#L88-L94

You can pull out the address with `config.suggested_fee_recipient`. [`H160::from_str`](https://docs.rs/ethereum-types/0.11.0/ethereum_types/struct.H160.html#impl-FromStr) might also be useful to convert the string address to an `Address`.

It looks like the current parser probably doesn't require a 0x prefix, whereas usually we do. If that's the case it would also be good to change the parsing code to require a 0x prefix so it's consistent.

If you don't have time or energy to do this that's also OK. We can do it and still give you credit :blush:

2022-01-06 18:29 UTC, pk910 commented
I've added the test as suggested and a value name for the fee-recipient argument (as all other arguments that take a value have a name, too).

There are currently also no tests for the merge / execution-endpoints arguments.
Shall I add tests for them, too?

Unfortunately I don't have enough rust knowledge to change the parsing thing.
I actually don't see where it is parsed to an Address at all..
It just goes through the generic clap_utils::parse_optional and is used as an Address afterwards?

https://github.com/sigp/lighthouse/blob/0b54ff17f209e2a627d9b5664bd25cf9566b948c/beacon_node/src/config.rs#L256-L261


Happy to help, if it's crap just throw it away, not here for credit collecting 😊

2022-01-07 01:08 UTC, michaelsproul approved these changes
Perfect!

It seems the `Address` deserialisation already neatly handles 0x prefixes, so I think we're good to merge.

I've changed the example address to something a bit more neutral (the eth2 deposit contract), as I noticed the other address existed on mainnet.

Thank you!

2022-01-07 01:08 UTC, michaelsproul commented on lighthouse/tests/beacon_node.rs
> +        .flag("fee-recipient", Some("0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b"))
```suggestion
        .flag("fee-recipient", Some("0x00000000219ab540356cbb839cbe05303d7705fa"))
```

2022-01-07 01:08 UTC, michaelsproul commented on lighthouse/tests/beacon_node.rs
> +        .with_config(|config| assert_eq!(config.suggested_fee_recipient, Some(Address::from_str("0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b").unwrap())));
```suggestion
        .with_config(|config| assert_eq!(config.suggested_fee_recipient, Some(Address::from_str("0x00000000219ab540356cbb839cbe05303d7705fa").unwrap())));
```

2022-01-07 01:21 UTC, michaelsproul commented
bors r+

2022-01-07 03:14 UTC, closed without merging