Document Homebrew package
sigp/lighthouse pull request #2885
Opened 2021-12-26 16:36 UTC by terorie

Resolves #2329

Documents the recently added `lighthouse` Homebrew formula.

NA

## Issue Addressed

Which issue # does this PR address?

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

2021-12-26 16:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=2885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=2885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=2885) it.</sub>

2021-12-28 15:36 UTC, divagant-martian commented
Thanks for your contribution @terorie! 

Right now, every installation mode described in the book (binaries for various platforms + docker + source) are maintained by the lighthouse team. Under the same strategy, I'd argue in favor of moving the `Homebrew` chapter to `Community maintained installers` with an entry for homebrew. It would be good too adding a direct link to the formula's page so that users can check the target platform for this installer directly where it is documented.

Let me know what you think

2021-12-28 19:50 UTC, terorie commented
> Under the same strategy, I'd argue in favor of moving the Homebrew chapter to Community maintained installers with an entry for homebrew.

Makes sense, will do 👍🏻 

> It would be good too adding a direct link to the formula's page so that users can check the target platform for this installer directly where it is documented.

The PR already has links to https://formulae.brew.sh/formula/lighthouse and the source, is this okay?

2022-01-07 01:20 UTC, michaelsproul approved these changes
Thanks!

2022-01-07 01:21 UTC, michaelsproul commented
bors r+

2022-01-07 01:22 UTC, michaelsproul requested changes
Ah, could you please rebase on `unstable` and change the target branch to `unstable`? :pray:

2022-01-07 23:49 UTC, terorie commented
@michaelsproul Yes, sir! Done

2022-01-08 01:11 UTC, michaelsproul commented on book/src/homebrew.md
> +The [formula] is kept up-to-date by the Homebrew community and a bot that lists for new releases.
```suggestion
The [formula][] is kept up-to-date by the Homebrew community and a bot that lists for new releases.
```

No-op change to trigger Github's CI

2022-01-08 01:14 UTC, michaelsproul commented
bors r+

2022-01-08 01:15 UTC, michaelsproul approved these changes

2022-01-08 03:07 UTC, closed without merging