Allow proposer duties request for the next epoch
sigp/lighthouse pull request #2963
Opened 2022-01-26 19:06 UTC by eklm

## Issue Addressed

#2880 

## Proposed Changes

Support requests to the next epoch in proposer_duties api.

## Additional Info

Implemented with skipping proposer cache for this case because the cache for the future epoch will be missed every new slot as dependent_root is changed and we don't want to "wash it out" by saving additional values.

2022-02-10 21:19 UTC, realbigsean requested changes
Sorry for taking while to check this out, but thanks a lot for your work  :slightly_smiling_face: 

I just had a minor comment

2022-02-10 21:19 UTC, realbigsean commented on beacon_node/http_api/src/proposer_duties.rs
>      } else if request_epoch > current_epoch {
We can update this condition to reflect the change, as well as the comment and error in this block

2022-02-10 21:19 UTC, realbigsean commented on beacon_node/http_api/tests/tests.rs
> +            "should not prime the proposer cache outside of tolerance"
Nice adjustment for this test!

2022-02-11 15:56 UTC, eklm commented
@realbigsean Thanks for reviewing it! I added suggested adjustments.

2022-02-11 19:02 UTC, realbigsean approved these changes

2022-02-18 02:27 UTC, michaelsproul approved these changes
LGTM!

2022-02-18 02:36 UTC, michaelsproul commented
bors r+

2022-02-18 07:22 UTC, closed without merging