Rename Eth1/Eth2 in documents
sigp/lighthouse pull request #3021
Opened 2022-02-14 15:05 UTC by ackintosh

## Issue Addressed

Resolves https://github.com/sigp/lighthouse/issues/3019

## Additional Info

2022-02-14 15:11 UTC, ackintosh commented on book/src/key-management.md
> +> **Note: we recommend using the [Staking launchpad][launchpad] to create validators.**
ref: https://launchpad.ethereum.org/
> Staking Launchpad

2022-02-22 14:54 UTC, realbigsean commented on book/src/api-bn.md
> +Lighthouse implements the standard [Eth Beacon Node API
```suggestion
Lighthouse implements the standard [Beacon Node API
```

2022-02-22 14:54 UTC, realbigsean commented on book/src/api-bn.md
> +All endpoints are documented in the [Eth Beacon Node API
```suggestion
All endpoints are documented in the [Beacon Node API
```

2022-02-22 14:55 UTC, realbigsean commented on book/src/api-lighthouse.md
> +The `state_id` parameter is identical to that used in the [Standard Eth Beacon Node API
```suggestion
The `state_id` parameter is identical to that used in the [Standard Beacon Node API
```

2022-02-22 14:57 UTC, realbigsean commented on book/src/faq.md
> +Since the beacon chain uses execution client for validator on-boarding, beacon chain
```suggestion
Since the beacon chain uses the execution layer for validator on-boarding, beacon chain
```

2022-02-22 16:13 UTC, realbigsean commented on book/src/faq.md
> +where beacon validators vote on which execution layer to include in the beacon chain. This
```suggestion
where beacon validators vote on which execution block hash to include in the beacon chain. This
```

2022-02-22 16:21 UTC, realbigsean commented on book/src/key-recovery.md
> +where `network` is the name of consensus layer passed in the `--network` parameter (default is `mainnet`).
```suggestion
where `network` is the name of the consensus layer network passed in the `--network` parameter (default is `mainnet`).
```

2022-02-22 16:22 UTC, realbigsean commented on book/src/mainnet-validator.md
> +> due to the actions of other actors on consensus layer or software bugs. See the
```suggestion
> due to the actions of other actors on the consensus layer or software bugs. See the
```

2022-02-22 16:22 UTC, realbigsean commented on book/src/mainnet-validator.md
> +The Ethereum Foundation provides an "Staking launch pad" for creating validator keypairs and submitting
```suggestion
The Ethereum Foundation provides a "Staking launchpad" for creating validator keypairs and submitting
```

2022-02-22 16:23 UTC, realbigsean commented on book/src/mainnet-validator.md
> +Since consensus client relies upon the execution chain for validator on-boarding, all consensus validators must have a
```suggestion
Since the consensus chain relies upon the execution chain for validator on-boarding, all consensus validators must have a
```

2022-02-22 16:28 UTC, realbigsean commented on book/src/slashing-protection.md
> +The security of Ethereum proof of stake protocol depends on penalties for misbehaviour, known
```suggestion
The security of the Ethereum proof-of-stake protocol depends on penalties for misbehaviour, known
```

2022-02-22 16:29 UTC, realbigsean commented on book/src/validator-doppelganger.md
> +"doppelganger" in consensus client refers to another instance of a validator running in a separate validator
```suggestion
"doppelganger" in the context of Ethereum proof-of-stake refers to another instance of a validator running in a separate validator
```

2022-02-22 16:30 UTC, realbigsean commented on book/src/validator-import-launchpad.md
> +command-line program to generate consensus client validator keys.
```suggestion
command-line program to generate consensus validator keys.
```

2022-02-22 16:31 UTC, realbigsean commented on book/src/voluntary-exit.md
> +To understand the phased rollout strategy for consensus client, please visit <https://ethereum.org/en/upgrades/#roadmap>.
```suggestion
To understand the phased rollout strategy for Ethereum upgrages, please visit <https://ethereum.org/en/upgrades/#roadmap>.
```

2022-02-22 16:31 UTC, realbigsean commented on book/src/voluntary-exit.md
> +- The `--beacon-node` flag is used to specify a beacon chain HTTP endpoint that confirms to the [Eth Beacon Node API](https://ethereum.github.io/beacon-APIs/) specifications. That beacon node will be
```suggestion
- The `--beacon-node` flag is used to specify a beacon chain HTTP endpoint that confirms to the [Beacon Node API](https://ethereum.github.io/beacon-APIs/) specifications. That beacon node will be used to validate and propagate the voluntary exit. The default value for this flag is `http://localhost:5052`.
```

2022-02-22 16:57 UTC, realbigsean requested changes
Thanks a lot for this @ackintosh !

2022-02-23 03:58 UTC, ackintosh commented
@realbigsean Thank you for your review!

2022-02-28 18:54 UTC, realbigsean requested changes
Sorry I had a couple more tiny ones I think I missed before!

2022-02-28 18:54 UTC, realbigsean commented on book/src/api-bn.md
> +The schema of the API aligns with the standard Eth Beacon Node API as defined
```suggestion
The schema of the API aligns with the standard Beacon Node API as defined
```

2022-02-28 18:54 UTC, realbigsean commented on book/src/redundancy.md
> +be tried each time the first fails. execution client endpoints will be tried from first to
```suggestion
be tried each time the first fails. Execution client endpoints will be tried from first to
```

2022-03-01 15:22 UTC, realbigsean approved these changes
Thanks a ton @ackintosh !

2022-03-02 00:01 UTC, AgeManning commented
bors r+

2022-03-02 03:14 UTC, closed without merging