Clarify proposers message is about current epoch
sigp/lighthouse pull request #3084
Opened 2022-03-14 00:31 UTC by kraemahz

## Issue Addressed

#3083

## Proposed Changes

Changes "proposers" to "proposers_this_epoch" in the validator log message.

2022-03-14 00:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3084) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3084) before we can accept your contribution.<br/><hr/>**Teague Lasser** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3084) it.</sub>

2022-03-14 00:41 UTC, michaelsproul approved these changes
Awesome, thank you!

Will merge this immediately after the v2.1.4 release, which is in its final stages (~24h)

2022-03-14 00:43 UTC, paulhauner requested changes
Nice suggestion, I think this makes things clearer. :pray: 

I have a suggestion to use `current_epoch_proposers` since it's a bit more in-line with the frequent usage of "current" and "previous" epochs in the spec.

2022-03-14 00:43 UTC, paulhauner commented on validator_client/src/notifier.rs
> +                "proposers_this_epoch" => proposing_validators,
```suggestion
                "current_epoch_proposers" => proposing_validators,
```

2022-03-14 00:43 UTC, paulhauner commented on validator_client/src/notifier.rs
> +                "proposers_this_epoch" => proposing_validators,
```suggestion
                "current_epoch_proposers" => proposing_validators,
```

2022-03-17 01:10 UTC, michaelsproul commented
bors r+

2022-03-17 03:33 UTC, michaelsproul commented
bors retry

2022-03-17 05:14 UTC, closed without merging