Correct typos book
sigp/lighthouse pull request #3099
Opened 2022-03-18 06:21 UTC by emhane

## Issue Addressed

No issue

## Proposed Changes

Correct typos in book

## Additional Info

Nothing to add

2022-03-18 06:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3099) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3099) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3099) it.</sub>

2022-03-18 07:39 UTC, macladson requested changes
Just had one little comment, but otherwise looks good :+1:

2022-03-18 07:39 UTC, macladson commented on book/src/suggested-fee-recipient.md
> +The `suggested_fee_recipient` can be provided to the VC, who will transmit it to the BN. Then also BN
I would probably say:
```suggestion
The `suggested_fee_recipient` can be provided to the VC, who will transmit it to the BN. The BN also
```

2022-03-18 07:55 UTC, macladson approved these changes
Perfect!

2022-03-20 22:43 UTC, michaelsproul approved these changes
Awesome, thanks!

bors r+

2022-03-20 22:47 UTC, michaelsproul commented
briefly cancelling this so I can include it in a batch with #3056

bors r-

2022-03-20 22:47 UTC, michaelsproul commented
bors r+

2022-03-21 00:51 UTC, closed without merging