Tim/add remote keys
sigp/lighthouse pull request #3162
Opened 2022-04-18 18:54 UTC by tthebst

## Issue Addressed

#3068

## Proposed Changes

Adds support for remote key API.

## Additional Info

Needed to add `is_local_keystore`  argument to `delete_definition_and_keystore` to know if we want to delete local or remote key. Previously this wasn't necessary because remotekeys(web3signers) could be deleted.

2022-04-18 19:00 UTC, tthebst commented on validator_client/src/http_api/tests.rs
> +// DO NOT MERGE
I will remove this after the review. Rust analyzer does not recognize the test file with this option.

2022-05-06 06:00 UTC, michaelsproul requested changes
This is absolutely fantastic, thank you so much for taking the time to implement it :heart:

I think we're super close to being able to merge. There's just one minor change required to the list keys API, and some nitpicks.

Thanks again!

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/create_validator.rs
> +    validators: &[ValidatorDefinition],
We could pass the `Vec` here and avoid the clone below, it seems we only ever call this before immediately discarding the vec of definitions.

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/mod.rs
> +                            .iter()
```suggestion
                            .into_iter()
```

If we use `into_iter` here we can avoid the `clone`s below.

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/remotekeys.rs
> +use std::sync::Weak;
```suggestion
use std::sync::{Arc, Weak};
```

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/remotekeys.rs
> +                SigningDefinition::LocalKeystore { .. } => (None, Some(true)),
We shouldn't list local keystores on the remotekeys endpoint.

Therefore I don't think we should ever set `readonly: true`, because all our remote keys are capable of being changed. Some other clients have a concept of immutable keys that can't be removed, e.g. ones passed on the command line.

2022-05-06 06:00 UTC, michaelsproul commented on common/eth2/src/lighthouse_vc/std_types.rs
> +    pub readonly: Option<bool>,
My reading of the spec is that the `readonly` flag is mandatory and that we should be setting it to `false` for all our responses:

https://github.com/ethereum/keymanager-APIs/blob/2bfc4307fcf48697aab66b5336a06506463749b3/types/signer_definition.yaml#L8-L10

2022-05-06 06:00 UTC, michaelsproul commented on common/eth2/src/lighthouse_vc/std_types.rs
> +    pub url: Option<String>,
The `url` is also mandatory, and we can satisfy that requirement if we avoid listing local keystores.

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/remotekeys.rs
> +pub fn delete<T: SlotClock + 'static, E: EthSpec>(
```suggestion

pub fn delete<T: SlotClock + 'static, E: EthSpec>(
```

A newline before this func would be nice

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/tests.rs
> +// DO NOT MERGE
All good, we can remove just before merging.

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/tests/keystores.rs
> +        // Check that both local and remote validators are returned.
This will need to be modified to just check for the remote keys (it's a good test nonetheless)

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/tests/keystores.rs
> +fn delete_then_reimport_remotekeys() {
Another variation of this test that would be good to have would be deleting a key and then re-importing it with a different URL. I'm happy to write it if you don't have the time

2022-05-06 06:00 UTC, michaelsproul commented on validator_client/src/http_api/tests/keystores.rs
> +fn import_remotekey_web3signer() {
Awesome test!

There are a few other web3signer API interactions that might be interesting to test:

1. Importing a key with the web3signer API with `enabled: false` and then re-importing it with the remote keys API (I think we will overwrite the disabled entry).
2. Importing a key with the web3signer API with `enabled: true` and then re-importing it with the remote keys API (I think this should be a duplicate). Might be interesting to see what happens to the remote certificate/etc as well.

2022-05-06 19:06 UTC, tthebst commented on validator_client/src/http_api/remotekeys.rs
> +use std::sync::Weak;
classic :)

2022-05-06 19:35 UTC, tthebst commented on validator_client/src/http_api/remotekeys.rs
> +pub fn delete<T: SlotClock + 'static, E: EthSpec>(
cargo fmt where are you :)

2022-05-08 23:14 UTC, michaelsproul approved these changes
Latest changes look great! There are just two things we need to do before merging:

1. Remove the `// DO NOT MERGE` section
2. Satisfy Clippy: https://github.com/sigp/lighthouse/runs/6343319556?check_suite_focus=true

2022-05-09 07:21 UTC, michaelsproul commented
LFG! :rocket: 

bors r+

2022-05-09 09:43 UTC, closed without merging