Remove DB migrations for legacy database schemas
sigp/lighthouse pull request #3181
Opened 2022-05-16 00:12 UTC by macladson

## Proposed Changes

Remove support for DB migrations to support upgrading from schema's below version 5. This is mostly for cosmetic/code quality reasons as in most circumstances upgrading from versions of Lighthouse this old will almost always require a re-sync.

## Additional Info

The minimum supported database schema is now version 5.

2022-05-16 23:14 UTC, michaelsproul requested changes
Looking great, love the red :fire:

I think there are a few more bits and pieces we can remove in the process, happy to merge after that

2022-05-16 23:14 UTC, michaelsproul commented on beacon_node/beacon_chain/src/schema_change.rs
> -                .get_item::<PersistedOperationPoolBase<T::EthSpec>>(&OP_POOL_DB_KEY)?
I think we can also remove some of the code related to `PersistedOperationPoolBase`. It's a `superstruct`, and it might be nice to keep it as a superstruct but with the `Base` variant removed (along with all the conversion/handling for that like `base_to_altair`).

2022-05-16 23:14 UTC, michaelsproul commented on beacon_node/beacon_chain/src/schema_change.rs
> -            if let Some(OnDiskStoreConfigV4 {
We can also delete the `OnDiskStoreConfigV4` that's defined later in this file.

2022-05-17 01:47 UTC, rsalvo77 approved these changes

2022-05-17 04:52 UTC, michaelsproul approved these changes
Nice :sunglasses:

2022-05-17 04:54 UTC, michaelsproul commented
bors r+

2022-05-17 06:59 UTC, closed without merging