Implement feerecipient API for keymanager
sigp/lighthouse pull request #3213
Opened 2022-05-24 03:25 UTC by ethDreamer

## Issue Addressed

* #3173 

## Proposed Changes

Moved all `fee_recipient_file` related logic inside the `ValidatorStore` as it makes more sense to have this all together there. I tested this with the validators I have on `mainnet-shadow-fork-5` and everything appeared to work well. Only technicality is that I can't get the method to return `401` when the authorization header is not specified (it returns `400` instead). Fixing this is probably quite difficult given that none of `warp`'s rejections have code `401`.. I don't really think this matters too much though as long as it fails.

2022-05-24 15:37 UTC, ethDreamer commented
For convenience, this is how the fee recipient page of the lighthouse book renders:
![fee_recipient](https://user-images.githubusercontent.com/37123614/170075694-9d8b0ff0-eb67-4de0-b421-dcc97231f631.png)

2022-05-24 21:21 UTC, realbigsean requested changes
Nice! Couple of small things. Moving the fee recipient file management to the validator store makes sense to me as well.

2022-05-24 21:21 UTC, realbigsean commented on common/eth2/src/lighthouse_vc/std_types.rs
> +pub struct GetFeeRecipientResponse {
I think you should be able to use the `GenericResponse<T>` type here instead of creating a new wrapper.

2022-05-24 21:21 UTC, realbigsean commented on validator_client/src/initialized_validators.rs
> +    pub async fn set_validator_fee_recipient(
I don't think this needs to be async

2022-05-24 21:21 UTC, realbigsean commented on validator_client/src/http_api/mod.rs
> +                                    e
If `set_validator_fee_recipient` is non-async I think we can get rid of this `block_on`

2022-05-25 19:59 UTC, ethDreamer commented on common/eth2/src/lighthouse_vc/std_types.rs
> +pub struct GetFeeRecipientResponse {
nice catch! done!

2022-05-25 20:02 UTC, ethDreamer commented on validator_client/src/initialized_validators.rs
> +    pub async fn set_validator_fee_recipient(
ahhh yeah an earlier version of this function had `self.update_validators().await` but I removed it and forgot to remove the `async` - thanks!

2022-05-25 20:02 UTC, ethDreamer commented on validator_client/src/http_api/mod.rs
> +                                    e
done!

2022-05-27 05:17 UTC, michaelsproul requested changes
Looks good

I think it would be good to add a test or two in `validator_client/src/http_api/tests/keystores.rs`. The rest of the API is quite well tested and I think it would be straight forward to incorporate some feerecipient tests

2022-06-03 21:01 UTC, ethDreamer commented
I added some tests which test the API endpoint as well as the `fee_recipient_file` fallback functionality..
@realbigsean and I were talking and we were wondering if we should just remove the `fee_recipient_file` functionality entirely now that we have an API endpoint to set the `fee_recipient` on the fly that will override the file if used.

It seems like it's redundant and less desirable now. On top of that, if we are to remove this, we should do it before the merge when people might start using it in their workflows..

what do you guys think @paulhauner @michaelsproul ?

2022-06-09 23:41 UTC, michaelsproul reviewed
I'm on the fence about deleting the fee-recipient file. I think seeing as we already have it we might as well keep it. I think it might also be easier for some users to work with than the HTTP API. E.g. you can can update the `default` without knowing the pubkey of the validator you want to update the fee recipient for (which could be useful for some kinds of round-robin).

Other than that, there's also the matter of the recently added delete API: https://github.com/ethereum/keymanager-APIs/pull/30. We could add it to this PR before merging, or bring it in separately seeing as this PR is already nicely self-contained and has been sitting in the merge queue so long. What's your preference @ethDreamer?

2022-06-16 18:40 UTC, realbigsean commented on book/src/suggested-fee-recipient.md
>  Assuming trustworthy nodes, the priority for the four methods is:
```suggestion
Assuming trustworthy nodes, the priority for the three methods is:
```

2022-06-16 18:41 UTC, realbigsean commented
Keeping the fee recipient file and storing fee recipients in the `validator_definitions` file seems like it adds too much complexity to be worth it to me. We'd have to decide whether to persist it in one place or both after API requests, and then also determine fallback order in different scenarios. I don't think these would be intuitive to users and we wouldn't want that to lead to misconfigurations that aren't apparent until proposal.  To me it makes the most sense to have a single source of truth.

Would it be better to create a `default_fee_recipient` field in the `validator_definitions` file and re-use the logic from the fee recipient file around that?

2022-07-06 02:30 UTC, michaelsproul approved these changes
Let's merge this now and come back for future enhancements:

1) _If_ the fee recipient setting API proves too slow with large number of validators, optimise it (possibly by batching disk writes), or if that isn't possible, add an alternative mechanism for loading fee recipients in bulk (possibly from a URL a la Teku).
2) Add a `default` field for the fee recipient in the `validator_definitions.yml`. For now this can be worked around by using the process-level default (i.e. the value of the `--suggested-fee-recipient` flag).

2022-07-06 02:30 UTC, michaelsproul commented
bors r+

2022-07-06 03:16 UTC, michaelsproul commented
CI failure looks spurious, I'll restart the batch

bors r-

2022-07-06 03:17 UTC, michaelsproul commented
bors r+

2022-07-06 06:15 UTC, closed without merging