Add a new bls test
sigp/lighthouse pull request #3235
Opened 2022-06-01 03:11 UTC by zsluedem

## Issue Addressed

Which issue # does this PR address?
#2629 

## Proposed Changes

Please list or describe the changes introduced by this PR.

1. ci would dowload the bls test cases from https://github.com/ethereum/bls12-381-tests/
2. all the bls test cases(except eth ones) would use cases in the archive from step one
3. The bls test cases from https://github.com/ethereum/consensus-spec-tests would stay there and no use . For the future , these bls test cases would be remove suggested from https://github.com/ethereum/consensus-spec-tests/issues/25 . So it would do no harm and compatible for future cases.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

2022-06-06 03:46 UTC, michaelsproul commented
hi @zsluedem is this ready for review?

2022-06-06 07:37 UTC, zsluedem commented
> hi @zsluedem is this ready for review?

@michaelsproul There is one thing which I am not sure. Do you need the tests `deserialization_G1`, `deserialization_G2` and `hash_to_G2`. If you don't need that, it is ready to review now.

2022-10-04 06:13 UTC, paulhauner requested changes
This is super clean and tidy, I couldn't have suggested a better method of implementation :rocket:

I apologise for letting this PR linger for so long, it's a great contribution and deserved to be merged sooner.

I have a few suggestions here, mostly just minor nit-picks. If I'm clever enough, you might be able to just commit the suggestions and still compile and get past the linter (spoiler, I'm probably not clever enough).

There is a merge conflict for which I couldn't resolve via a suggestion. That should be an easy fix though.

Once again, thanks for this. If you're able to address these comments I'll make sure it gets merged quickly :pray:

2022-10-04 06:13 UTC, paulhauner commented on testing/ef_tests/src/handler.rs
> +                        .filter(|e| e.file_type().map(|ty| ty.is_file()).unwrap_or(false))
```suggestion
                        .filter(|e| e.file_type().map(|ty| ty.is_file()).unwrap())
```

I thought this may follow the "fail loudly" ethos more closely? My understanding is that this should never fail unless there's a filesystem/IO error, but perhaps I've missed something?

2022-10-04 06:13 UTC, paulhauner commented on testing/ef_tests/src/cases/bls_batch_verify.rs
> +#[derive(Debug, Clone, Deserialize)]
```suggestion

#[derive(Debug, Clone, Deserialize)]
```

Just a minor consistency nitpick :pray:

2022-10-04 06:13 UTC, paulhauner commented on testing/ef_tests/src/cases/common.rs
>  /// Macro to wrap U128 and U256 so they deserialize correctly.
```suggestion

/// Macro to wrap U128 and U256 so they deserialize correctly.
```

2022-10-04 06:13 UTC, paulhauner commented on testing/ef_tests/src/cases/bls_batch_verify.rs
> +use std::borrow::Cow;
```suggestion
use std::borrow::Cow;
use std::str::FromStr;
```

Required for a later suggestion.

2022-10-04 06:13 UTC, paulhauner commented on testing/ef_tests/src/cases/bls_batch_verify.rs
> +            })
```suggestion
            .map(|s| Hash256::from_str(s).map_err(|e| Error::FailedToParseTest(format!("{:?}", e))))
```

Just a minor simplification.

2022-10-04 06:13 UTC, paulhauner commented on testing/ef_tests/src/cases/bls_batch_verify.rs
> +            })
```suggestion
            .map(|s| {
                Signature::from_str(s).map_err(|e| Error::FailedToParseTest(format!("{:?}", e)))
            })
```

Another minor simplification.

2022-10-05 08:41 UTC, zsluedem commented on testing/ef_tests/src/handler.rs
> +                        .filter(|e| e.file_type().map(|ty| ty.is_file()).unwrap_or(false))
I think I forgot because it was long ago. But I think it is no harm to fail loudly here.

2022-10-05 08:42 UTC, zsluedem commented
@paulhauner Conflicts resolved and comments addressed.

2022-10-12 17:16 UTC, paulhauner commented on testing/ef_tests/src/handler.rs
> +                        .filter(|e| e.file_type().map(|ty| ty.is_file()).unwrap_or(false))
I don't think this got implemented but I'm OK with that because any missed files should be detected via the "all files checked" script.

2022-10-12 17:17 UTC, paulhauner approved these changes
Great work, thank you!

2022-10-12 23:40 UTC, michaelsproul commented
bors r+

2022-10-13 02:21 UTC, closed without merging