Add more features to `lcli skip-slots`
sigp/lighthouse pull request #3252
Opened 2022-06-09 06:06 UTC by paulhauner

## Issue Addressed

NA

## Proposed Changes

Modifies `lcli skip-slot` to give it more features, namely:

- Ability to pull a `BeaconState` from a HTTP URL.
- Do repeat runs via `--runs`.
- Output timing information.
- Ability for partial state advance via `--partial-state-advance`.

Examples:

Download a state from a HTTP endpoint and skip forward an epoch, twice (the initial state is advanced 32 slots twice, rather than it being advanced 64 slots): 

```
lcli skip-slots --beacon-url http://localhost:5052 --state-id 0x3cdc33cd02713d8d6cc33a6dbe2d3a5bf9af1d357de0d175a403496486ff845e --slots 32 --runs 2
```

Download a state to a SSZ file (without modifying it):

```
lcli skip-slots --beacon-url http://localhost:5052 --state-id 0x3cdc33cd02713d8d6cc33a6dbe2d3a5bf9af1d357de0d175a403496486ff845e --slots 0 --runs 0 --output-path /tmp/state-0x3cdc.ssz
```

Do two runs over the state that was downloaded in the previous example:

```
lcli skip-slots --state-path /tmp/state-0x3cdc.ssz --slots 32 --runs 2
```

## Additional Info

NA

2022-07-12 20:58 UTC, realbigsean requested changes
Mostly just some typos, these new commands look really useful!

2022-07-12 20:58 UTC, realbigsean commented on lcli/src/main.rs
> +                    Arg::with_name("state-path")
in the `transition-blocks` subcommand this is named `pre-state-path` so might be better to keep it consistent

2022-07-12 20:58 UTC, realbigsean commented on lcli/src/skip_slots.rs
> +        _ => return Err("mut supply either --state-file or --beacon-url".into()),
```suggestion
        _ => return Err("must supply either --state-path or --beacon-url".into()),
```

2022-07-12 20:58 UTC, realbigsean commented on lcli/src/skip_slots.rs
> +                .ok_or("shut down in progress")?
```suggestion
                .ok_or("shutdown in progress")?
```

2022-07-12 20:58 UTC, realbigsean commented on lcli/src/skip_slots.rs
> +                .map_err(|e| format!("Unable to perform partial advance: {:?}", e))?;
```suggestion
                .map_err(|e| format!("Unable to perform complete advance: {:?}", e))?;
```

2022-07-12 20:58 UTC, realbigsean commented on lcli/src/transition_blocks.rs
> +//! beaconAPI. Advance the pre-state to the slot of the 0x6c69 and apply that block to the
```suggestion
//! beaconAPI. Advance the pre-state to the slot of the 0x6c69 block and apply that block to the
```

2022-07-12 20:58 UTC, realbigsean commented on lcli/src/transition_blocks.rs
> +                .ok_or("shut down in progress")?
```suggestion
                .ok_or("shutdown in progress")?
```

2022-07-12 20:58 UTC, realbigsean commented on lcli/src/transition_blocks.rs
> +     * Write artefacts to disk, if required.
```suggestion
     * Write artifacts to disk, if required.
```

2022-08-09 04:08 UTC, paulhauner commented
All comments addressed, I'm going to add "ready for bors" since this is just an lcli command and seems to have implicit approval.

2022-08-09 04:09 UTC, paulhauner commented
I'm flagging this as backwards-incompat just so that we remember to mention it in the release notes. I don't think that changes to `lcli` should *actually* be considered "breaking changes" to Lighthouse.

2022-08-09 06:04 UTC, michaelsproul commented
bors r+

2022-08-09 08:46 UTC, closed without merging