[WIP] Remove engines fallback from the `execution_layer` crate
sigp/lighthouse pull request #3257
Opened 2022-06-09 15:07 UTC by divagant-martian

## Issue Addressed

Part of #3160 

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

2022-06-09 20:24 UTC, divagant-martian commented on beacon_node/execution_layer/src/lib.rs
> +        let i = 0usize;
This looks horrible, but I don't want to touch the `EngineError::Api` (which contains the id) to keep the changes minimal

2022-06-10 10:43 UTC, pawanjay176 approved these changes
LGTM. I thought the `EngineErrors` doesn't need to be a vec anymore but we can change that after we switch to a single builder as you mentioned

2022-06-22 05:15 UTC, paulhauner commented on beacon_node/execution_layer/src/engines.rs
>  /// Holds multiple execution engines and provides functionality for managing them in a fallback
Perhaps we could quickly change this comment to say it holds a single execution engine?

2022-06-22 05:17 UTC, paulhauner requested changes
Looks good, I only have a couple of really minor suggestions.

We'll have to come back and clean this up, but I appreciate that this will unblocks #3094 and I think this PR is a good way to do that :)

2022-06-22 05:17 UTC, paulhauner commented on beacon_node/execution_layer/src/engines.rs
>  /// Holds multiple execution engines and provides functionality for managing them in a fallback
Perhaps we could quickly change this comment to say it holds a single execution engine?

2022-06-22 05:17 UTC, paulhauner commented on beacon_node/execution_layer/src/lib.rs
> +            info!(log, "Only the first execution engine url will be used");
```suggestion
            warn!(log, "Only the first execution engine url will be used");
```

Just a suggestion, might be nice to be louder about it.

2022-06-22 07:50 UTC, paulhauner approved these changes
LGTM! Feel free to bors at will :)

2022-06-22 14:26 UTC, divagant-martian commented
bors r+

2022-06-22 16:23 UTC, closed without merging