Add Goerli `--network` flag as duplicate of Prater
sigp/lighthouse pull request #3346
Opened 2022-07-19 07:11 UTC by paulhauner

## Issue Addressed

- Resolves #3338

## Proposed Changes

This PR adds a new `--network goerli` flag that reuses the [Prater network configs](https://github.com/sigp/lighthouse/tree/stable/common/eth2_network_config/built_in_network_configs/prater).

As you'll see in #3338, there are several approaches to the problem of the Goerli/Prater alias. This approach achieves:

1. No duplication of the genesis state between Goerli and Prater.
    - Upside: the genesis state for Prater is ~17mb, duplication would increase the size of the binary by that much.
2. When the user supplies `--network goerli`, they will get a datadir in `--network goerli`.
    - Upside: our docs stay correct when they declare a datadir is located at `~/.lighthouse/{network}`
    - Downside: switching from `--network prater` to `--network goerli` will require some manual migration. 
3. When using `--network goerli`, the [`config/spec`](https://ethereum.github.io/beacon-APIs/#/Config/getSpec) endpoint will return a [`CONFIG_NAME`](https://github.com/ethereum/consensus-specs/blob/02a2b71d64fcf5023a8bd890dabce774a6e9802e/configs/mainnet.yaml#L11) of "prater".
    - Upside: VC running `--network prater` will still think it's on the same network as one using `--network goerli`.
    - Downside: potentially confusing.

## Additional Info

### Notes for reviewers:

In https://github.com/sigp/lighthouse/commit/e4896c268217e501ab581ce857d526572b235b91 you'll see that I remove the `$name_str` by just using `stringify!($name_ident)` instead. This is a simplification that should have have been there in the first place.

Then, in https://github.com/sigp/lighthouse/commit/90b5e22fca366c1db741c6d8f02902d9e375279f I reclaim that second parameter with a new purpose; to specify the directory from which to load configs.

2022-07-19 07:15 UTC, paulhauner commented
Once we get consensus that this is a good idea I'll add some docs to this PR.

2022-07-19 07:24 UTC, paulhauner commented
I've raised this for discussion on a public Discord: https://discord.com/channels/595666850260713488/892088344438255616/998851248965038180

2022-07-19 22:37 UTC, paulhauner commented
> No duplication of the genesis state between Goerli and Prater. 

I was wrong about this, the genesis state is duplicated in the binary. I'm going to see if I can avoid that now.

2022-07-20 07:49 UTC, paulhauner commented
> I was wrong about this, the genesis state is duplicated in the binary. I'm going to see if I can avoid that now.

I was actually wrong about *this*! It appears that Rust automatically dedups two instances of `include_bytes!` which point to the same file :tada: 

```
println!(
  "{}.genesis_state_bytes: {:p}",
  net.name, net.genesis_state_bytes
);

mainnet.genesis_state_bytes: 0x557f25d33bcf
prater.genesis_state_bytes: 0x557f2625c1ec
goerli.genesis_state_bytes: 0x557f2625c1ec
gnosis.genesis_state_bytes: 0x557f27ec2cb2
kiln.genesis_state_bytes: 0x557f281d4861
ropsten.genesis_state_bytes: 0x557f29137380
sepolia.genesis_state_bytes: 0x557f2a015a99
```

2022-07-20 22:28 UTC, realbigsean requested changes

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
>      pub unique_id: &'a str,
I'm not seeing the `unique_id` used anywhere anymore

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        // The name of the directory in the `eth2_network_configs/build_in_network_configs`
```suggestion
        // The name of the directory in the `eth2_network_config/built_in_network_configs`
```

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        // The name of the directory in the `eth2_network_configs/build_in_network_configs`
```suggestion
        // The name of the directory in the `eth2_network_config/built_in_network_configs`
```

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        // The name of the directory in the `eth2_network_configs/build_in_network_configs`
```suggestion
        // The name of the directory in the `eth2_network_config/built_in_network_configs`
```

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        // The name of the directory in the `eth2_network_configs/build_in_network_configs`
```suggestion
        // The name of the directory in the `eth2_network_config/built_in_network_configs`
```

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        // The name of the directory in the `eth2_network_configs/build_in_network_configs`
```suggestion
        // The name of the directory in the `eth2_network_config/built_in_network_configs`
```

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        // The name of the directory in the `eth2_network_configs/build_in_network_configs`
```suggestion
        // The name of the directory in the `eth2_network_config/built_in_network_configs`
```

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
> +        // The name of the directory in the `eth2_network_configs/build_in_network_configs`
```suggestion
        // The name of the directory in the `eth2_network_config/built_in_network_configs`
```

2022-07-20 22:28 UTC, realbigsean commented on common/eth2_config/src/lib.rs
>      pub unique_id: &'a str,
I'm not seeing `unique_id` being used anywhere anymore so I think it can be removed

2022-07-20 22:29 UTC, realbigsean commented
Just had some tiny annoying feedback on this one :slightly_smiling_face:

2022-07-20 22:40 UTC, paulhauner commented
Not annoying at all, great points! Thank you :)

All comments addressed.

2022-07-20 22:44 UTC, paulhauner commented
Feel free to bors when approval is granted :pray:

2022-07-20 23:04 UTC, realbigsean approved these changes

2022-07-20 23:04 UTC, realbigsean commented
bors r+

2022-07-21 01:19 UTC, closed without merging