Strict fee recipient
sigp/lighthouse pull request #3363
Opened 2022-07-22 18:43 UTC by realbigsean

## Issue Addressed

Resolves #3267
Resolves #3156 

## Proposed Changes

- Move the log for fee recipient checks from proposer cache insertion into block proposal so we are directly checking what we get from the EE
- Only log when there is a discrepancy with the local EE, not when using the builder API. In the `builder-api` branch there is an `info` log when there is a discrepancy, I think it is more likely there will be a difference in fee recipient with the builder api because proposer payments might be made via a transaction in the block. Not really sure what patterns will become commong.
- Upgrade the log from a `warn` to an `error` - not actually sure which we want, but I think this is worth an error because the local EE with default transaction ordering I think should pretty much always use the provided fee recipient
- add a `strict-fee-recipient` flag to the VC so we only sign blocks with matching fee recipients. Falls back from the builder API to the local API if there is a discrepancy .

2022-07-24 23:46 UTC, paulhauner requested changes
Nice, looks well thought out.

I have a simple copy-paste fix (I assume). It might also be easy and simple to add a test for the flag, like this one:

https://github.com/sigp/lighthouse/blob/21dec6f603edd53ad8d2372941c77ab8098d3b5a/lighthouse/tests/validator_client.rs#L378-L384

2022-07-24 23:46 UTC, paulhauner commented on validator_client/src/config.rs
> +        if cli_args.is_present("private-tx-proposals") {
```suggestion
        if cli_args.is_present("strict-fee-recipient") {
```

2022-07-25 20:30 UTC, realbigsean commented
Oof my bad, had I put in the test I would have caught it :/. Thanks!

2022-07-26 00:13 UTC, paulhauner approved these changes
LGTM!

2022-07-26 02:17 UTC, paulhauner commented
bors r+

2022-07-26 04:21 UTC, closed without merging