Remove fallback support from eth1 service
sigp/lighthouse pull request #3594
Opened 2022-09-20 17:55 UTC by pawanjay176

## Issue Addressed

N/A

## Proposed Changes

With https://github.com/sigp/lighthouse/pull/3214 we made it such that you can either have 1 auth endpoint or multiple non auth endpoints. Now that we are post merge on all networks (testnets and mainnet), we cannot progress a chain without a dedicated auth execution layer connection so there is no point in having a non-auth eth1-endpoint for syncing deposit cache. 

This code removes all fallback related code in the eth1 service. We still keep the single non-auth endpoint since it's useful for testing.

## Additional Info

This removes all eth1 fallback related metrics that were relevant for the monitoring service, so we might need to change the api upstream.

2022-09-27 05:10 UTC, michaelsproul requested changes
This is awesome!

Looks good on the whole, I've just requested a few minor changes to the logs.

I've also marked this PR as backwards incompat, as it will break `--eth1-endpoints` for users on Gnosis chain. Given the Gnosis merge should happen soon after we release this, I think it's OK to just note the breakage in the release notes.

2022-09-27 05:10 UTC, michaelsproul commented on beacon_node/src/lib.rs
> +                "endpoints" => format!("{:?}", &client_config.eth1.endpoint),
```suggestion
                "endpoint" => format!("{:?}", &client_config.eth1.endpoint),
```

2022-09-27 05:10 UTC, michaelsproul commented on beacon_node/eth1/src/service.rs
>              warn!(
there's an `"action"` key in this warn log that says `"trying fallbacks"`. we should delete it

2022-09-27 05:10 UTC, michaelsproul commented on beacon_node/eth1/src/service.rs
>  async fn endpoint_state(
There's another instance of `"trying fallbacks"` in this function. We should delete all of them.

2022-09-27 21:28 UTC, pawanjay176 commented
To account for removed fallback related metrics that were sent over the monitoring service endpoint, this PR sets default values for all monitoring metrics that aren't present as lighthouse metrics in 9a71f41

2022-09-30 04:34 UTC, michaelsproul approved these changes
LGTM!

2022-10-04 06:42 UTC, paulhauner commented
bors r+

2022-10-04 10:36 UTC, closed without merging