add execution-timeout-multiplier flag to optionally increase timeouts
sigp/lighthouse pull request #3631
Opened 2022-10-06 23:04 UTC by GeemoCandama

## Issue Addressed
Add flag to lengthen execution layer timeouts

Which issue # does this PR address?

#3607 

## Proposed Changes

Added execution-timeout-multiplier flag and a cli test to ensure the execution layer config has the multiplier set correctly.

Please list or describe the changes introduced by this PR.
Add execution_timeout_multiplier to the execution layer config as Option<u32> and pass the u32 to HttpJsonRpc.

## Additional Info
Not certain that this is the best way to implement it so I'd appreciate any feedback.

Please provide any additional information. For example, future considerations
or information useful for reviewers.

2022-10-07 00:22 UTC, michaelsproul commented
Do you mind rebasing on/merging `unstable`? Thanks! :pray:

2022-10-07 22:06 UTC, GeemoCandama commented
> Do you mind rebasing on/merging `unstable`? Thanks! pray

Sorry about that! I think I fixed it now

2022-10-17 00:36 UTC, michaelsproul requested changes
There's one timeout that the multiplier isn't applied to: `ENGINE_EXCHANGE_TRANSITION_CONFIGURATION_V1_TIMEOUT`. Happy to merge once the multiplier is applied there and my other suggestion is applied.

Thank you very much for implementing this feature!

2022-10-17 00:36 UTC, michaelsproul commented on beacon_node/src/cli.rs
> +                .value_name("EXECUTION-TIMEOUT-MULTIPLIER")
Usually we try to keep these placeholder names as short as possible

```suggestion
                .value_name("NUM")
```

2022-10-18 01:34 UTC, michaelsproul approved these changes
Awesome thanks!

2022-10-18 01:35 UTC, michaelsproul commented
bors r+

2022-10-18 04:01 UTC, michaelsproul commented
bors r-

2022-10-18 04:01 UTC, michaelsproul commented
bors r+

2022-10-18 06:27 UTC, closed without merging