Book spelling and grammar corrections
sigp/lighthouse pull request #3659
Opened 2022-10-26 06:34 UTC by iKausik

## Issue Addressed

There are few spelling and grammar errors in the book.

## Proposed Changes

Corrected those spelling and grammar errors in the below files
- book/src/advanced-release-candidates.md
- book/src/advanced_networking.md
- book/src/builders.md
- book/src/key-management.md
- book/src/merge-migration.md
- book/src/wallet-create.md

2022-10-26 06:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3659) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3659) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3659) it.</sub>

2022-10-26 06:38 UTC, michaelsproul requested changes
Thanks!

2022-10-26 06:38 UTC, michaelsproul commented on README.md
> +- Funded by various organizations, including Sigma Prime, the
```suggestion
- Funded by various organisations, including Sigma Prime, the
```

Most of us are based in Australia, so we're committed to a mix of UK and US English. We hope our US audience understand anyway ;)

2022-10-26 06:38 UTC, michaelsproul commented on book/src/advanced-release-candidates.md
> +you're looking for a stable Lighthouse**.
```suggestion
you're looking for stable Lighthouse**.
```

Stable here refers to the `stable` branch, perhaps we could say "the stable version of Lighthouse".

2022-10-26 06:52 UTC, iKausik reviewed
I reviewed the rest of the changes and found those are correct changes to make.

2022-10-26 07:08 UTC, michaelsproul commented
@iKausik Did you intend to push another commit? It looks like you just marked the feedback as resolved without changing anything

2022-10-26 07:15 UTC, michaelsproul approved these changes

2022-10-26 07:16 UTC, michaelsproul commented
Thanks! Will merge this after v3.2.1 has shipped

2022-10-28 01:12 UTC, AgeManning commented
bors r+

2022-10-28 05:29 UTC, closed without merging