compile with beta compiner on CI
sigp/lighthouse pull request #3717
Opened 2022-11-13 15:41 UTC by danielrachi

## Issue Addressed

#3709 

## Proposed Changes

Add the job `compile-with-beta-compiler` to `test-suite`. This job has the following steps:

1. Use `actions/checkout@v3`. (Needed to run make in a later step.)
2. Install the dependencies listed in [build from source guide](https://lighthouse-book.sigmaprime.io/installation-source.html).
3. Change the compiler to the current beta version with `rustup override`.
4. Run `make`.

2022-11-13 15:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3717) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3717) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3717) it.</sub>

2022-11-13 16:31 UTC, danielrachi commented
Force pushed because there was a typo on my original commit message. Only changed the commit message.

2022-11-15 04:14 UTC, michaelsproul requested changes
Awesome thank you!

Can you please add the `compile-with-beta-compiler` job to `./bors.toml` so that our PR merge pipeline verifies that the job passes? thanks

2022-11-15 04:51 UTC, michaelsproul requested changes

2022-11-15 04:51 UTC, michaelsproul commented on bors.toml
>      "disallowed-from-async-lint"
```suggestion
    "disallowed-from-async-lint",
```

2022-11-15 05:00 UTC, danielrachi commented on bors.toml
>      "disallowed-from-async-lint"
Whoops 😅

2022-11-15 05:18 UTC, michaelsproul approved these changes
Great, think we're ready to go!

2022-11-15 05:20 UTC, michaelsproul commented
bors r+

2022-11-15 07:22 UTC, closed without merging