Add CLI flag to opt in to world-readable log files
sigp/lighthouse pull request #3747
Opened 2022-11-23 01:31 UTC by macladson

## Issue Addressed

#3732

## Proposed Changes

Add a CLI flag to allow users to opt out of the restrictive permissions of the log files.

## Additional Info

This is not recommended for most users. The log files can contain sensitive information such as validator indices, public keys and API tokens (see #2438). However some users using a multi-user setup may find this helpful if they understand the risks involved.

2022-11-25 02:54 UTC, michaelsproul requested changes
Looks good, can we chuck two tests in to check the default value and the value with the flag? Our test infra recently gained support for log config in https://github.com/sigp/lighthouse/pull/3609

2022-11-25 05:06 UTC, michaelsproul approved these changes
ty

2022-11-25 05:13 UTC, michaelsproul commented
bors r+

2022-11-25 05:15 UTC, michaelsproul commented
re-batching to fix the merge conflict

bors r-

2022-11-25 05:20 UTC, michaelsproul commented
Sorry, everything conflicts with https://github.com/sigp/lighthouse/pull/3711, and seeing as that's biggger and older I'm gonna prioritise getting it in

2022-11-25 07:56 UTC, michaelsproul commented
bors r+

2022-11-25 09:58 UTC, closed without merging

2023-04-03 21:38 UTC, ostracoder commented
@michaelsproul I think the flag help text is a bit misleading. When using this flag on Windows, the log file permissions are inherited from the parent folder (as expected), which does not necessarily mean "world-readable". It depends on the permissions set on the parent folder, which can be totally secure.

2023-04-04 02:21 UTC, michaelsproul commented
Thanks @ostracoder, I opened a new issue to track this: https://github.com/sigp/lighthouse/issues/4162. Would you be interested in raising a PR?