Add support for Capella
sigp/lighthouse pull request #3763
Opened 2022-12-01 00:18 UTC by ethDreamer

2022-12-01 00:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3763) before we can accept your contribution.<br/>**5** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: ethDreamer<br/>:white_check_mark: pawanjay176<br/>:white_check_mark: michaelsproul<br/>:white_check_mark: jimmygchen<br/>:white_check_mark: realbigsean<br/>:x: daniel-tud<br/>:x: MariusVanDerWijden<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3763) it.</sub>

2023-02-15 22:57 UTC, paulhauner commented
I'm flagging this as ready for review! I think it's still OK to merge things in here, but I'm hoping we can get this merged early next week.

2023-02-16 04:36 UTC, paulhauner requested changes
I just finished reviewing the `execution_layer`. It looks great, I only have really minor suggestions.

I believe that all of the suggestions here will compile if they're accepted and committed via the Github UI. Anything that I couldn't get to work via suggestions I added here: https://github.com/sigp/lighthouse/pull/3983

2023-02-16 04:36 UTC, paulhauner commented on beacon_node/execution_layer/src/engine_api/http.rs
> +    }
```suggestion
    pub fn engine_capabilities(&self) -> EngineCapabilities {
        self.engine_capabilities
    }
```

Super minor nit, but it makes a future suggestion slightly cleaner. `EngineCapabilities` is tiny and `Copy`, currently a reference/pointer is likely larger than the actual struct.

2023-02-16 04:36 UTC, paulhauner commented on beacon_node/execution_layer/src/engine_api/http.rs
> +        }
```suggestion
        if let Some(lock) = lock.as_ref().filter(|entry| !entry.older_than(age_limit)) {
            Ok(lock.engine_capabilities())
        } else {
            let engine_capabilities = self.exchange_capabilities().await?;
            *lock = Some(CapabilitiesCacheEntry::new(engine_capabilities));
            Ok(engine_capabilities)
        }
```

Removes the `unwrap()` and is still easy to read, IMO.

2023-02-16 04:36 UTC, paulhauner commented on beacon_node/execution_layer/src/engine_api/http.rs
> +            // Have to guess zero here as we don't know the value
```suggestion
            // Set the V1 payload values from the EE to be zero. This simulates
            // the pre-block-value functionality of always choosing the builder
            // block.
```

Very minor nit, mostly represents that I took the time to go and double-check this.

2023-02-16 04:36 UTC, paulhauner commented on beacon_node/execution_layer/src/engines.rs
> +/// FIXME: check this assumption now that the key includes entire payload attributes which now includes withdrawals
```suggestion
/// Since the size of each value is small (~800 bytes) a large number is used for safety.
```

I think we can stick with a cache size of `512`. Here's my working:

- hash: `32`
- attributes:
  - timestamp: `8`
  - prev_randao: `32`
  - suggested_fee_recip: `20`
  - withdrawals: `44 * 16 = 704`
- payload_id: `8`

The size of each entry is `32+8+32+20+704+8 = 804` bytes.

The total cache would be `512 * 804 ~= 411KB` , which I think is very reasonable.

2023-02-16 04:36 UTC, paulhauner commented on beacon_node/execution_layer/src/engines.rs
> +                (**state, CapabilitiesCacheAction::None)
```suggestion
                (**state, CapabilitiesCacheAction::Clear)
```

I would expect to get an auth error in two cases:

1. We are connecting to the EE for the first time and a `Clear` can't hurt.
1. The EE has changed and it would be good to `Clear` and get fresh capabilities.

It's probably the case that in (2) we'd get an `Offline` first, but using `Clear` for auth errors still seems to make sense to me.

2023-02-17 07:59 UTC, paulhauner commented
I just finished reviewing `beacon_chain`, my suggestions are at #3999. It's looking good!

2023-02-21 07:07 UTC, paulhauner approved these changes
Approved! 🎉 🎉 

Congrats to all involved, this looks great! As you can see in the history, I made some suggestions via a bunch of PRs. However I don't think any of them were really significant, we probably could have gone to production as it was.

Seeing as we're planning to merge this into `unstable` via a merge commit (rather than squash merge via bors), I think it makes sense to wait and see that CI finishes before merging.

2023-02-21 22:01 UTC, divagant-martian commented on beacon_node/network/src/beacon_processor/mod.rs
> +                    &metrics::BEACON_PROCESSOR_RPC_BLOB_QUEUE_TOTAL,
this change should be reverted

2023-02-21 23:09 UTC, paulhauner commented on beacon_node/network/src/beacon_processor/mod.rs
> +                    &metrics::BEACON_PROCESSOR_RPC_BLOB_QUEUE_TOTAL,
Good catch, I fixed this in #4020

2023-02-21 23:27 UTC, merged

2023-02-21 23:28 UTC, michaelsproul commented
Leaving the `capella` branch around for people using old instructions to build from source. We can delete it in a few days.