[Merged by Bors] - add better err reporting UnableToOpenVotingKeystore
sigp/lighthouse pull request #3781
Opened 2022-12-07 15:55 UTC by infosecual

## Issue Addressed

#3780 

## Proposed Changes

Add error reporting that notifies the node operator that the `voting_keystore_path` in their `validator_definitions.yml` file may be incorrect.

## Additional Info

There is more info in issue #3780

2022-12-07 16:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3781) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3781) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3781) it.</sub>

2022-12-13 06:00 UTC, paulhauner commented
I'd be happy to merge once the suggestion is implemented and the conflict resolved. Thanks for the contribution 🙏

2022-12-14 01:19 UTC, paulhauner requested changes
Sorry, I just realised I hadn't submitted this review so there was an invisible suggestion! Thanks @michaelsproul for picking this up 🙏

2022-12-14 01:19 UTC, paulhauner commented on validator_client/src/lib.rs
> +                    format!("Unable to initialize validators: {:?}, If you have recently moved the location of your data directory \
```suggestion
                    format!("Unable to initialize validators: {:?}. If you have recently moved the location of your data directory \
```

We've been trying to remove `,` from the logs since it's challenging for indexing log systems (e.g., ELK) that parse our `key1: value1, key2: value:2` format.

2023-01-10 20:20 UTC, fafrd commented
@infosecual Can you address the comment and get this merged in? I was tripped up by this exact issue recently.

2023-01-17 04:25 UTC, paulhauner commented
I've made the changes myself, we'll see how CI goes 🤞

2023-01-17 04:36 UTC, infosecual commented
Apologies- this got buried in a sea of github notification. Glad it was a small change and not too much trouble! Thanks for taking care of this.

2023-01-17 05:09 UTC, paulhauner approved these changes
Thanks David 🙏

2023-01-17 05:13 UTC, paulhauner commented
bors r+

2023-01-17 07:37 UTC, closed without merging