Return HTTP 404 rather than 405
sigp/lighthouse pull request #3836
Opened 2022-12-26 00:56 UTC by santiagomed

## Issue Addressed

Issue 3112

## Proposed Changes

Add `Filter::recover` to the GET chain to handle rejections specifically as 404 NOT FOUND

## Additional Info

Making a request to `http://localhost:5052/not_real` now returns the following:

```
{
    "code": 404,
    "message": "NOT_FOUND",
    "stacktraces": []
}
```

2022-12-26 00:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3836) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3836) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3836) it.</sub>

2023-01-09 04:22 UTC, paulhauner requested changes
Great, thanks for this contribution @santiagomed! It really irks me how our HTTP server gives weird error codes 😥

Your fix is simple and works well. I was wondering if you could do the same for POST requests too, please? I tried this locally and it should be as simple as adding the same line here: https://github.com/sigp/lighthouse/blob/260f78aebc46feae4bdf6414e42369b83a7805db/beacon_node/http_api/src/lib.rs#L3380

2023-01-09 04:25 UTC, paulhauner commented
I've marked this PR as `backwards-incompat` because I think it deserves a mention in our release notes.

2023-01-10 02:46 UTC, santiagomed commented
@paulhauner made the addition! Let me know if anything else is needed.

2023-01-10 23:09 UTC, paulhauner requested changes
Thanks! It looks like there's been a conflict sorry, I imagine it'll be simple to resolve.

I've also made a suggest to what I *think* will be a compile error.

2023-01-10 23:09 UTC, paulhauner commented on beacon_node/http_api/src/lib.rs
>                  .or(post_lighthouse_block_rewards.boxed()),
```suggestion
                .or(post_lighthouse_block_rewards.boxed())
```

2023-01-10 23:12 UTC, paulhauner commented
I just tried my hand at resolving the conflict and compile error with the Github UI, let's see how that goes!

2023-01-10 23:12 UTC, paulhauner commented on beacon_node/http_api/src/lib.rs
>                  .or(post_lighthouse_block_rewards.boxed()),
Please ignore this, I fixed this when resolving the conflict.

2023-01-11 02:56 UTC, paulhauner approved these changes
It passed CI 🎉 Thanks again @santiagomed. This is good to merge once v3.4.0 is released and proven stable. Until then, it's `blocked`.

2023-01-11 03:02 UTC, paulhauner commented
### Breaking changes note

Previously, the Beacon Node HTTP would return `405` (method not allowed) for an unknown route (e.g. `http://localhost:5052/not_a_real_route`). Lighthouse will now return a `404` (not found) error.

2023-01-16 03:41 UTC, michaelsproul commented
bors r+

2023-01-16 06:23 UTC, closed without merging