Add content-type header to metrics server response
sigp/lighthouse pull request #3970
Opened 2023-02-13 17:36 UTC by kayibal

This fixes issues with certain metrics scrapers, which might error if the content-type is not correctly set.

## Issue Addressed

Fixes https://github.com/sigp/lighthouse/issues/3437

## Proposed Changes

Simply set header: `Content-Type: text/plain` on metrics server response. Seems like the errored branch does this correctly already.

## Additional Info

This is needed also to enable influx-db metric scraping which work very nicely with Geth.

2023-02-13 17:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=3970) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=3970) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3970) it.</sub>

2023-02-14 01:18 UTC, michaelsproul requested changes
Awesome, thanks!

Do you mind applying the same fix to the validator client metrics here?

https://github.com/sigp/lighthouse/blob/38514c07f222ff7783834c48cf5c0a6ee7f346d0/validator_client/src/http_metrics/mod.rs#L124

Thank you! :pray:

2023-02-14 10:24 UTC, kayibal commented
Sure thing I added it, couldn't find any other place for metrics apart than those two. Also didn't find any tests for the latter.

2023-02-28 01:56 UTC, michaelsproul approved these changes
Looks good, thanks!

2023-02-28 02:05 UTC, michaelsproul commented
bors r+

2023-02-28 02:19 UTC, michaelsproul commented
bors r-
bors r+

2023-02-28 02:19 UTC, michaelsproul commented
bors r-
bors r+

2023-02-28 04:32 UTC, closed without merging