Incomplete tests
sigp/lighthouse pull request #4052
Opened 2023-03-06 06:56 UTC by danielrachi

## Issue Addressed

#4040 

## Proposed Changes

- Add the `always_prefer_builder_payload` and `builder_profit_margin` fields to `Config` in `beacon_node/client/src/config.rs`.
- Add those same fields to `Inner` in `beacon_node/execution_layer/src/lib.rs`
- Modify the logic for picking the payload in beacon_node/execution_layer/src/lib.rs`
- Add the `buildier-profit-margin` and `always-prefer-builder-payload` flags to the CLI
- Test the new flags in `lighthouse/tests/beacon_node.rs`

## Additional Info

Besides my tests not being complete, I'm getting a compilation error I don't recognize. I'll look into it later today, but if someone could point where the error could be I'd appreciate it.

2023-03-06 07:20 UTC, michaelsproul commented
Ah that overflow error isn't the fault of your code. Are you running an older compiler version? If you update it should go away

2023-03-06 11:09 UTC, divagant-martian commented
@paulhauner has some thoughts on how we should do this changes, but to tackle the compiler error please apply this patch:
```diff
diff --git a/beacon_node/tests/test.rs b/beacon_node/tests/test.rs
index 1c11a8349..8ccb260d2 100644
--- a/beacon_node/tests/test.rs
+++ b/beacon_node/tests/test.rs
@@ -1,5 +1,5 @@
 #![cfg(test)]
-#![recursion_limit = "256"]
+#![recursion_limit = "512"]
 
 use beacon_chain::StateSkipConfig;
 use node_test_rig::{

```

2023-03-06 11:12 UTC, paulhauner requested changes
Thanks for the contribution @danielrachi 🙏

I appreciate the ambition with the `buildier-profit-margin` flag, however I'd like to request that we just do the `always_prefer_builder_payload` flag in this PR. We've already started testing this release so anything we add now should be as minimal as possible, both from a complexity/risk perspective and a time-to-implement-and-review perspective. We haven't had any user requests for the profit margin, so I think it's reasonable for us to omit it from this release.

As pointed out by @michaelsproul, it may be more user friendly to express the profit margins as a percentage rather than a wei value (e.g., "use the builder payload only if it's 50% more profitable). We can think about this after we get the release out, if you're keen to implement it then we'd love to have you involved. No pressure, of course.

So, in summary, it would be awesome if you could please adjust the `recursion_limit` (as per @divagant-martian's [diff/comment](https://github.com/sigp/lighthouse/pull/4052#issuecomment-1455932522)) and reduce the scope of this PR so that we can land this release nice and easily ☺️

2023-03-06 11:12 UTC, paulhauner commented on lighthouse/src/main.rs
> +            .takes_value(true)
```suggestion
```

The flag doesn't take a value (i.e. it's just `--flag` rather than `--flag value`) so we don't need these.

2023-03-06 11:12 UTC, paulhauner commented on lighthouse/tests/beacon_node.rs
> +#[test]
Could we please add another test that doesn't have any flag provided and asserts `!config.always_prefer_builder_payload` 🙏

2023-03-06 23:08 UTC, paulhauner approved these changes
Great, thanks @danielrachi!

In the interests of a quick resolution, I pushed a [commit](https://github.com/sigp/lighthouse/pull/4052/commits/ef5565b1c1cae63008c36ba7770f4f705892e06d) to:

- Move the CLI args to be underneath the `lighthouse bn` command, rather than at the root `lighthouse` level.
- Make the flag conflict with `--builder-profit-threshold`, since that flag could cause us to actually prefer a local payload.

2023-03-06 23:16 UTC, michaelsproul approved these changes
Nice! Let's merge, thanks @danielrachi

2023-03-07 00:45 UTC, paulhauner commented
bors r+

2023-03-07 07:50 UTC, closed without merging