Fix order of arguments to log_count
sigp/lighthouse pull request #4060
Opened 2023-03-07 22:38 UTC by centromere

See: https://github.com/sigp/lighthouse/pull/4027

## Proposed Changes

The order of the arguments to `log_count` is swapped in `beacon_node/beacon_chain/src/events.rs`.

2023-03-07 23:12 UTC, michaelsproul requested changes
Thanks!

Due to a quirk of Github actions, the branch check won't re-run until you push a different commit. Do you mind pushing an empty commit, or amending the existing commit (you can just change the message) so that we can re-trigger CI after changing the target branch from `stable` to `unstable`?

Thanks again!

2023-03-07 23:29 UTC, centromere commented
Done.

2023-03-07 23:38 UTC, michaelsproul approved these changes
Great, thanks!

2023-03-08 17:18 UTC, centromere commented
Should this be applied to 3.5.1, or is it too late?

2023-03-08 21:09 UTC, michaelsproul commented
@centromere it's too late, but the bug is very low severity so that's OK.

We'll merge it for v4.0.0 (Capella on mainnet).

2023-03-10 05:28 UTC, michaelsproul commented
bors r+

2023-03-10 05:57 UTC, michaelsproul commented
batching with a clippy fix

bors +

2023-03-10 05:57 UTC, michaelsproul commented
bors r+

2023-03-12 23:42 UTC, michaelsproul commented
bors r+

2023-03-13 03:53 UTC, closed without merging