Update get blobs endpoint to return a list of BlobSidecars
sigp/lighthouse pull request #4109
Opened 2023-03-20 01:12 UTC by jimmygchen

## Issue Addressed

Addresses #4106

## Proposed Changes

- updated path to `GET /eth/v1/beacon/blobs/{block_id}`
- updated response to list of `BlobSidecar`s

## Additional Info

I've stubbed the `beacon_chain.get_blobs` method for now,  which is currently being worked on in #4104

2023-03-20 20:50 UTC, divagant-martian commented
hi @jimmygchen can you update the endpoint to return a `Vec<Arc<BlobSidecar>>` instead according to internal discussions? I think it's good enough like this for now, no need to deal with the `BlobSidecarList` alias for this

2023-03-20 20:55 UTC, jimmygchen commented
> hi @jimmygchen can you update the endpoint to return a `Vec<Arc<BlobSidecar>>` instead according to internal discussions? I think it's good enough like this for now, no need to deal with the `BlobSidecarList` alias for this

Updated, thanks!

2023-03-20 23:12 UTC, divagant-martian commented on beacon_node/http_api/src/lib.rs
> +                .uor(get_blobs)
sorry to be pedantic but why in this order? it's a bit of breaking the list of `beacon_block_` ones. Can we move it a bit down?

2023-03-20 23:14 UTC, divagant-martian commented on beacon_node/http_api/src/lib.rs
> +                .uor(get_blobs)
yeah ok maybe it makes sense. Ignore my pedantic comment if you want

2023-03-21 10:42 UTC, pawanjay176 approved these changes

2023-03-21 13:15 UTC, pawanjay176 requested changes
Sorry missed this earlier

2023-03-21 13:15 UTC, pawanjay176 commented on beacon_node/http_api/src/block_id.rs
> +use types::{BlobSidecarList, Hash256, SignedBeaconBlock, SignedBlindedBeaconBlock, Slot};
Actually we want `BlobSidecarList` to have each individual BlobSidecar arc'd right?

2023-03-21 13:24 UTC, pawanjay176 commented on beacon_node/http_api/src/block_id.rs
> +use types::{BlobSidecarList, Hash256, SignedBeaconBlock, SignedBlindedBeaconBlock, Slot};
or what Diva said above

2023-03-21 13:49 UTC, jimmygchen commented on beacon_node/http_api/src/block_id.rs
> +use types::{BlobSidecarList, Hash256, SignedBeaconBlock, SignedBlindedBeaconBlock, Slot};
ah sorry I misread the message quite terribly! 😅 Thanks for pointing this out! 
I assumed the type alias would be done i in Mark / Sean / your PR and this would just work. I've replaced the `BlodSidecarList` type alias now, but had to add a clippy exception to make lint happy.

2023-03-21 14:55 UTC, divagant-martian approved these changes
lgtm

2023-03-21 14:56 UTC, merged