add attestation inclusion distance in http api
sigp/lighthouse pull request #4148
Opened 2023-03-31 02:34 UTC by int88

## Issue Addressed

#4097

## Proposed Changes

Add attestation inclusion distance in http api, extend `/lighthouse/ui/validator_metrics` to include it.

## Usage
```
curl -X POST "http://localhost:8001/lighthouse/ui/validator_metrics" -d '{"indices": [1]}' -H "Content-Type: application/json" | jq
```

```
{
  "data": {
    "validators": {
      "1": {
        "attestation_hits": 3,
        "attestation_misses": 1,
        "attestation_hit_percentage": 75,
        "attestation_head_hits": 3,
        "attestation_head_misses": 0,
        "attestation_head_hit_percentage": 100,
        "attestation_target_hits": 3,
        "attestation_target_misses": 0,
        "attestation_target_hit_percentage": 100,
        "attestation_inclusion_distance": 1
      }
    }
  }
}
```

## Additional Info

NA

2023-03-31 02:36 UTC, int88 commented
@michaelsproul @AgeManning PTAL :)

2023-04-03 00:37 UTC, AgeManning approved these changes
This looks good to me. 

Dropping the write-lock early is nice too. Will wait for @michaelsproul to triple check before merging.

2023-04-03 00:43 UTC, paulhauner requested changes
I notice that the `attestation_inclusion_distance` shows the inclusion distance of the *latest* attestation, whilst the other metrics track the *sum* of all previous attestations.

To avoid confusion, perhaps we should label it `latest_attestation_inclusion_distance`?

2023-04-03 03:07 UTC, int88 commented
@paulhauner updated, PTAL :)

2023-04-06 01:09 UTC, int88 commented
ping @paulhauner

2023-04-06 02:43 UTC, michaelsproul commented
Paul's on leave, he'll be back Tuesday after the easter public holidays 

We'll get your PR in for v4.1.0

2023-04-12 08:20 UTC, paulhauner approved these changes
Looks good, approved! Thank you 🙏

2023-04-12 08:54 UTC, int88 commented
@paulhauner  vscode not automatically `cargo fmt` for me, please help retrigger the CI :)

2023-04-20 06:57 UTC, int88 commented
@paulhauner maybe this PR could get merged? :)

2023-04-20 07:47 UTC, paulhauner commented
> @paulhauner maybe this PR could get merged? :)

We like to take a few days after a release before merging something, just to keep `unstable` clean in case we need to push a release.

I'll come back to this next week. You have the v4.2.0 flag now, so you're going to end up in that release.

2023-04-20 07:50 UTC, int88 commented
Ok, just a friendly reminder, as I see v4.1.0 was just released :) @paulhauner

2023-04-26 01:11 UTC, paulhauner commented
bors r+

2023-04-26 01:12 UTC, paulhauner commented
bors r-

(batching)

2023-04-26 01:12 UTC, paulhauner commented
bors r+

2023-04-26 03:30 UTC, closed without merging