Update Lighthouse Book API and Advanced Usage section
sigp/lighthouse pull request #4300
Opened 2023-05-17 01:47 UTC by chong-he

## Issue Addressed

Update Information in Lighthouse Book

## Proposed Changes

- move Validator Graffiti from Advanced Usage to Validator Management
- update API response and command
- some items that aren't too sure I put it in comment, which can be seen in raw/review format but not live

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

2023-05-29 01:50 UTC, paulhauner requested changes
Wow, this is a big effort! It makes lots of overdue fixes and I think it's a great improvement! 🚀 

I've made a bunch of small suggestions. FYI, if you use the "Conversation" tab then you can only implement suggestions one-by-one, but if you use the "Files changed" tab you can batch them (this is faster, IMO).

I would also like to request changing all instances of `sudo cat` to just `cat`. I can see how the `sudo` is useful, however we tend to leave `sudo` out of examples since it can be dangerous. I don't think your use is dangerous, but I'd prefer to avoid it if possible. Perhaps adding a note that `sudo` maybe required is nice?

2023-05-29 01:50 UTC, paulhauner commented on book/src/advanced-datadir.md
> -lighthouse --network mainnet --datadir /var/lib/my-custom-dir bn --staking
I would have thought the `--staking` flag would be useful and not harmful in this scenario?

2023-05-29 01:50 UTC, paulhauner commented on book/src/advanced-release-candidates.md
> +Other than the above scenarios, it is generally not recommended to use release candidates for any critical tasks on mainnet (e.g., staking). To test critical features, try one of the testnets (e.g.,
```suggestion
Other than the above scenarios, it is generally not recommended to use release candidates for any critical tasks on mainnet (e.g., staking). To test new release candidate features, try one of the testnets (e.g., Goerli).
```

I know that "critical" was already here and you didn't add it, but I think it makes more sense like this.

2023-05-29 01:50 UTC, paulhauner commented on book/src/advanced_database.md
> +| Research                   | 32   | 3.4 TB            | 155 ms                |
Looping in @michaelsproul to get his 👍 on this math. I recall some conversation about it, but not the outcome.

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-bn.md
> +where `jq` is used to format the JSON data properly. If it returns `jq: command not found`, then you can install `jq` with `sudo apt install -y jq`. After that, run the command again, and it should r
```suggestion
The `jq` tool is used to format the JSON data properly. If it returns `jq: command not found`, then you can install `jq` with `sudo apt install -y jq`. After that, run the command again, and it should return the head state of the beacon chain.
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +        "attestation_target_hit_percentage": 50
```suggestion
        "attestation_target_hit_percentage": 50,
        "latest_attestation_inclusion_distance": 1
```

This field was added in #4148.

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +There are two possible outcome, depending on whether the beacon node is syncing or synced.
```suggestion
There are two possible outcomes, depending on whether the beacon node is syncing or synced.
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +[comment]: <> (Reorganize the output, tested the API on my own node shows that the output is reordered)
```suggestion
```

Nice, looks good.

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +[comment]: <> (Tested that it needs the flag `--validator-monitor-auto` to return the output, hence added the content)
```suggestion
```

Nice 👍

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +[comment]: <> (Changed the output as per tested on my own node. Most info are the same but there are some differences such as the output I obtained contains subnet, is_trusted, connection_direction a
```suggestion
```

Looks good 👍

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +[comment]: <> (modified similarly as above in /lighthouse/peers)
```suggestion
```

👍

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +
```suggestion
`voting_target_timestamp`. 

```

Nice find! The variable name was wrong, we wanted `voting_target_timestamp` instead.

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +[comment]: <> (Added prune_payloads which seems to have been added in the response of this API query, so updated the response of other fields too)
```suggestion
```

👍

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-lighthouse.md
> +[comment]: <> (The response seems to have more information now, I query only 1 slot and updated accordingly the command and response, but that's a bit weird because I didn't include all response unti
```suggestion
```

👍

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-vc-endpoints.md
> +> Note: The command provided in this documentation links to the API token file. In this documentation, it is assumed that the API token file is located in `/var/lib/lighthouse/validators/API-token.tx
```suggestion
> Note: The command provided in this documentation links to the API token file. In this documentation, it is assumed that the API token file is located in `/var/lib/lighthouse/validators/API-token.txt`. If your database is saved in another directory, modify the `DATADIR` accordingly.
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-vc-endpoints.md
> +> As an alternative, you can also provide the API token directly, for example, `-H "Authorization: Bearer api-token-0x02dc2a13115cc8c83baf170f597f22b1eb2930542941ab902df3daadebcb8f8176`. In this case
```suggestion
> As an alternative, you can also provide the API token directly, for example, `-H "Authorization: Bearer api-token-0x02dc2a13115cc8c83baf170f597f22b1eb2930542941ab902df3daadebcb8f8176`. In this case, you obtain the token from the file `API token.txt` and the command becomes:
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-vc-endpoints.md
> + curl -X GET "http://localhost:5062/lighthouse/ui/health" -H "Authorization: Bearer $(sudo cat ${DATADIR}/validators/api-token.txt)" | jq
```suggestion
curl -X GET "http://localhost:5062/lighthouse/ui/health" -H "Authorization: Bearer $(sudo cat ${DATADIR}/validators/api-token.txt)" | jq
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/api-vc-endpoints.md
> +```bash
```suggestion
```bash
DATADIR=/var/lib/lighthouse
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/redundancy.md
> +> Important Note: `lighthouse vc` would failover to the redundant beacon node after the primary beacon node has been out of synced for 8 epochs (51.2 minutes). This is a known [issue](https://github.
```suggestion
```

We've released v4.2.0 with this fix since you wrote this, so perhaps we can remove this now?

2023-05-29 01:50 UTC, paulhauner commented on book/src/slasher.md
> +[comment]: <> (change to 512GB as below stated 300K validators, but mainnet is now 600K. Please correct me if this is wrong)
```suggestion
```

I ran this past @michaelsproul and he's indicated that 256GB is still adequate. In fact 175GB would work for 600k validators. Perhaps we just leave it as-is for now.

2023-05-29 01:50 UTC, paulhauner commented on book/src/slasher.md
> +* 512 GB solid state storage (in addition to the space requirement for the beacon node DB)
```suggestion
* 256 GB solid state storage (in addition to the space requirement for the beacon node DB)
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/slasher.md
> +[comment]: <> (I have changed the default to 512GB to tally with the above, and also change the 300K validators to 600K validators. Please correct me if this is wrong.)
```suggestion
* Default: 256 GB
```

As above.

2023-05-29 01:50 UTC, paulhauner commented on book/src/slasher.md
> +[comment]: <> (lmdb is an option, but lighthouse bn --help shows possible values are mdbx and disabled only, no lmdb. I found that this can be updated in beacon_node/src/cli.rs https://github.com/sig
```suggestion
```

You only get one of these options, depending on which [feature-flags](https://lighthouse-book.sigmaprime.io/installation-source.html?highlight=mdbx#feature-flags) you compile with (`slasher-mdbx` or `slasher-lmdb`).

2023-05-29 01:50 UTC, paulhauner commented on book/src/slasher.md
> +By default the limit is set to accommodate the default history length and around 600K validators but
```suggestion
By default the limit is set to accommodate the default history length and around 600K validators (with about 30% headroom) but
```

2023-05-29 01:50 UTC, paulhauner commented on book/src/slasher.md
> +[comment]: <> (Not sure if this subsection should be updated? Like not sure about the "quite new" description.)
```suggestion
```

Oh yeah, good point. I think we can leave it as-is for now. We could maybe change "is still quite new" to "has not yet ossified". However I don't feel strongly about that and could happily leave it as-is.

2023-05-30 22:51 UTC, chong-he commented on book/src/advanced-datadir.md
> -lighthouse --network mainnet --datadir /var/lib/my-custom-dir bn --staking
Can't remember why I removed that.. I will upadte to keep this, thanks

2023-05-30 22:54 UTC, chong-he commented on book/src/api-lighthouse.md
> +        "attestation_target_hit_percentage": 50
thanks!

2023-05-30 23:34 UTC, michaelsproul commented on book/src/advanced_database.md
> +| Research                   | 32   | 3.4 TB            | 155 ms                |
Yeah this is right, after consulting with the beaconcha.in guys

2023-05-31 00:36 UTC, chong-he commented
> Wow, this is a big effort! It makes lots of overdue fixes and I think it's a great improvement! 🚀
> 
> I've made a bunch of small suggestions. FYI, if you use the "Conversation" tab then you can only implement suggestions one-by-one, but if you use the "Files changed" tab you can batch them (this is faster, IMO).
> 
> I would also like to request changing all instances of `sudo cat` to just `cat`. I can see how the `sudo` is useful, however we tend to leave `sudo` out of examples since it can be dangerous. I don't think your use is dangerous, but I'd prefer to avoid it if possible. Perhaps adding a note that `sudo` maybe required is nice?

Thanks so much for the review. I have committed all suggestions, removed comments and sudo.

2023-05-31 00:38 UTC, chong-he commented on book/src/advanced_database.md
> +| Research                   | 32   | 3.4 TB            | 155 ms                |
Thanks for the input

2023-06-01 05:48 UTC, paulhauner approved these changes
Looks great, thank you!

2023-06-01 06:38 UTC, paulhauner commented
bors r+

2023-06-01 23:43 UTC, paulhauner commented
bors r+

2023-06-02 00:19 UTC, paulhauner commented
bors r-

2023-06-02 00:19 UTC, paulhauner commented
bors r+

2023-06-02 02:16 UTC, paulhauner commented
bors r+

2023-06-02 03:17 UTC, michaelsproul commented
bors r-
bors r+

2023-06-02 06:00 UTC, closed without merging