add builder registration overrides
sigp/lighthouse pull request #4306
Opened 2023-05-18 14:30 UTC by xenowits

## Issue Addressed

https://github.com/sigp/lighthouse/issues/3444

Add validator registration overrides to support Distributed Validator use-case.

Most of the changes included in this PR are taken from this [outdated PR](https://github.com/sigp/lighthouse/pull/3445).

## Proposed Changes

Adds builder registration overrides: `builder_pubkey_override` and `builder_timestamp_override` to `ValidatorDefinition`.

## Additional Info

Please provide any additional information. For example, future considerations or information useful for reviewers.

2023-05-18 14:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=4306) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=4306) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: michaelsproul<br/>:white_check_mark: jimmygchen<br/>:white_check_mark: paulhauner<br/>:x: xenowits<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=4306) it.</sub>

2023-05-22 07:24 UTC, paulhauner commented
Heyo, we have a failure on the formatting. @xenowits ,could you please run `cargo fmt` in the root of the repo and commit the result?

2023-05-22 07:41 UTC, xenowits commented
> Heyo, we have a failure on the formatting. @xenowits ,could you please run `cargo fmt` in the root of the repo and commit the result?

@paulhauner Done 👍

2023-05-26 04:53 UTC, paulhauner commented
Thanks @xenowits. It looks liek we have some linting/compile issues. I suggest running `make lint` for the lint issues. For the compile issues, I find `make udeps` is an easy way to check that tests are compiling.

2023-05-26 11:19 UTC, xenowits commented
@paulhauner Thanks for the advice! I found a lot of issues to fix, have pushed the fixes. Let's see if we get any build failures

2023-06-05 15:10 UTC, xenowits commented
@paulhauner bump ^^ 🙏

2023-06-16 04:14 UTC, paulhauner requested changes
Heyo, I've been on leave so apologies for the delay. Thanks for the ping.

I've done a first pass and it's looking really good. Simple, neat and tidy! I've made a few suggestions. Once they're addressed I'll come back through for a final review. I've tagged it with `v4.3.0` so we include this in the next release (if all goes well).

2023-06-16 04:14 UTC, paulhauner commented on lighthouse/tests/validator_client.rs
> +fn builder_registration_pubkey_override_flag() {
This test looks good!

Would you mind also adding a test to check that `config.builder_registration_pubkey_override` is `None` when the ```builder-registration-pubkey-override` is *not* provided, please? We find these types of tests are nice because it prevents us from accidentally breaking default behavior in the future.

2023-06-16 04:14 UTC, paulhauner commented on validator_client/src/cli.rs
> +                    pubkey used in builder api registration")
```suggestion
                    pubkey used in builder api registration. This is useful for DVT setups.")
```

Just a suggestion to remind users (and developers) what this is for :)

2023-06-16 04:14 UTC, paulhauner commented on validator_client/src/cli.rs
> +                .value_name("BUILDER_REGISTRATION_TIMESTAMP_OVERRIDE")
```suggestion
                .value_name("UNIX_TIMESTAMP")
```

As above.

2023-06-16 04:14 UTC, paulhauner commented on validator_client/src/cli.rs
> +                .value_name("BUILDER_REGISTRATION_PUBKEY_OVERRIDE")
```suggestion
                .value_name("PUBLIC_KEY")
```

We generally use the `value_name` as a sort of type hint. E.g., `INTEGER`.

2023-06-16 04:14 UTC, paulhauner commented on validator_client/src/config.rs
> +        }
```suggestion
        config.builder_registration_pubkey_override =
            parse_optional(cli_args, "builder-registration-pubkey-override")?;
```

We have a handy little helper function for this. We don't *consistently* use it for legacy reasons, but I think it's worth using for new code.

2023-06-28 23:55 UTC, paulhauner commented
We're planning on releasing v4.3.0 next week and I think we've run out of time for this one. I'm going to push it back to v4.3.1 which we should expect in July sometime.

2023-08-02 08:56 UTC, paulhauner commented
Just checking if there's still interest in this one? I have some review cycles I could put towards it.

2023-08-17 23:37 UTC, paulhauner commented
I've dropped the `v4.3.1` flag since it doesn't seem like we're likely to land this in the next week or so.

2024-04-01 20:55 UTC, paulhauner commented
I'm closing this due to inactivity, please feel free to re-open.

2024-04-01 20:55 UTC, closed without merging