Implement liveness BeaconAPI
sigp/lighthouse pull request #4343
Opened 2023-05-28 00:48 UTC by aoikurokawa

## Issue Addressed

#4243

## Proposed Changes

- create a new endpoint for liveness/{endpoint}

## Additional Info
This is my first PR.

2023-05-28 01:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=4343) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=4343) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=4343) it.</sub>

2023-05-30 07:25 UTC, michaelsproul requested changes
Thank you for the contribution!

The code is very well-written overall, I just had a few suggestions about how to achieve conformance with the spec.

Thanks!

2023-05-30 07:25 UTC, michaelsproul commented on beacon_node/http_api/src/lib.rs
> +    // POST lighthouse/liveness/{epoch}
The path should be `/eth/v1/validator/liveness/{epoch}`, matching the spec: https://ethereum.github.io/beacon-APIs/#/Validator/getLiveness

2023-05-30 07:25 UTC, michaelsproul commented on beacon_node/http_api/src/lib.rs
> +                    if epoch > next_epoch {
The prev_epoch check is missing

2023-05-30 07:25 UTC, michaelsproul commented on beacon_node/http_api/src/lib.rs
> +                                epoch,
We need a new type here, like `StandardLivenessResponseData` which does not include the `epoch`. The `epoch` is not part of the standardised endpoint.

2023-05-30 07:25 UTC, michaelsproul commented on beacon_node/http_api/src/lib.rs
> +                    .uor(post_lighthouse_liveness_epoch)
this should be renamed `post_validator_liveness` and moved up with the other `post_validator_*` methods

2023-05-30 07:25 UTC, michaelsproul commented on common/eth2/src/lib.rs
> +    pub async fn post_lighthouse_liveness_epoch(
```suggestion
    pub async fn post_validator_liveness_epoch(
```

Similarly this should be renamed and refactored to use the `/eth/v1/validator/liveness` path

2023-05-30 23:13 UTC, aoikurokawa commented
Thank you for reviewing!. 

I think I have fixed all what you reviewed for my code.

2023-06-01 06:24 UTC, paulhauner commented
@aoikurokawa the `cargo-fmt` check is failing. You can fix this my running `cargo fmt` in the project root and committing the result ☺️

2023-06-01 23:43 UTC, aoikurokawa commented
Oops, sorry. 
I run the command `cargo fmt`, then committed, 
I appreciate your review.

2023-07-19 01:42 UTC, jimmygchen approved these changes
Looks good to me 👍 

There's just one `clippy` failure that I think should be fixed by merging latest `unstable` branch into this branch, and we should be good to merge!

2023-07-19 21:54 UTC, aoikurokawa commented
Thank you for reviewing 🙏
I think I have merged the current unstable branch.

2023-07-20 04:35 UTC, paulhauner approved these changes
Very neat and tidy!

2023-07-31 01:52 UTC, paulhauner commented
bors r+

2023-07-31 02:38 UTC, closed without merging