Remove `Banned` connection state from peer database
sigp/lighthouse pull request #4493
Opened 2023-07-12 01:55 UTC by jmcph4

## Issue Addressed

#2772

## Proposed Changes

 - Add `banned_since` field to `PeerInfo` type, capturing the time at which a peer was banned
 - Add accessors for this field
   - `banned_since`
   - `banned_since_mut`
 - Remove references to the old `PeerConnectionStatus::Banned` state
 - Correct the definition of whether a peer is banned or not to rely solely on the `ScoreState::Banned` variant

## Additional Info

N/A

2023-07-17 02:06 UTC, divagant-martian requested changes
while this obviously compiles and indeed removes the `PeerConnectionState::Banned`, it's not fully untangling score and connection state, since `NewConnectionState::Banned` and `NewConnectionState::Unbanned` still exist. 

Tests are failing because of this in part. `NewConnectionState::Banned` is adding banned peers and their ips, and later checks are removing them

2023-07-17 02:17 UTC, divagant-martian commented on beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
> +    banned_since: Option<Instant>,
I'm not sure this is the best way to keep track of this. Banned peers exist outside the `PeerInfo`, this keeps the posibility of inconsistency between that tracking and the inner one

2023-07-17 03:58 UTC, jmcph4 commented
> while this obviously compiles and indeed removes the `PeerConnectionState::Banned`, it's not fully untangling score and connection state, since `NewConnectionState::Banned` and `NewConnectionState::Unbanned` still exist.
> 
> Tests are failing because of this in part. `NewConnectionState::Banned` is adding banned peers and their ips, and later checks are removing them

I was thinking about this over the weekend and I don't get why `NewConnectionState` is strictly necessary? If you model the current connection for any given peer as a finite state machine, it doesn't really make sense to make a distinction between current state and new state -- they should be the same. When you compare the two different types it seems to reinforce this belief too:

https://github.com/sigp/lighthouse/blob/0d6530a0163eca1a0f39e3bab4465c690e41dc7d/beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs#L483-L511

https://github.com/sigp/lighthouse/blob/0d6530a0163eca1a0f39e3bab4465c690e41dc7d/beacon_node/lighthouse_network/src/peer_manager/peerdb.rs#L1110-L1139

Eager for your insight -- perhaps I'm oversimplifying it!

2023-07-18 01:00 UTC, divagant-martian commented
So this was added by age back in https://github.com/sigp/lighthouse/pull/2660.

It took me a bit to understand why it made sense again. The main difference is that the `ConnectionState` is pub while the `NewConnectionState` is private. This was made to isolate the connection state from outside modification since its container (the `PeerInfo`) needs to be mutated outside the `PeerManager` as well.  I would be on board with creating perhaps a newtype to encapulate this without duplicating the state, achieves the same and maintains the isolation. That is a bit outside the scope of this tho, as the focus is first to stop the entanglement between score and connection state

2023-08-28 01:31 UTC, closed without merging