Fix bug in lcli transition-blocks and improve pretty-ssz
sigp/lighthouse pull request #4513
Opened 2023-07-18 03:24 UTC by michaelsproul

## Proposed Changes

- Fix bad `state_root` reuse in `lcli transition-blocks` that resulted in invalid results at skipped slots.
- Modernise `lcli pretty-ssz` to include fork-generic decoders for `SignedBeaconBlock` and `BeaconState` which respect the `--network`/`--testnet-dir` flag.

## Additional Info

Breaking change: the underscore names like `signed_block_merge` are removed in favour of the fork-generic name `SignedBeaconBlock`, and fork-specific names which match the superstruct variants, e.g. `SignedBeaconBlockMerge`.

2023-07-18 04:20 UTC, jimmygchen requested changes
Looks like the local testnet script needs a small update (replace `state_merge` with `BeaconStateMerge`), otherwise looks great!
https://github.com/sigp/lighthouse/blob/087b480ffa0da9a1c9797ac6ffb37ea696c0a25e/scripts/local_testnet/start_local_testnet.sh#L106

2023-07-18 04:30 UTC, michaelsproul commented
Thanks Jimmy! Fixed in 430e4380ee69c16968e9e5f10f226957d44223db (will wait to see if it passes CI).

2023-07-18 06:16 UTC, jimmygchen approved these changes
LGTM! 👍

2023-07-31 01:52 UTC, paulhauner commented
bors r+

2023-07-31 02:38 UTC, closed without merging