Improvements to Deneb `store` upon review
sigp/lighthouse pull request #4693
Opened 2023-09-01 08:37 UTC by michaelsproul

## Issue Addressed

Part of #4676

## Proposed Changes

- [x] Remove unnecessary lazy_static for `MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS`.
- [x] Fix bugs in blob pruning (`blob_sidecar_exists` was buggy and caused pruning to always no-op).
- [x] Clarify code comments and logs in blob pruning. This just felt natural as I was poking around and improving my understanding.
- [ ] Remove unnecessary `BeaconBlobOrphan` column (TODO).
- [ ] Add a database schema migration with no-op upgrade, and a no-op downgrade that only suceeeds _before_ Deneb.
- [x] Test for blob pruning happy case.
- [ ] Test for blob pruning without Deneb (should return early).
- [ ] Test for blob pruning without finalization (should return early).

2023-09-19 02:52 UTC, jimmygchen commented on consensus/types/src/consts.rs
>              "52435875175126190479447740508185965837690552500527637822603658699938581184513"
just discussed with @michaelsproul and might be worth moving this to a const as well

2023-09-20 14:09 UTC, realbigsean requested changes
Awesome! Looks a lot simpler and the new tests are great

2023-09-20 14:09 UTC, realbigsean commented on beacon_node/beacon_chain/src/schema_change/migration_schema_v18.rs
> +    // *maybe* the fork recovery will revert the minority fork and suceed.
```suggestion
    // No-op, even if Deneb has already occurred. The database is probably borked in this case, but
    // *maybe* the fork recovery will revert the minority fork and succeed.
```

2023-09-20 14:09 UTC, realbigsean commented on beacon_node/beacon_chain/src/historical_blocks.rs
> +        if let Some(oldest_blob_slot) = new_oldest_blob_slot {
should we skip this if `new_oldest_blob_slot` is unchanged?

2023-09-20 14:09 UTC, realbigsean commented on beacon_node/store/src/hot_cold_store.rs
> +                        "Stopping blob pruning early";
love that we're pruning the name `sidecar` from our codebase

2023-09-20 14:09 UTC, realbigsean commented on beacon_node/store/src/hot_cold_store.rs
>          };
```suggestion
        if self.spec.deneb_fork_epoch.is_none() {
            debug!(self.log, "Deneb fork is disabled");
            return Ok(());
        }
```

2023-09-20 14:09 UTC, realbigsean commented on beacon_node/store/src/hot_cold_store.rs
>                  debug!(
should this be a trace if we're emitting it up to once per block on a prune? Could be pretty spammy

2023-09-20 14:09 UTC, realbigsean commented on beacon_node/beacon_chain/src/canonical_head.rs
> +        // Prune blobs in the background.
Just noting: moving this to `after_finalization` definitely make sense with how we're currently pruning. But we'll have to move it if we want to extend pruning to work for unfinalized blobs in a future PR

2023-09-21 01:27 UTC, michaelsproul commented on beacon_node/store/src/hot_cold_store.rs
> +                        "Stopping blob pruning early";
I was getting irked by the weird pluralisation of "blobs sidecars", so I just nuked it

2023-09-25 12:01 UTC, realbigsean approved these changes
Looks like all comments are addressed, I'm going to give this a whirl on devnet 8

2023-09-25 18:21 UTC, realbigsean commented
looks like it works on devnet 8

2023-09-25 18:21 UTC, merged