Yet another configuration file PR
sigp/lighthouse pull request #4737
Opened 2023-09-15 00:44 UTC by jmcph4

## Issue Addressed

#2748 

## Proposed Changes

See #3079.

## Additional Info

This PR is purely a revival of #3079.

2023-09-20 17:07 UTC, realbigsean requested changes
Thanks for picking this up!

2023-09-20 17:07 UTC, realbigsean commented on common/clap_utils/src/preprocess.rs
> +/// `argmatches::expand_args_from` respectively, but differ in the following ways:
```suggestion
/// This function and `expand_args_from` are inspired by `argfile::expand_args_from` and
/// `argfile::expand_args_from` respectively, but differ in the following ways:
```

2023-09-20 17:07 UTC, realbigsean commented on common/clap_utils/src/preprocess.rs
> +) -> Result<Vec<std::ffi::OsString>, ClapPreprocessingError>
`OsString` is also imported so we can delete the path prefix (there's a few of these in this file)

```suggestion
) -> Result<Vec<OsString>, ClapPreprocessingError>
```

2023-09-20 17:07 UTC, realbigsean commented on common/clap_utils/src/preprocess.rs
> +/// This converts a givent map of config into a `Vec<OsString>`, for consumption by
```suggestion
/// This converts a given map of config into a `Vec<OsString>`, for consumption by
```

2023-09-20 17:07 UTC, realbigsean commented on book/src/file-config.md
> +eth1-endpoints: ["http://localhost:8545", "http://localhost:9545"]
These examples are a little out of date, this should probably be updated to `execution-endpoint` and only take a single value. Although it is nice to have an array example, so maybe we should add `validator-monitor-pubkeys` instead

2023-09-20 17:07 UTC, realbigsean commented on book/src/file-config.md
> +eth1-endpoints: ["http://localhost:8545", "http://localhost:9545"]
we should also maybe note in the docs that arrays can also work as a single CSV string `validator-monitor-pubkeys: "0x123..456,0x456..123"`

2023-12-15 07:27 UTC, michaelsproul commented
Lets revisit this for 4.7.0

2024-06-27 15:35 UTC, dapplion commented
We are slowly adopting clap v4 with derive syntax, which would allow us to finally have proper file config :)

Closing this approach in favor of the former

2024-06-27 15:35 UTC, closed without merging