fix(validator_client): raise soft fd limit
sigp/lighthouse pull request #4796
Opened 2023-09-30 10:19 UTC by rkrasiuk

## Issue Addressed

Closes https://github.com/sigp/lighthouse/issues/3468

## Proposed Changes

Attempt to raise validator client's fdlimit. OS specific behavior is described in the comments

2023-09-30 10:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=4796) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=4796) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=4796) it.</sub>

2024-01-19 10:40 UTC, dapplion requested changes, later dismissed
I have tested the fslimit crate on a separate repo on my local M2 mac on a regular user and it could raise the fd limit from 256 -> 10240.

However I have mixed feelings about this feature. It seems to only be useful to large operators or devnet operators, two parties who can manually raise the fd limit on their own.

I would recommend mantainers to take a look at the fdlimit crate briefly since it's just one short file https://github.com/paritytech/fdlimit/blob/master/src/lib.rs

To scope its usage better the validator client could only try to raise the fdlimit if needs too i.e. if the user is loading more than N keys.

2024-01-19 10:40 UTC, dapplion commented on validator_client/Cargo.toml
> +fdlimit = "0.2.1"
Can you use version 0.3.0? It includes an improvement to not panic on syscall errors, https://github.com/paritytech/fdlimit/commit/eee618fbe779452099f1857dd9191ec711067af6

2024-01-19 11:37 UTC, rkrasiuk commented
@dapplion upgraded the crate. re limiting this behavior - fair enough, we could raise fdlimit based on the current limit and the number of user keys loaded. alternatively, we could expose a CLI flag, that users could pass in case they hit the limit

2024-01-21 08:09 UTC, dapplion commented
> alternatively, we could expose a CLI flag, that users could pass in case they hit the limit

This feature is maximally useful when it allows users to not have to think about file limits. Adding a flag defeats the purpose, as after an error the user now has to add a new flag, might as well manually bump the file limit

2024-02-15 08:01 UTC, paulhauner commented
I've pushed this to v5.1.0 since it doesn't seem critical for Deneb.

2024-03-07 11:11 UTC, pawanjay176 commented
Pushed back to 5.2 since we want to get networking improvements in the 5.1 release out soon.

2024-04-02 02:30 UTC, dapplion approved these changes

2024-04-29 22:53 UTC, realbigsean commented
@mergify queue

2024-04-29 22:55 UTC, merged