feat(consensus): add the `max_request_blocks` field in `ChainSpec`
sigp/lighthouse pull request #4800
Opened 2023-10-03 09:07 UTC by duguorong009

## Issue Addressed
- Close #4711 

## Proposed Changes
- Update the `ChainSpec` struct of `consensus` crate
   Add the `max_request_blocks` field

## Additional Info
Originally, this PR is for addressing the issue of missing the `MAX_REQUEST_BLOCKS` info from lighthouse beacon API `/eth/v1/config/spec`.
While resolving the issue, I found that we don't need to update anything from BN crate code, but update the `ChainSpec` from `consensus` crate.
Hence, the PR is for updating the `consensus` crate, adding one more field to `ChainSpec` struct and related codes.

2023-10-06 04:15 UTC, michaelsproul requested changes
Sorry, it looks like this problem is a bit more involved than described on the issue. We not only need to include the `max_request_blocks` in the chain spec, but also need to _use_ this value in place of the existing `MAX_REQUEST_BLOCKS` constant. This will require refactoring some of the networking code, and should probably happen as part of the Deneb work (to avoid merge conflicts, and because Deneb also touches this code). I'll close the original issue and open a new one.

2023-10-06 04:17 UTC, divagant-martian commented
There is #4562 @michaelsproul

2023-10-06 04:27 UTC, michaelsproul commented
Ah! Thanks @divagant-martian, didn't see that!

2023-10-12 15:18 UTC, duguorong009 commented
@michaelsproul 
So, what do you want me to do?
As far as I see, this PR is for `Deneb` work.
So, simply change the merge destination branch to `Deneb` one?

2023-10-12 15:27 UTC, divagant-martian commented
HI @duguorong009 bare in mind that I'm not a team member but I know about this to some depth. What @michaelsproul is describing is that the changed you made address the issue partially and we want to address it fully. "Using" this value is what https://github.com/sigp/lighthouse/issues/4562 describes. This has not been done because in terms of code, it's not clear for us what's the best way to do it. Or at least it's definitely not straightforward. 

This being said, re-targeting to deneb is not going to be enough, I'm afraid

2023-10-12 15:34 UTC, duguorong009 commented
Thanks for the quick answer! @divagant-martian 
It seems like this PR needs to wait for the discussion result. (currently, leaving as is)

2023-10-25 03:50 UTC, michaelsproul commented
Thanks for your work on this @duguorong009, it helped us clarify the issue. I'm going to close your PR now in favour of the more involved fix here: #4841.

2023-10-25 03:50 UTC, closed without merging