Db compaction tweaks
sigp/lighthouse pull request #5142
Opened 2024-01-30 02:09 UTC by michaelsproul

## Issue Addressed

I noticed that `prune-states` doesn't actually clear any space on disk because we don't compact the freezer database after running it.

## Proposed Changes

- Compact the relevant columns of the freezer database after pruning states.
- Add a new `lighthouse db compact` command for manually compacting specific columns in a specific DB (hot, freezer or blobs).
- Add a `--blobs-db` option to `lighthouse db inspect` (and `compact`) so we can inspect the blobs DB as well as the freezer.

## Additional Info

I've manually tested the tree-states version of these changes (https://github.com/sigp/lighthouse/pull/5097) and the compaction works correctly.

2024-02-07 22:43 UTC, realbigsean requested changes
Love the addition of blob db compaction and inspection!!

2024-02-07 22:43 UTC, realbigsean commented on beacon_node/store/src/leveldb_store.rs
> +            &vec![0; std::cmp::max(column.key_size(), 32)],
this should be 255 or `u8::MAX`, right?

2024-02-07 22:46 UTC, michaelsproul commented on beacon_node/store/src/leveldb_store.rs
> +            &vec![0; std::cmp::max(column.key_size(), 32)],
oh, you're right!

2024-02-07 23:02 UTC, realbigsean approved these changes
LGTM

2024-02-08 09:13 UTC, michaelsproul commented
@mergifyio queue

2024-02-08 10:05 UTC, merged