Markdown linter
sigp/lighthouse pull request #5494
Opened 2024-03-27 12:54 UTC by chong-he

## Issue Addressed

* #5053

2024-03-28 01:53 UTC, AgeManning reviewed
Nice!

Could we add it into the `code-check` test? 

I recall grouping things improved the speed of CI and it seems this could fit under that test?

2024-03-28 02:15 UTC, chong-he commented
> Nice!
> 
> Could we add it into the `code-check` test?
> 
> I recall grouping things improved the speed of CI and it seems this could fit under that test?

I will look into it, thanks!

2024-03-28 04:18 UTC, michaelsproul commented on .github/workflows/test-suite.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
I think we might need this:

```suggestion
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
```

From https://stackoverflow.com/questions/77456851/how-to-configure-super-linter-on-github-for-all-branches

2024-03-29 23:35 UTC, jxs commented
can we run this conditionally, i.e. only for changes in markdown files?

2024-03-31 22:58 UTC, chong-he commented
> can we run this conditionally, i.e. only for changes in markdown files?

Yes, the `VALIDATE_MARKDOWN: true` is to only run this for markdown file. Got it from: https://github.com/super-linter/super-linter?tab=readme-ov-file#configure-super-linter which states:

If you set any of the VALIDATE_[LANGUAGE] variables to true, super-linter defaults to leaving any unset variable to false (only validate those languages).

2024-04-02 23:29 UTC, dapplion approved these changes
Purely formating changes, nothing controversial. They look good! I welcome the linter

2024-04-03 02:22 UTC, AgeManning commented
Probably need to pass the actual linter first

2024-04-03 02:51 UTC, chong-he commented
> Probably need to pass the actual linter first

Yes I am still figuring out to make it pass the CI. I will also make the linter to be in the same check with `code-check` later

2024-04-04 04:13 UTC, michaelsproul commented on book/src/validator-inclusion.md
>  ```
try adding `text` here

2024-04-12 05:15 UTC, macladson requested changes
Looks pretty good to me, just had a few notes

2024-04-12 05:15 UTC, macladson commented on scripts/mdlint.sh
> +docker run -v ./book:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest '**/*.md' --ignore node_modules
I _think_ it might be safer to add a `--rm` here just in case the container fails to exit cleanly?

```suggestion
docker run --rm -v ./book:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest '**/*.md' --ignore node_modules
```

2024-04-12 05:15 UTC, macladson commented on scripts/mdlint.sh
> +    docker run -v ./book:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest '**/*.md' --ignore node_modules --fix
```suggestion
    docker run --rm -v ./book:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest '**/*.md' --ignore node_modules --fix
```

2024-04-12 05:15 UTC, macladson commented on scripts/mdlint.sh
> +    echo "Exiting with errors. Run 'make mdlint' locally and commit the changes. Note that not all errors can be fixed automatically, if there are still errors after running 'make mdlint', look for t
Thank you for not using back-ticks and saving us from the crazy nested docker shenanigans :grin:

2024-04-12 05:15 UTC, macladson commented on scripts/mdlint.sh
> +# set -e
May as well remove this since we are exiting very explicitly
```suggestion
```

2024-04-12 05:15 UTC, macladson commented on scripts/mdlint.sh
> +    docker run -v ./book:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest '**/*.md' --ignore node_modules --fix
I think this should be fine (it worked fine for me), but if we start seeing permissions issues in certain environments, we might want to consider defining `--user` like we do for `cli.sh`.

2024-04-16 01:33 UTC, chong-he commented on scripts/mdlint.sh
> +# set -e
Removed in [b52597b](https://github.com/sigp/lighthouse/pull/5494/commits/b52597b5d9e06a6be9b4f2098acbdcf055752cc3)

2024-05-17 06:41 UTC, michaelsproul commented
@mergifyio queue

2024-05-21 01:13 UTC, michaelsproul commented
@mergifyio requeue

2024-05-23 00:37 UTC, michaelsproul commented
@mergifyio requeue

2024-05-23 01:14 UTC, michaelsproul commented
Ah, looks like this is failing to merge because of some formatting issues in `unstable`. @chong-he can you back-merge unstable to this branch, and then get CI passing again? :pray:

https://github.com/sigp/lighthouse/actions/runs/9200347323/job/25306765265

2024-05-23 10:08 UTC, chong-he commented
> Ah, looks like this is failing to merge because of some formatting issues in `unstable`. @chong-he can you back-merge unstable to this branch, and then get CI passing again? 🙏
> 
> https://github.com/sigp/lighthouse/actions/runs/9200347323/job/25306765265

Done, thanks!

2024-05-23 12:12 UTC, jimmygchen commented
@mergify queue

2024-05-24 00:54 UTC, michaelsproul commented
@mergifyio requeue

2024-05-24 02:43 UTC, michaelsproul commented
@mergifyio queue

2024-05-24 02:45 UTC, merged