Update Simulator tests
sigp/lighthouse pull request #5520
Opened 2024-04-04 10:10 UTC by macladson

## Issue Addressed

#5173 

## Proposed Changes

Adds fork compatibility up to Deneb (and Electra). This includes a basic check that each post-Deneb block has available blobs.

This also removes compatibility with pre-Bellatrix forks since Genesis now starts pre-merged.
This should hopefully allow us to remove `Anvil` as a dependency soon, although there is still a lot of older `Eth1` code that will need to be reworked/removed.

2024-04-17 14:03 UTC, realbigsean requested changes
Looks pretty much good to go! Just a couple minor comments

2024-04-17 14:03 UTC, realbigsean commented on testing/simulator/src/checks.rs
> +/// Verifies that there's been a block produced at every slot up to and including `slot`.
```suggestion
/// Verifies that there's been blobs produced at every slot with a block from `blob_start_slot` up to and including `slot`.
```

2024-04-17 14:03 UTC, realbigsean commented on testing/simulator/src/basic_sim.rs
> +                Epoch::new(DENEB_FORK_EPOCH + 1).start_slot(slots_per_epoch) + 1,
Don't think the offset should exist here
```suggestion
                Epoch::new(DENEB_FORK_EPOCH).start_slot(slots_per_epoch),
```

2024-04-18 06:23 UTC, macladson commented
Thanks! I also added the block production check to the `fallback-sim` since full block production is also indicative of the fallback mechanism working properly.

2024-04-22 12:15 UTC, realbigsean approved these changes
Nice! Let's send it!

2024-04-22 12:16 UTC, realbigsean commented
@mergify queue

2024-04-22 14:04 UTC, realbigsean commented
@mergify requeue

2024-04-22 15:08 UTC, merged