In-memory tree states
sigp/lighthouse pull request #5533
Opened 2024-04-08 06:21 UTC by michaelsproul

## Issue Addressed

This is the memory-only portion of `tree-states`, i.e. without any database schema changes.

- https://github.com/sigp/lighthouse/pull/3206

## Proposed Changes

- [x] Make `BeaconState` cheap to clone thanks to persistent data structures from [milhouse](https://github.com/sigp/milhouse).
- [x] Replace the snapshot cache with a new state cache inside the store which holds 32x more states for around the same memory cost :tada:
- [x] Delete the now-unnecessary `block_production_state`.
- [x] Delete `StateProcessingStrategy`. This could cause us to do more tree hashing in the case of an attester shuffling cache miss, but this is mitigated by 1) tree-states has faster tree hashing due to structural sharing, 2) the state cache is likely to hit even when the shuffling cache misses. It is less risky to remove the concept of inconsistent states altogether so that they can't end up in the new `state_cache` and poison it. We can re-optimise this codepath in future by adopting the `HotStateSummary` changes from full `tree-states`.

2024-04-12 04:03 UTC, michaelsproul commented on beacon_node/beacon_chain/src/state_advance_timer.rs
> -                            if let Err(e) = tx.notify_fork_choice_complete(next_slot) {
Not to self: should put this back

2024-04-16 04:50 UTC, michaelsproul commented
Some benchmarks as of `unstable` @ f5e0404fb8c5ad924b5d0f0f4e953f7a3778e327 and `tree-states-memory` @ bca33f1f5fd3f3ed373f78887820e04e604989da

| Slot (offset) | `unstable` total (slot/sigs/core/hash) | `tree-states-memory` total (slot/sigs/core/hash) |
| ------------- | -------------------------------- | ------------------------------  |
| 8867873 (1)   | 56.5ms (0ms/11.1ms/7.1ms/38.1ms) | 39.8ms (0ms/8.9ms/21.0ms/9.8ms) |
| 8867872 (0)   | 360.7ms (274.7ms/8.8ms/8.6ms/68.5ms) | 654.4 (493.2ms/11.0ms/19.1ms/130.96ms) |

This shows that we're ~30% processing average blocks (offsets 1-31) compared to unstable, due to the faster tree hashing.

However, compared to `unstable` with single-pass and _no tree-states_ we are slower at epoch boundaries. That's 81% slower to be precise :scream: Disregarding the slot-processing, which should happen as part of state advance, we have 86ms for unstable vs 161ms for tree-states, which is 87% slower.

This is not really a fair comparison however, due to single-pass, so I am in the process of re-running the benchmarks against `stable`.

2024-04-16 05:03 UTC, michaelsproul commented
Ok the epoch boundary case is similar on `stable` (345ms total, similar breakdown to `unstable), while block-processing is substantially slower (73ms).

I'm going to check there isn't something wrong with the single-pass caches.

2024-04-16 05:45 UTC, michaelsproul commented
Ok, the issue was in my benchmarking technique. For `tree-states`, the slot advance was creating a lot of pending updates, which were being applied in one big batch. A more realistic scenario is that these pending updates are applied after epoch processing as part of the state advance. By using `lcli skip-slots` to get the pre-state at slot 8867872 I got what I think is a more representative result:

```
[2024-04-16T05:21:46Z DEBUG lcli::transition_blocks] Slot processing: 310ns
[2024-04-16T05:21:46Z DEBUG lcli::transition_blocks] Build all caches (again): 1.89µs
[2024-04-16T05:21:46Z DEBUG lcli::transition_blocks] Batch verify block signatures: 10.485968ms
[2024-04-16T05:21:46Z DEBUG lcli::transition_blocks] Process block: 22.432465ms
[2024-04-16T05:21:46Z DEBUG lcli::transition_blocks] Post-block tree hash: 9.284713ms
[2024-04-16T05:21:46Z INFO  lcli::transition_blocks] Run 9: 42.259264ms
```

This is once again competitive with `unstable` (actually faster). So we can conclude that tree-states will almost always be faster, except in the case of a failed state advance. Even in the case the state is not advanced, that usually implies, there's a reorg or several skipped slots. Tree states is more likely to do well in these scenarios because it can clone the parent state faster and doesn't need to worry about snapshot cache misses.

2024-04-16 07:02 UTC, michaelsproul commented
Logging on one of our Holesky nodes running this branch shows an uptick in attestation queues becoming full, and this log:

> ERRO Failed to maintain availability cache   error: DecodeError(OffsetOutOfBounds(1157628160)), service: beacon

I need to dig into why the `DecodeError` is happening. It's definitely a bug.

2024-04-18 04:53 UTC, michaelsproul commented
Bug was actually in `unstable`, fixed here:

- https://github.com/sigp/lighthouse/pull/5533

2024-04-19 20:11 UTC, realbigsean requested changes
This is looking awesome! No snapshot cache is really nice!

2024-04-19 20:11 UTC, realbigsean commented on Cargo.toml
> +crossbeam-channel = "0.5.8"
this is up to `0.5.12` should we perhaps define it as `0.5`

2024-04-19 20:11 UTC, realbigsean commented on beacon_node/beacon_chain/src/block_verification.rs
> -    let block_delay = chain
should this have been removed?

2024-04-19 20:11 UTC, realbigsean commented on beacon_node/beacon_chain/src/builder.rs
> +            .build_all_committee_caches(&self.spec)
Do we need to call `build_all_committe_caches` here if we are calling `build_all_caches` on L464?

2024-04-19 20:11 UTC, realbigsean commented on testing/ef_tests/src/cases/ssz_generic.rs
> +                    Vector,
Should we be testing `Vector` and `FixedVector` since we're still using both?

2024-04-19 20:11 UTC, realbigsean commented on consensus/types/src/chain_spec.rs
> +    pub fn fork_activated_at_slot<E: EthSpec>(&self, slot: Slot) -> Option<ForkName> {
Not seeing this used anywhere

2024-04-19 20:11 UTC, realbigsean commented on consensus/types/Cargo.toml
> +rpds = "0.11.0"
Same comment as elsewhere about potentially moving this to a workspace dep

2024-04-19 20:11 UTC, realbigsean commented on consensus/state_processing/src/common/initiate_validator_exit.rs
> +    let validator = state.get_validator_cow(index)?;
Is there a reason to get a `Cow` here when it's made `into_mut` a couple lines later as opposed to using the getter that gets a mutable reference?

2024-04-19 20:11 UTC, realbigsean commented on consensus/state_processing/Cargo.toml
> +vec_map = "0.8.2"
Should this be a workspace dep? Honestly not sure whether our policy is all deps to workspace, or only deps used in multiple crates

2024-04-19 20:11 UTC, realbigsean commented on beacon_node/store/src/state_cache.rs
> +    capacity: NonZeroUsize,
If this is just tracking the `LruCache` capacity, `LruCache` has a `cap` method that could be used instead

2024-04-19 20:11 UTC, realbigsean commented on beacon_node/store/src/state_cache.rs
> +        if let Some(over_capacity) = self.len().checked_sub(self.capacity.get()) {
If this is just comparing the `LruCache` length vs capacity, I don't see how this condition could be hit, so I don't know that this custom `cull` method is actually being used.

2024-04-19 20:11 UTC, realbigsean commented on consensus/types/src/beacon_state.rs
> +    pub fn get_validator_index_read_only(
Not seeing this used anywhere

2024-04-19 20:11 UTC, realbigsean commented on consensus/types/src/beacon_state.rs
> +            bimappings(bimap_beacon_state_merge_tree_list_fields(
The other map macros here use `bellatrix`, we should probably keep it consistent

2024-04-19 20:11 UTC, realbigsean commented on consensus/types/src/beacon_state.rs
> +    pub fn has_pending_mutations(&self) -> bool {
This seems like it'd be a really good use case for `metastruct` mappings. So we wouldn't forget to update this with new fields. I tried out making an immutable an infallibe mapping for this and it's compiling for me:

```
    pub fn has_pending_mutations(&self) -> bool {
        let mut any_pending_mutations = false;
        match &self {
            Self::Base(self_inner) => {
                map_beacon_state_base_tree_list_fields_immutable!(self_inner, |_, self_field| {
                    if self_field.has_pending_updates() {
                        any_pending_mutations = true;
                    }
                });
            }
            Self::Altair(self_inner) => {
                map_beacon_state_altair_tree_list_fields_immutable!(self_inner, |_, self_field| {
                    if self_field.has_pending_updates() {
                        any_pending_mutations = true;
                    }
                });
            }
            Self::Merge(self_inner) => {
                map_beacon_state_bellatrix_tree_list_fields_immutable!(
                    self_inner,
                    |_, self_field| {
                        if self_field.has_pending_updates() {
                            any_pending_mutations = true;
                        }
                    }
                );
            }
            Self::Capella(self_inner) => {
                map_beacon_state_capella_tree_list_fields_immutable!(
                    self_inner,
                    |_, self_field| {
                        if self_field.has_pending_updates() {
                            any_pending_mutations = true;
                        }
                    }
                );
            }
            Self::Deneb(self_inner) => {
                map_beacon_state_deneb_tree_list_fields_immutable!(self_inner, |_, self_field| {
                    if self_field.has_pending_updates() {
                        any_pending_mutations = true;
                    }
                });
            }
            Self::Electra(self_inner) => {
                map_beacon_state_electra_tree_list_fields_immutable!(
                    self_inner,
                    |_, self_field| {
                        if self_field.has_pending_updates() {
                            any_pending_mutations = true;
                        }
                    }
                );
            }
        };
        any_pending_mutations
    }
```

2024-04-22 03:31 UTC, michaelsproul commented on beacon_node/beacon_chain/src/block_verification.rs
> -    let block_delay = chain
yeah this was previously only used for deciding whether to clone from the snapshot cache, and logging associated with that

2024-04-22 03:44 UTC, michaelsproul commented on consensus/state_processing/src/common/initiate_validator_exit.rs
> +    let validator = state.get_validator_cow(index)?;
Hmm I think it was in case the validator is already exited and we hit the `return Ok(())` case. But I don't imagine that happens very often

2024-04-22 12:14 UTC, realbigsean commented on consensus/state_processing/src/common/initiate_validator_exit.rs
> +    let validator = state.get_validator_cow(index)?;
ndb either way

2024-04-23 00:19 UTC, michaelsproul commented on consensus/state_processing/Cargo.toml
> +vec_map = "0.8.2"
deleted this as it wasn't actually used explicitly

2024-04-23 00:24 UTC, michaelsproul commented on beacon_node/store/src/state_cache.rs
> +        if let Some(over_capacity) = self.len().checked_sub(self.capacity.get()) {
If `len == capacity` then we'll get `over_capacity == 0`, and will cull `over_capacity + 1 == 1`, right?

Maybe we should try increasing the number of states that are culled (the +1)

2024-04-23 00:37 UTC, michaelsproul commented on consensus/types/src/beacon_state.rs
> +    pub fn has_pending_mutations(&self) -> bool {
done!

2024-04-23 00:37 UTC, michaelsproul commented on beacon_node/store/src/state_cache.rs
> +    capacity: NonZeroUsize,
nice, fixed

2024-04-23 05:50 UTC, michaelsproul commented
I pushed a commit 970f3dfc6eca93bbdbf11b89e6c93157eb693bcd which seems to have made memory usage less spikey on a restart (see 12:30 in chart). The problem previously was that the head state would not get cached in the `state_cache` on startup, creating the possibility for a cache-miss and reload from disk, which would increase memory usage due to the lack of full structural sharing.

![spikeyness](https://github.com/sigp/lighthouse/assets/4452260/5790aa73-fc1c-4e40-b56e-5ef5d3bb7be6)

The memory usage is still a bit spikier than I'd like, and this is despite a complete absence of cache misses. This may be memory usage unrelated to the state cache.

Even so, tree-states is using consistently less memory with lower spikes than `stable`:

![bn_memory_comparison](https://github.com/sigp/lighthouse/assets/4452260/c33503c2-b202-4b48-8c11-606f24bb0b2e)

The yellow line at the bottom is this branch, the rest are running variants of stable/unstable.

2024-04-23 20:44 UTC, realbigsean commented on beacon_node/store/src/state_cache.rs
> +        if let Some(over_capacity) = self.len().checked_sub(self.capacity.get()) {
oh right `len == capacity` 😂 my bad

> Maybe we should try increasing the number of states that are culled (the +1)

No, I think it's fine how it is, it's sort of just customizing the lru cache's prune mechanic which makes sense.

2024-04-23 20:45 UTC, realbigsean approved these changes
🚀

2024-04-23 23:47 UTC, realbigsean commented
@mergify queue

2024-04-24 00:02 UTC, jimmygchen commented on beacon_node/beacon_chain/src/beacon_chain.rs
> +                let (state_root, state) = self
I think the log above needs to be updated to remove snapshot cache:

https://github.com/sigp/lighthouse/blob/970f3dfc6eca93bbdbf11b89e6c93157eb693bcd/beacon_node/beacon_chain/src/beacon_chain.rs#L4398-L4403

2024-04-24 00:10 UTC, jimmygchen commented
Some minor comments:
- [The description for `--state-cache-size`](https://github.com/sigp/lighthouse/blob/6bac5ce12b94c397ee0a7d5423a0eeab814c3682/beacon_node/src/cli.rs#L623-L629) needs an update i think - replace the "snapshot cache" and also update the default to `128`.
- Remove snapshot cache related metrics [here](https://github.com/sigp/lighthouse/blob/de7ae83abc3cb657453eb730b18eaf114336d6b3/beacon_node/beacon_chain/src/metrics.rs#L35-L46)

2024-04-24 00:13 UTC, realbigsean commented
@mergify dequeue

2024-04-24 00:14 UTC, realbigsean commented
sorry @jimmygchen didn't realize you were mid-review!

2024-04-24 00:22 UTC, jimmygchen commented
All good, happy to merge this as it's gone through some testing and you've already done a round of review!
I'm just going through the changes to help me understand them, it'd probably take me a while. I haven't found anything major that's worth stopping the mege, I think we're good to merge and address further comments in a separate PR? 

I'd be keen to get this in so 
- we avoid further code conflicts
- others working on `unstable` can help discover potential issues not yet identified

2024-04-24 00:22 UTC, realbigsean commented
@jimmygchen has expressed offline he's good with merging and allowing feedback resolution in a followup PR so as to avoid conflicts

2024-04-24 00:22 UTC, realbigsean commented
@mergify queue

2024-04-24 00:23 UTC, realbigsean commented
@mergify requeue

2024-04-24 01:22 UTC, merged

2024-04-24 04:18 UTC, jimmygchen commented on beacon_node/beacon_chain/src/metrics.rs
> +        beacon_chain.store.state_cache_len(),
Can we rename the metrics to `BLOCK_PROCESSING_STATE_CACHE_SIZE` instead?