Report RPC Errors to the application on peer disconnections
sigp/lighthouse pull request #5658
Opened 2024-04-29 07:03 UTC by AgeManning

As we are overhaling some internal RPC infrastructure, a desired feature is to report peer disconnects on RPC requests. 

This PR should report an RPCError(Disconnected) if a connection is terminated whilst an RPC request is underway.

2024-04-29 07:19 UTC, dapplion approved these changes
Thank you! `expect` usage is ok

2024-05-01 17:42 UTC, pawanjay176 requested changes
Nice.

2024-05-01 17:42 UTC, pawanjay176 commented on beacon_node/lighthouse_network/tests/rpc_tests.rs
> +                        panic!("got RPCError");
We should return true from the future if we entered this branch and only pass the test in that case.

2024-05-02 08:00 UTC, dapplion commented
- Closing for https://github.com/sigp/lighthouse/pull/5680

2024-05-02 08:00 UTC, closed without merging