Add more info about why lookup is in AwaitingDownload
sigp/lighthouse pull request #5838
Opened 2024-05-24 17:11 UTC by dapplion

## Issue Addressed

When debugging lookup stuck incidents in https://github.com/sigp/lighthouse/issues/5833, it's very helpful to know if the specific reason why a lookup is at the `AwaitingDownload` state.

## Proposed Changes

As purely informational, append to `AwaitingDownload` enum variant the last reason why the lookup is at that state.

2024-05-24 17:46 UTC, realbigsean requested changes
I like the idea!

2024-05-24 17:46 UTC, realbigsean commented on beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
> +                self.state = State::AwaitingDownload("retry");
Might be good to differentiate "retry after download failure" from "retry after processing failure"

2024-05-24 17:46 UTC, realbigsean commented on beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
> +            _ => {}
looks like a lint is failing here

2024-05-24 18:12 UTC, dapplion commented on beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
> +                self.state = State::AwaitingDownload("retry");
Changed to "not started" since it will never remain in that state

2024-05-24 21:06 UTC, realbigsean approved these changes

2024-05-25 14:29 UTC, realbigsean commented
@mergify queue

2024-05-27 06:40 UTC, michaelsproul commented
needs an update

2024-05-28 02:46 UTC, jimmygchen commented
@mergify queue

2024-05-28 02:48 UTC, merged