Add builder header timeout flag
sigp/lighthouse pull request #5857
Opened 2024-05-28 16:35 UTC by eserilev

## Issue Addressed

#4709
## Proposed Changes

Add a new flag `builder-header-timeout` which allows for configuring timeouts for the get builder header api call

2024-05-28 16:46 UTC, eserilev commented
Do we want to force minimum and maximum values for this flag? I don't see why anyone would want this set to less than one second, or more than 2-3 seconds

2024-05-28 22:43 UTC, dapplion reviewed
> Do we want to force minimum and maximum values for this flag? I don't see why anyone would want this set to less than one second, or to more than 2-3 seconds

If you set a very low value you will prioritize local building, which you can do today already.
If you set a very high value you will never consider local building and potentially cause liveness issues if builders misbehave. In extreme cases the failover should kick in switching to local building if the failures are common.

I have a soft opinion towards not specifying neither a minimum nor a maximum

2024-05-28 22:43 UTC, dapplion commented on consensus/types/src/test_utils/test_random/bitfield.rs
> +        }
Sneaked in from the other PR?

2024-05-28 23:54 UTC, jxs commented on beacon_node/execution_layer/src/lib.rs
> +    /// from the builder api
```suggestion
    /// from the builder api.
```

2024-05-28 23:54 UTC, jxs commented on beacon_node/builder_client/src/lib.rs
> +        };
nit:
```suggestion
        let get_header = get_header_timeout.unwrap_or(DEFAULT_GET_HEADER_TIMEOUT_MILLIS);
```

2024-05-29 04:14 UTC, jimmygchen requested changes
Looks good - I don't have anything else to add!

2024-05-29 07:10 UTC, eserilev commented on consensus/types/src/test_utils/test_random/bitfield.rs
> +        }
oops thanks

2024-05-30 00:12 UTC, michaelsproul approved these changes
Looks good modulo capitalisation fix

2024-05-30 00:12 UTC, michaelsproul commented on beacon_node/src/cli.rs
> +                    fetching a block header from the builder api.")
```suggestion
                    fetching a block header from the builder API.")
```

2024-05-30 00:12 UTC, michaelsproul commented on book/src/help_bn.md
> +          header from the builder api. [default: 1000]
```suggestion
          header from the builder API. [default: 1000]
```

2024-05-31 02:55 UTC, michaelsproul commented
@mergifyio queue

2024-05-31 03:35 UTC, merged