Consolidate non-configurable constants from chainspec
sigp/lighthouse pull request #6028
Opened 2024-07-01 09:57 UTC by pawanjay176

## Issue Addressed

Resolves #5631 

## Proposed Changes

We currently have a lot of spec constants listed under lighthouse's ChainSpec struct. Values in chainspec are meant to be configurable from a given config file. Hence, there is no point in having spec defined constants under chainspec.

This PR moves all values defined as constant in the spec to types/consts.rs. 
This is more consistent imo and also reduces the need to pass a `ChainSpec` in many places across the code.
Most of the diff is renames from `spec.x` to `X` and importing the required constants.

## Additional Info

This specific test is a confusing case. https://github.com/sigp/lighthouse/blob/70bcba1e6b7a7123b2f48e1c77b9afb9bbb11c26/consensus/types/src/beacon_state/iter.rs#L118

We are setting a custom value for genesis_slot which is defined as a constant in the [spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#misc) 
I don't think this is required behaviour from lighthouse, not completely sure though.

2024-07-03 08:29 UTC, dapplion commented
Conflicts 🙌

2024-07-22 16:47 UTC, realbigsean commented on consensus/types/src/beacon_state/iter.rs
> +    // TODO(do we need this test?)
I think you can revive this test if instead of using `all_roots` you directly contruct an iter: `BlockRootsIter::new(self, GENESIS_SLOT)`

2024-07-22 17:12 UTC, realbigsean requested changes
Love how much `ChainSpec` passing we can get rid of

2024-07-22 17:12 UTC, realbigsean commented on consensus/types/src/consts.rs
> +pub mod phase0 {
Looks like `INTERVALS_PER_SLOT` is actually phase0/

Also `TARGET_AGGREGATORS_PER_COMMITTEE` looks like it was missed in the migration here

2024-07-22 17:12 UTC, realbigsean commented on consensus/types/src/config_and_preset.rs
> +        "domain_application_mask".to_uppercase()=> u32_hex(APPLICATION_DOMAIN_BUILDER),
I think we should use 2 separate constants for the mask vs the builder domain even though `DOMAIN_APPLICATION_MASK == APPLICATION_DOMAIN_BUILDER`. probably better to make a specific `DOMAIN_APPLICATION_MASK` constant available

2024-07-23 18:32 UTC, pawanjay176 commented on consensus/types/src/consts.rs
> +pub mod phase0 {
Seems like we play with the value of `target_aggregators_per_committee` for easier testing.
https://github.com/sigp/lighthouse/blob/unstable/beacon_node/beacon_chain/src/test_utils.rs#L173

I'm a little hesitant to do this PR if we are not moving all constants. Practically, its just a minor annoyance so I'm fine either way. 
What do you think? cc @michaelsproul

2024-09-03 13:15 UTC, michaelsproul commented on consensus/types/src/consts.rs
> +pub mod phase0 {
Hmm, target aggregators per committee probably needs to stay tweak-able

2024-09-03 18:07 UTC, pawanjay176 commented
Closing this as the cost to effort ratio isn't looking great

2024-09-03 18:07 UTC, closed without merging