Visualisation logging for sync batch states
sigp/lighthouse pull request #6034
Opened 2024-07-02 05:03 UTC by AgeManning

I have been writing up logic about how sync works and also debugging some sync issues locally. 

I thought it would be an improvement to have a visual representation of a current chain state, to help see where abouts the progress of a chain is at any given point from just eyeballing the logs. 

I set a few icons to represent different batch states:
```
    /// The current icons are:
    /// - Empty/Uninitialized: 
    /// - Downloading: 󰦗
    /// - Awaiting Download: 󰝤
    /// - Awaiting Validation: 󰦖
    /// - Failed: 
    /// - AwaitingProcessing: 
```
These are from `nerd-fonts` and should appear for any os with the fonts installed. 

These changes produce a small log when we are updating the chain state showing the current state of our block downloading buffer. 

Here are some example logs I've run on a mainnet head sync:

```
Jul 02 04:48:30.068 DEBG Requesting batch                        batch_state: [󰝤 ], start_slot: 9422560, end_slot: 9422591, downloaded: 0, processed: 0, processed_no_penalty: 0, state: Downloading(16Uiu2HAmCJEcww2BZ7Cj93Rvzkj8cf19pAmi2kiFw4qj9X5vw7AU, 13), batch_ty: blocks_and_blobs, epoch: 294455, chain: 12325625451770947895, service: range_sync, service: sync
Jul 02 04:48:30.119 DEBG Requesting batch                        batch_state: [󰦗 󰝤 ], start_slot: 9422592, end_slot: 9422623, downloaded: 0, processed: 0, processed_no_penalty: 0, state: Downloading(16Uiu2HAmFVBES8qsTwVeAM6Tv6V8qexeGZnkGKkTGhsRfjQnKbZt, 14), batch_ty: blocks_and_blobs, epoch: 294456, chain: 12325625451770947895, service: range_sync, service: sync
Jul 02 04:48:30.119 DEBG Requesting batch                        batch_state: [󰦗 󰝤 ], start_slot: 9422592, end_slot: 9422623, downloaded: 1, processed: 0, processed_no_penalty: 0, state: Downloading(16Uiu2HAmCJEcww2BZ7Cj93Rvzkj8cf19pAmi2kiFw4qj9X5vw7AU, 15), batch_ty: blocks_and_blobs, epoch: 294456, chain: 12325625451770947895, service: range_sync, service: sync
Jul 02 04:48:33.907 DEBG Requesting batch                        batch_state: [  󰦗 󰝤 ], start_slot: 9422624, end_slot: 9422655, downloaded: 0, processed: 0, processed_no_penalty: 0, state: Downloading(16Uiu2HAmUhvmM4z7XryDrMyQXVUrHB2AWMfaAPcmS5qQRoTSkzs7, 16), batch_ty: blocks_and_blobs, epoch: 294457, chain: 11891774074394069546, service: range_sync, service: sync
Jul 02 04:48:33.910 DEBG Batch downloaded                        awaiting_batches: 1, batch_state: [   󰦗 ], blocks: 0, epoch: 294456, chain: 11891774074394069546, service: range_sync, service: sync
Jul 02 04:48:36.055 DEBG Batch downloaded                        awaiting_batches: 2, batch_state: [     ], blocks: 16, epoch: 294457, chain: 11891774074394069546, service: range_sync, service: sync
Jul 02 04:48:36.462 DEBG Requesting batch                        batch_state: [󰦗 󰦗 󰝤 ], start_slot: 9422624, end_slot: 9422655, downloaded: 0, processed: 0, processed_no_penalty: 0, state: Downloading(16Uiu2HAmRtTvtezhpWsSBnRBVa29KsQf6Sb9sPA2uAqyUvnNSa6t, 17), batch_ty: blocks_and_blobs, epoch: 294457, chain: 12325625451770947895, service: range_sync, service: sync
```

It's not as handy as I had originally expected because the buffer is a moving window, but it is useful to show where sync might be stalling, how many we are currently downloading and what bottlenecks etc. 

A more holistic approach is probably a proper sync grafana dash.

2024-07-03 05:42 UTC, jimmygchen commented
The visualization is nice!! 🔥 

I couldn't get it to render on my terminal though, I've tried a few built-in fonts but they don't render, looks like I might have to install something from nerd-fonts?

I tried emojis and they work well (on my machine) - think it might be worth considering since some of them have been part of the Unicode standard for a while and have wide OS support. I've only tested on MacOS though ;)

2024-07-03 08:51 UTC, dapplion commented
<img width="459" alt="Screenshot 2024-07-03 at 10 51 42" src="https://github.com/sigp/lighthouse/assets/35266934/3546bfe1-342c-4b0f-aed7-06e1632c168a">

is it expected for icons to not render on the browser?

2024-07-03 14:00 UTC, ackintosh commented
I installed the [0xProto](https://www.nerdfonts.com/font-downloads) font on my Ubuntu machine and saw the following icons:

<img width="813" alt="image" src="https://github.com/sigp/lighthouse/assets/1885716/3be403c3-ecb5-4571-9539-83831437ae52">

Using emojis seems like a good idea. 💡

2024-07-09 01:21 UTC, AgeManning commented
Yeah sorry. The fonts I used aren't widely used. 

If someone can suggest some good emoji's maybe we can do with that.

2024-07-09 01:50 UTC, jimmygchen commented
Some options:

```rust
fn visualize(&self) -> &'static str {
    match self {
        BatchState::Downloading(_, _) => "⏬",
        BatchState::Processing(_) => "🔄",
        BatchState::AwaitingValidation(_) => "⏳",
        BatchState::AwaitingDownload => "📥",
        BatchState::Failed => "❌",
        BatchState::AwaitingProcessing(_, _) => "🕓",
        BatchState::Poisoned => "💀",
    }
}
```

Face emojis from neutral to happy face

```rust
fn visualize(&self) -> &'static str {
    match self {
        BatchState::AwaitingDownload => "😐",
        BatchState::Downloading(_, _) => "🙂",
        BatchState::AwaitingProcessing(_, _) => "😊",
        BatchState::Processing(_) => "😃",
        BatchState::AwaitingValidation(_) => "😁",
        BatchState::Failed => "😞",
        BatchState::Poisoned => "😵",
    }
}
```

2024-07-09 02:19 UTC, AgeManning commented
Awesome thanks. I replaced them with emoji's now.

2024-07-10 08:54 UTC, dapplion commented
Not sure how I feel to have debug logs full of emojis now.. haha

This batch state codes will be read by a small minority of devs who could memorize the meaning of a few letters. Plus there are ordering rules of states that reduce the max possible combination of states. ASCII has a bunch of disctict symbols that can de used.

For example:
- Downloading -> `D`
- Processing -> `P`
- Awaiting`X` -> lowercase `x`
- Failed -> `F`
- Poisoned -> `P`

```rust
fn visualize(&self) -> &'static str {
    match self {
        BatchState::Downloading(_, _) => "D",
        BatchState::Processing(_) => "P",
        BatchState::AwaitingValidation(_) => "v",
        BatchState::AwaitingDownload => "d",
        BatchState::Failed => "F",
        BatchState::AwaitingProcessing(_, _) => "p",
        BatchState::Poisoned => "X",
    }
}
```

2024-07-11 06:03 UTC, AgeManning commented
Yeah fair. I'm not sold on this PR and if people don't find it useful, happy to ditch it. 

The reason I built it was, i saw a couple of times sync being stalled and it was kind of pain to track down and figure out what we were waiting on this (because the batches are all numbers). 

Happy to switch to text for the states. If i get a few thumbs on this, then I'll consider this PR useful, switch to text and merge down. 

If not many thumbs <3, i'll close this PR

2024-07-11 06:09 UTC, jimmygchen commented
Gave you both my thumbs 👍

2024-07-11 12:26 UTC, dapplion commented
> The reason I built it was, i saw a couple of times sync being stalled and it was kind of pain to track down and figure out what we were waiting on this (because the batches are all numbers).

Sync lookup has now a gadget to detect when it gets stuck and drops a nice long report to logs. This has been the key to debug stalls in minutes instead of hours. We could do the same for other syncs

2024-07-23 04:08 UTC, jimmygchen commented on beacon_node/network/src/sync/range_sync/batch.rs
> +    /// NOTE: May require nerd-fonts
This comment can be removed now

2024-07-23 04:11 UTC, jimmygchen commented on beacon_node/network/src/sync/range_sync/batch.rs
> +    /// - AwaitingProcessing: 
`Empty/Uninitialized` and `AwaitingProcessing` aren't rendering for me here - are they emojis? This list don't cover all variants below, (missing `Processing`, `Poisoned`)

2024-07-23 04:14 UTC, jimmygchen commented on beacon_node/network/src/sync/range_sync/chain.rs
> +                    visualization_string.push('');
This doesn't render for me, but I think it's the character you want lol (the math symbol that never renders)

2024-07-23 04:15 UTC, jimmygchen approved these changes
Added some minor comments, otherwise looks good to me!

2024-07-23 07:21 UTC, jimmygchen commented on beacon_node/network/src/sync/range_sync/batch.rs
> +            BatchState::AwaitingValidation(_) => 'V',
I think the proposed convention is to use lower case for all `Awaiting-` states. Or are you using `V` here because we don't have a conflict for 'v'?

2024-07-24 08:15 UTC, dapplion requested changes
There's a `Cargo.lock` diff

2024-07-24 08:16 UTC, dapplion commented on beacon_node/network/src/sync/range_sync/batch.rs
> +    /// - Poisoned => "X",
This mapping comment should be removed as it does not add any new information not visible in the code below and risks going stale

2024-07-25 06:01 UTC, AgeManning commented
@mergifyio queue

2024-07-25 13:41 UTC, jimmygchen approved these changes

2024-07-25 13:41 UTC, jimmygchen commented
@mergify requeue

2024-07-25 23:45 UTC, jimmygchen commented
@mergify requeue

2024-07-26 05:19 UTC, jimmygchen approved these changes

2024-07-26 09:56 UTC, dapplion approved these changes

2024-07-29 03:11 UTC, AgeManning commented
@mergifyio refresh

2024-07-29 05:25 UTC, jimmygchen commented
@mergify requeue

2024-07-29 05:52 UTC, merged