Add PeerDAS presets and configs.
sigp/lighthouse pull request #6127
Opened 2024-07-18 07:10 UTC by jimmygchen

## Issue Addressed

Part of #6072

## Proposed Changes

This PR pulls all presets and configs related changes from the `das` branch.

2024-07-18 11:41 UTC, pawanjay176 requested changes
Looks good except a config value

2024-07-18 11:41 UTC, pawanjay176 commented on consensus/types/src/chain_spec.rs
> +    512
Spec says 16384 🤔 
https://github.com/ethereum/consensus-specs/blob/dev/configs/mainnet.yaml#L163

2024-07-18 18:49 UTC, realbigsean approved these changes
looks good other than pawan's comment

2024-07-19 01:45 UTC, jimmygchen commented on consensus/types/src/chain_spec.rs
> +    512
Good catch! Fixed

2024-07-19 05:39 UTC, pawanjay176 approved these changes

2024-07-19 07:28 UTC, jimmygchen commented
@mergify queue

2024-07-22 02:24 UTC, jimmygchen commented
@mergify requeue

2024-07-22 04:27 UTC, jimmygchen commented
@mergify requeue

2024-07-22 05:47 UTC, jimmygchen commented
@mergify requeue

2024-07-22 06:25 UTC, merged