Add custody by root request to sync
sigp/lighthouse pull request #6275
Opened 2024-08-16 11:22 UTC by dapplion

## Issue Addressed

Part of 
- https://github.com/sigp/lighthouse/issues/4983
- https://github.com/sigp/lighthouse/issues/6072

## Proposed Changes

Adds a new higher order request to fetch all custody columns of a given block root.

It's a stateful request that may trigger one or more data_columns_by_root internally with features:
- per-column retry
- peer load balancing / prioritization of peer
- don't re-request peers that return failures for some time

2024-08-21 02:29 UTC, jimmygchen commented
This was automatically closed by mergify as the upstream branch was merged. I'll reopen this PR against `unstable`.

2024-08-21 10:15 UTC, jimmygchen commented
The refactoring on these PRs are making merging back to `das` really difficult, can we please avoid refactoring on these PRs, and instead do it against `das` branch? 

Some of the new function signatures require reworking parts of the existing code on `das` branch, so it would be easier if the refactor happens directly on `das` branch, otherwise we'd have to do the rework as part of the merge back to `das` which is really painful.

2024-08-21 12:40 UTC, jimmygchen commented on beacon_node/lighthouse_network/src/types/globals.rs
> +            .collect::<Vec<_>>()
Why not take the latest change from `das`branch?
This undos most the changes from #6218 - i understand selecting peers from entire peers is not the right solution, but even this doesn't fix it and just revert back to the previous version.

2024-08-21 12:40 UTC, jimmygchen commented on beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
> +        peer_id
Is all this change required? Why not just take the latest change from `das` branch? The change in #6218 fixes the custody lookup tests.

2024-08-21 12:41 UTC, jimmygchen commented on beacon_node/lighthouse_network/src/types/globals.rs
> +            .collect::<Vec<_>>()
Also happy if you'd like to change how it works on the `das` branch but i think it's better to target the `das` branch before we finish the merge to `unstable`.

2024-08-21 12:47 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/custody_by_root.rs
> +type DataColumnSidecarVec<E> = Vec<Arc<DataColumnSidecar<E>>>;
For consistency:

```suggestion
type DataColumnSidecarList<E> = Vec<Arc<DataColumnSidecar<E>>>;
```

Also updated on the `das` branch `custody.rs`

2024-08-21 12:48 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/custody_by_root.rs
> +    requester: SingleLookupReqId,
What's the reason to change this from `CustodyId`? (on `das` branch)

2024-08-21 12:49 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/custody_by_root.rs
> +type CustodyRequestResult<E> = Result<Option<DataColumnSidecarVec<E>>, Error>;
Are we dumping the peer group?

`das` branch: 

```
type CustodyRequestResult<E> = Result<Option<(DataColumnSidecarList<E>, PeerGroup)>, Error>;
```

2024-08-21 12:50 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/custody_by_root.rs
> +                            // Safe to cast, self.column_requests only contains indexes for columns we must custody
This comment can be removed as we're no longer casting, although I'm not sure why we removed the `CustodyDataColumn` type

2024-08-21 12:57 UTC, jimmygchen commented on beacon_node/network/src/sync/block_lookups/tests.rs
> +        }
Is this just for debugging? it doesn't actually assert anything but just prints

2024-08-21 13:03 UTC, jimmygchen commented on beacon_node/network/src/sync/manager.rs
> +        requester: SingleLookupReqId,
This parameter type isn't compatible with the `das` branch.

2024-08-21 13:05 UTC, jimmygchen commented on beacon_node/network/src/sync/manager.rs
> +                        peer_id,
We already have this on `das` branch, is there a reason why you don't want it included in this PR?

2024-08-21 13:15 UTC, jimmygchen requested changes
Nice, another 900+ lines down 🎉 
I've went through the code and I don't see anything impacting mainnet code path, so we should be good to go once comments are addressed and CI passes.

2024-08-28 06:13 UTC, jimmygchen commented
@dapplion Is there any refactor in this PR that you'd like to merge to `unstable`? or shall we close this one?

2024-08-28 08:35 UTC, dapplion commented
I ported a change to
- https://github.com/sigp/lighthouse/pull/6317

2024-08-28 08:35 UTC, closed without merging