Book: fix broken link in merge-migration.md
sigp/lighthouse pull request #6370
Opened 2024-09-07 21:40 UTC by silvekkk

Hi there, the original link is expired, I found this one may be the correct one.

2024-09-07 21:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=6370) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=6370) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=6370) it.</sub>

2024-09-09 01:19 UTC, jimmygchen requested changes
Thanks for reporting this, however I don't think the link provided is the right link for configuring Besu, I don't see the instructions there.

2024-09-09 02:46 UTC, chong-he commented
Maybe we can put the link to configure Besu: https://besu.hyperledger.org/public-networks/get-started/connect/mainnet

Having said that, I wonder should we add a section in the Lighthouse book titled `Archived` and keep all deprecated and archived pages under it? Examples include:
- this merge-migration 
- https://lighthouse-book.sigmaprime.io/pi.html
- https://lighthouse-book.sigmaprime.io/key-management.html

2024-09-09 16:39 UTC, silvekkk commented
> Maybe we can put the link to configure Besu: https://besu.hyperledger.org/public-networks/get-started/connect/mainnet
> 
Thanks for the tips fixed now!

> Having said that, I wonder should we add a section in the Lighthouse book titled `Archived` and keep all deprecated and archived pages under it? Examples include:
> 
> * this merge-migration
> * https://lighthouse-book.sigmaprime.io/pi.html
> * https://lighthouse-book.sigmaprime.io/key-management.html

 or we could directly delete them？

2024-09-10 02:24 UTC, chong-he commented
> > Maybe we can put the link to configure Besu: https://besu.hyperledger.org/public-networks/get-started/connect/mainnet
> 
> Thanks for the tips fixed now!
> 
> > Having said that, I wonder should we add a section in the Lighthouse book titled `Archived` and keep all deprecated and archived pages under it? Examples include:
> > 
> > * this merge-migration
> > * https://lighthouse-book.sigmaprime.io/pi.html
> > * https://lighthouse-book.sigmaprime.io/key-management.html
> 
> or we could directly delete them？

That could be fine, but keeping them may serve as future references just in case (e.g., some users may want to have a read at the R Pi 4 docs, or what happened back then during The Merge). 

Keen to hear from others about this

2024-09-18 12:03 UTC, silvekkk commented
@chong-he Hi, I'm wondering if there is anything more I need to fix in this PR?

2024-09-24 01:21 UTC, chong-he commented
> @chong-he Hi, I'm wondering if there is anything more I need to fix in this PR?

Not at the moment. 

Specifically, for small PR changes (e.g., 1-line), we have the following note to maintain the project quality:
https://github.com/sigp/lighthouse/blob/stable/CONTRIBUTING.md#i-dont-think-i-have-anything-to-add

So, we will see if the devs would think having more changes (e.g., add a deprecated section or other updates) is required.

2024-09-30 00:49 UTC, jimmygchen approved these changes
The new link LGTM.
I think we can probably address @chong-he's suggestions separately.

2024-09-30 00:51 UTC, jimmygchen commented
@chong-he I think we can merge this, as it fixes a broken link. I do agree we can archive the merge documentations.

2024-09-30 01:08 UTC, closed without merging

2024-09-30 01:11 UTC, jimmygchen commented
Issue raised: https://github.com/sigp/lighthouse/issues/6447

2024-10-02 17:10 UTC, LeesaZiegler approved these changes
API key 1ljbmqcbqlxlscfngtoa6dxejqagazxjomusnb1xvh4vzoomv35erilbhmqdjme0

2024-10-02 17:10 UTC, LeesaZiegler commented on book/src/merge-migration.md
> +- [Besu: Prepare For The Merge](https://besu.hyperledger.org/public-networks/get-started/connect/mainnet)
![blockware-bundles.csv](https://github.com/user-attachments/files/17233189/blockware-bundles.csv)

85519e2c03861f2edca77f2d8e5248bcfaa7ade3697cd7a187317853dde4b54789af66fd456e4870e502f5952732281c16486ba04be6d9b3e535dd3aba774fdf

2024-10-02 17:10 UTC, LeesaZiegler commented on book/src/merge-migration.md
> +- [Besu: Prepare For The Merge](https://besu.hyperledger.org/public-networks/get-started/connect/mainnet)
Https://blockchain.com

2024-10-02 17:10 UTC, LeesaZiegler commented on book/src/merge-migration.md
> +- [Besu: Prepare For The Merge](https://besu.hyperledger.org/public-networks/get-started/connect/mainnet)
Https://localhost:3000