Electra updates for v1.5.0-alpha.6
sigp/lighthouse pull request #6445
Opened 2024-09-28 00:45 UTC by pawanjay176

## Issue Addressed

N/A

## Proposed Changes

1. https://github.com/ethereum/consensus-specs/pull/3882 . I modified the existing `process_single_slashing` function instead of creating a new function for electra as I think both the pre-electra and electra functions have the same logic. I'm not completely sure if we need to make a separate >= Electra function and keep the pre-electra logic as is.
2. https://github.com/ethereum/consensus-specs/pull/3915 : just remove unused Consolidations domain
3. Rename `get_validator_max_effective_balance` https://github.com/ethereum/consensus-specs/pull/3909

Remaining [spec updates](https://github.com/ethereum/consensus-specs/releases/tag/v1.5.0-alpha.6) for electra are cosmetic

2024-10-10 20:31 UTC, ethDreamer requested changes
Looks good! Almost done reviewing, just gotta do the single pass changes.

2024-10-10 20:31 UTC, ethDreamer commented on beacon_node/execution_layer/src/engine_api/new_payload_request.rs
> +    pub execution_requests_list: Vec<Bytes>,
This is kinda rough because it does processing and holds the data rather than a reference. I remember when I created the `NewPayloadRequest`, I got rid of copies so it was lightweight because (if I remember correctly) there's points in the code where `NewPayloadRequest` is created, then some validations are done and it gets dropped. And then later another request is made.

It would be cool to continue this and rather than holding a `Vec<Bytes>` here just hold a `&'block ExecutionRequests<E>` just call `get_execution_requests_list()` on that reference when inside`new_payload_v4_electra()`. 

Then this object would remain lightweight and the processing would only be done when it actually needs to be.

2024-10-10 20:35 UTC, pawanjay176 commented on beacon_node/execution_layer/src/engine_api/new_payload_request.rs
> +    pub execution_requests_list: Vec<Bytes>,
good call, will make the changes

2024-10-10 20:45 UTC, pawanjay176 commented on beacon_node/execution_layer/src/engine_api/new_payload_request.rs
> +    pub execution_requests_list: Vec<Bytes>,
Added in ebc7265

2024-10-11 19:41 UTC, ethDreamer approved these changes
lgtm!

2024-10-15 05:36 UTC, michaelsproul approved these changes
LGTM!

Just a few minor comments

2024-10-15 05:36 UTC, michaelsproul commented on beacon_node/execution_layer/src/engine_api/json_structures.rs
> +/// Array of ssz-encoded requests list` encoded as hex bytes.
There's a stray backtick here, not sure what was intended:

```suggestion
/// Array of ssz-encoded requests list encoded as hex bytes.
```

2024-10-15 05:36 UTC, michaelsproul commented on beacon_node/execution_layer/src/lib.rs
> +        // TODO(pawan): this should probably be a separate variant/superstruct
Maybe we change this to `TODO(electra)` before merging? Or do you want to fix it first?

```suggestion
        // TODO(electra): this should probably be a separate variant/superstruct
```

2024-10-15 05:36 UTC, michaelsproul commented on beacon_node/execution_layer/src/test_utils/handle_rpc.rs
> +                            // TODO(pawan): add EL requests in mock el
```suggestion
                            // TODO(electra): add EL requests in mock el
```

2024-10-15 16:17 UTC, ethDreamer commented
@Mergifyio queue

2024-10-15 17:38 UTC, merged