Split the VC into crates making it more modular
sigp/lighthouse pull request #6453
Opened 2024-10-01 08:02 UTC by AgeManning

# Modularize the VC

The VC currently is built mostly as a single module. It self-references itself making it hard to modularize its components. 

This PR splits the VC into multiple sub-crates that can be imported independently making it useful to external projects, but also making the type dependencies cleaner and the code more logically grouped.

2024-10-08 07:10 UTC, AgeManning commented
I modified the general config, to include some sub-configs (It was required in order to split up dependencies and avoid circular ones). 

The only thing I can really foresee potentially breaking is serializing and de-serializing the validator config. I'm flattening the new inner configs, so I think it should behave the same, but I've not tested it.

2024-11-05 05:12 UTC, michaelsproul commented
I reverted the `cargo update` changes so we can get CI to pass on this branch. There's a regression caused by one of our deps:

- https://github.com/sigp/lighthouse/pull/6554

2024-11-05 05:55 UTC, michaelsproul requested changes
Reviewed half, will come back for the rest tomorrow

2024-11-05 05:55 UTC, michaelsproul commented on validator_client/beacon_node_fallback/Cargo.toml
> +[dev-dependencies]
Can just delete this

```suggestion
```

2024-11-05 05:55 UTC, michaelsproul commented on validator_client/http_api/src/tests.rs
> +        let secrets_dir: PathBuf = tempdir().unwrap().path().into();
I don't think this is a good idea, as the tempdir will get dropped and deleted?

I'm surprised the tests are passing currently

2024-11-05 05:55 UTC, michaelsproul commented on validator_client/http_metrics/Cargo.toml
> +[dev-dependencies]
```suggestion
```

2024-11-07 23:00 UTC, michaelsproul requested changes
Looks good on the whole. This was less daunting than I expected.

I'll push some small tweaks and then we can merge.

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/http_metrics/src/lib.rs
> +    encoder.encode(&metrics::gather(), &mut buffer).unwrap();
```suggestion
    encoder.encode(&metrics::gather(), &mut buffer).map_err(|e| format!("{:e?}"))?;
```

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/initialized_validators/Cargo.toml
> +[dev-dependencies]
```suggestion
```

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/signing_method/Cargo.toml
> +[dev-dependencies]
```suggestion
```

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/src/check_synced.rs
Nice catch deleting this unused file!

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/validator_metrics/Cargo.toml
> +[dev-dependencies]
```suggestion
```

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/validator_services/Cargo.toml
> +[dev-dependencies]
```suggestion
```

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/validator_store/Cargo.toml
> +[dev-dependencies]
```suggestion
```

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/validator_store/src/lib.rs
> +    /// Fallback fallback address.
```suggestion
    /// Fallback fee recipient address.
```

2024-11-07 23:00 UTC, michaelsproul commented on validator_client/validator_store/src/lib.rs
> +impl<T: SlotClock + 'static, E: EthSpec> DoppelGangerValidatorStore for ValidatorStore<T, E> {
I think we should rename this trait. Doppelganger with a capital G looks really weird

```suggestion
impl<T: SlotClock + 'static, E: EthSpec> DoppelgangerValidatorStore for ValidatorStore<T, E> {
```

2024-11-08 00:13 UTC, michaelsproul approved these changes

2024-11-08 00:59 UTC, michaelsproul commented
@mergify queue

2024-11-08 01:01 UTC, merged