Remove merge flags
sigp/lighthouse pull request #6489
Opened 2024-10-15 05:10 UTC by michaelsproul

## Proposed Changes

Start deleting some merge logic and flags. We don't need to carry this stuff around forever.

- [x] Delete all traces of `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY`. This concept was removed from the spec, so this was just dead code.
- [x] Delete CLI flags related to terminal total difficulty.

Ripping out the TTD logic more thoroughly proved to be more involved. A lot of our tests still depend on doing the merge transition, which is annoying. I have another branch where I started that work, but will submit it separately.

2024-10-17 16:33 UTC, macladson requested changes
I can't seem to comment on the files directly but there's a few more references to `safe_slots` in the `consensus/types/presets` files and also `book/src/api-vc-endpoints` that I think we can remove.

2024-10-17 16:33 UTC, macladson commented on lighthouse/tests/beacon_node.rs
> +// DEPRECATED. This flag is deprecated but should not cause a crash.
```suggestion
// DEPRECATED. This flag is deprecated but should not cause a crash.
```

2024-10-17 16:33 UTC, macladson commented on consensus/types/src/chain_spec.rs
May as well also remove the corresponding line in `test_defaults()` (line 2095)

2024-10-18 05:25 UTC, michaelsproul commented on consensus/types/src/chain_spec.rs
done

2024-10-18 05:25 UTC, michaelsproul commented on lighthouse/tests/beacon_node.rs
> +// DEPRECATED. This flag is deprecated but should not cause a crash.
done, thanks!

2024-10-18 05:26 UTC, michaelsproul commented
Updated thanks

2024-10-18 08:43 UTC, macladson approved these changes
LGTM!

2024-10-21 00:38 UTC, michaelsproul commented
@mergify queue

2024-10-21 01:28 UTC, merged