Migrate account manager cli client to clap derive
sigp/lighthouse pull request #6493
Opened 2024-10-16 01:29 UTC by eserilev

## Issue Addressed

Partially https://github.com/sigp/lighthouse/issues/5900

## Proposed Changes

Migrate account-manager to clap derive

2024-10-26 15:23 UTC, macladson requested changes
I think this PR needs some of the same love from #6300 since `lighthouse am --help` also doesn't work.

2025-04-22 16:45 UTC, eserilev commented
this one should be g2g for another review

2025-04-24 14:36 UTC, macladson requested changes
Will leave a more thorough review soon, but noticed some comments that need updating

2025-04-24 14:36 UTC, macladson commented on common/clap_utils/src/lib.rs
> +/// home directory and appends `default` to it.
I think this comment needs updating. Maybe also explain how this function is different from `v1`

2025-04-24 14:36 UTC, macladson commented on common/directory/src/lib.rs
> +/// and appends `flag` to it.
Same here

2025-04-24 23:39 UTC, eserilev commented on common/clap_utils/src/lib.rs
> +/// home directory and appends `default` to it.
updated

2025-04-24 23:39 UTC, eserilev commented on common/directory/src/lib.rs
> +/// and appends `flag` to it.
updated

2025-04-25 08:13 UTC, macladson requested changes

2025-04-25 08:13 UTC, macladson commented on account_manager/src/validator/modify.rs
> +        Modify::Disable(sub_matches) => (false, Box::new(sub_matches) as Box<dyn Modifiable>),
Unless I'm missing something I think we can remove both the `Box` and `Modifiable` if we just do: 

```suggestion
    let (enabled, pubkey, is_all) = match modify_config {
        Modify::Enable(enable) => (true, enable.pubkey.clone(), enable.all),
        Modify::Disable(disable) => (false, disable.pubkey.clone(), disable.all),
    };
```

2025-04-25 08:13 UTC, macladson commented on lighthouse/src/main.rs
> +            account_manager::run(&account_manager_config, matches, environment)?;
We should reorder this for consistency with the other subcommands
```suggestion
            account_manager::run(matches, &account_manager_config, environment)?;
```

2025-04-25 15:37 UTC, eserilev commented on lighthouse/src/main.rs
> +            account_manager::run(&account_manager_config, matches, environment)?;
[c0ce1cc](https://github.com/sigp/lighthouse/pull/6493/commits/c0ce1cceeab464925ea9d7a5cc4e2316fe35f186)

2025-04-25 15:39 UTC, eserilev commented on account_manager/src/validator/modify.rs
> +        Modify::Disable(sub_matches) => (false, Box::new(sub_matches) as Box<dyn Modifiable>),
c0ce1cc
9cfcc59

2025-06-22 13:52 UTC, eserilev commented
hi @chong-he could i bug you to review this PR please :)

2025-06-23 01:41 UTC, chong-he commented
> hi @chong-he could i bug you to review this PR when you get the chance :)

I wouldn't say I am capable to review this PR now, but I am happy to do some testing on this, will post if anything. 

Thanks!

2025-07-03 01:29 UTC, chong-he commented
After chatting with @michaelsproul , I am going to give reviewing this PR a try

2025-07-08 01:43 UTC, chong-he requested changes
Looks pretty good overall. There is just this thing that I found: 

For commands in `lighthouse am`, for example, when we run: `lighthouse account wallet create --name test`, this first line is printed when it shouldn't (unless `--logfile-dir` is specified): 
```
No logfile path provided, logging to file is disabled
Running account manager for mainnet network
wallet-dir path: "/home/ck/.lighthouse/mainnet/wallets"
```

It's from here: 
https://github.com/sigp/lighthouse/blob/3e6b0bd0a36dfa434a779812b648d15c9e67025f/lighthouse/environment/src/lib.rs#L217-L221

This looks like is because from here:
https://github.com/sigp/lighthouse/blob/3e6b0bd0a36dfa434a779812b648d15c9e67025f/lighthouse/src/main.rs#L569-L588

where `account_manager` falls into the `None` arm of the match automatically. We can add an `if` condition in the logging in `lighthouse/lighthouse/environment/src/lib.rs` to only print it for some subcommands, but that sounds a bit of a hack. I am sure you have a better solution for this. 

I think `logfile-dir` for  `account_manager` is not really relevant, so would be nice to not have that line printed (current `lighthouse db` also have this line printed)

2025-07-08 01:43 UTC, chong-he commented on account_manager/src/validator/cli.rs
> +    )]
Currently the flags are not sorted alphabetically. We can add `display_order = 0` to make it sorted, as in the validator client and database cli files.

```suggestion
        help = "Use the wallet identified by this name",
        display_order = 0
    )]
```

This applies to all flags in the `cli.rs` file

2025-07-08 01:43 UTC, chong-he commented on common/clap_utils/src/lib.rs
> +pub fn parse_path_with_default_in_home_dir_v2(
Small nit pick, would be good to put this after the function `parse_path_with_default_in_home_dir` for consistency

2026-01-08 00:15 UTC, macladson reviewed
I'll be dedicating some cycles soon to getting the existing `clap` PRs merged as I'm keen to see these happen!

2026-01-08 00:15 UTC, macladson commented on beacon_node/http_api/src/inclusion_list_duties.rs
Looks like this file snuck in from somewhere else

2026-01-08 20:58 UTC, eserilev commented on beacon_node/http_api/src/inclusion_list_duties.rs
oops, I've removed that file. thanks!

2026-02-25 19:32 UTC, macladson requested changes

2026-02-25 19:32 UTC, macladson commented on account_manager/src/lib.rs
>  pub const VALIDATOR_DIR_FLAG_ALIAS: &str = "validators-dir";
I think these constants are now unused since we define these in the actual struct definitions.

2026-02-25 19:32 UTC, macladson commented on account_manager/src/validator/cli.rs
> +        value_name = "VALIDATOR_DIRECTORY",
I think we have lost the previous alias `--validators-dir`, which we can add back like this:


```suggestion
    #[clap(
        long,
        alias = "validators-dir",
        value_name = "VALIDATOR_DIRECTORY",
```

2026-02-25 19:32 UTC, macladson commented on account_manager/src/validator/cli.rs
> +            method for importing a directory of keys generated by the eth2-deposit-cli \
Did this get renamed recently? It was `ethstaker-deposit-cli` previously 

```suggestion
            method for importing a directory of keys generated by the ethstaker-deposit-cli \
```

2026-02-25 19:32 UTC, macladson commented on account_manager/src/lib.rs
>  pub const VALIDATOR_DIR_FLAG_ALIAS: &str = "validators-dir";
There might be more unused constants in other modules too

2026-02-25 19:32 UTC, macladson commented on account_manager/src/wallet/cli.rs
> +pub trait NewWallet {
Should this trait exist in `cli.rs`? Seems like we should reserve the `cli.rs` file only for cli definitions

2026-02-26 20:51 UTC, eserilev commented on account_manager/src/lib.rs
>  pub const VALIDATOR_DIR_FLAG_ALIAS: &str = "validators-dir";
[555c100](https://github.com/sigp/lighthouse/pull/6493/commits/555c1001f26e35e21e9cdd3eb7552b6dc9ce26bf)

2026-02-26 20:52 UTC, eserilev commented on account_manager/src/validator/cli.rs
> +        value_name = "VALIDATOR_DIRECTORY",
[113c00e](https://github.com/sigp/lighthouse/pull/6493/commits/113c00e21b7f107077e4998aedf3213cd77020de)

2026-02-26 20:52 UTC, eserilev commented on account_manager/src/validator/cli.rs
> +            method for importing a directory of keys generated by the eth2-deposit-cli \
[77d08eb](https://github.com/sigp/lighthouse/pull/6493/commits/77d08eb0923fd99b434669fd8fd3e727ec0e987a)

2026-02-26 20:52 UTC, eserilev commented on account_manager/src/wallet/cli.rs
> +pub trait NewWallet {
[98159fb](https://github.com/sigp/lighthouse/pull/6493/commits/98159fb099a05126222178488070a4830051cecf)

2026-02-26 20:53 UTC, eserilev commented on account_manager/src/validator/cli.rs
> +    )]
i found out that we can define the display order at the struct level instead of individual fields!

2026-02-26 20:53 UTC, eserilev commented on common/clap_utils/src/lib.rs
> +pub fn parse_path_with_default_in_home_dir_v2(
its now listed after

2026-02-26 20:54 UTC, eserilev commented
I think I tackled all the feedback. Should be g2g for another review

2026-02-27 11:24 UTC, macladson reviewed
Looks like the `/lighthouse/tests` relied on those constants after all. We could either leave them, or hard code them in the lighthouse tests directly. It was kinda nice that they were imported constants, but most of the other cli flag tests just hard code them anyway so I don't think we lose that much realistically.

2026-03-16 09:15 UTC, eserilev commented
sorry jsut getting around to this now. the constants are in the test file now

2026-05-15 09:22 UTC, closed without merging