Add individual by_range sync requests
sigp/lighthouse pull request #6497
Opened 2024-10-16 22:37 UTC by dapplion

## Issue Addressed

Part of
- https://github.com/sigp/lighthouse/issues/6258

To address PeerDAS sync issues we need to make individual by_range requests within a batch retriable. We should adopt the same pattern for lookup sync where each request (block/blobs/columns) is tracked individually within a "meta" request that group them all and handles retry logic.

## Proposed Changes

- Building on https://github.com/sigp/lighthouse/pull/6398

second step is to add individual request accumulators for `blocks_by_range`, `blobs_by_range`, and `data_columns_by_range`. This will allow each request to progress independently and be retried separately.

Most of the logic is just piping, excuse the large diff. This PR does not change the logic of how requests are handled or retried. This will be done in a future PR changing the logic of `RangeBlockComponentsRequest`.

### Before

- Sync manager receives block with `SyncRequestId::RangeBlockAndBlobs`
- Insert block into `SyncNetworkContext::range_block_components_requests`
- (If received stream terminators of all requests)
  - Return `Vec<RpcBlock>`, and insert into `range_sync`

### Now

- Sync manager receives block with `SyncRequestId::RangeBlockAndBlobs`
- Insert block into `SyncNetworkContext:: blocks_by_range_requests`
- (If received stream terminator of this request)
  - Return `Vec<SignedBlock>`, and insert into `SyncNetworkContext::components_by_range_requests `
  - (If received a result for all requests)
    - Return `Vec<RpcBlock>`, and insert into `range_sync`

2024-10-16 22:39 UTC, dapplion commented on beacon_node/network/src/sync/range_sync/range.rs
> +        // rig.expect_chain_segment();
I want to migrate the range sync tests to the event-driven format but would prefer to do so in a separate PR

2024-10-17 18:01 UTC, realbigsean requested changes
Looks really good overall!

2024-10-17 18:01 UTC, realbigsean commented on beacon_node/lighthouse_network/src/service/api_types.rs
> +    pub id: Id,
i'm understanding this is the sub-request id and `requester.id` is the meta-request id, can we rename one of them? it's sort of confusing

2024-10-17 18:01 UTC, realbigsean commented on beacon_node/network/src/sync/network_context/requests/blobs_by_range.rs
> +        // TODO: Should check if index is within bounds
As in the blob index? might as well throw that check in now right

2024-10-17 18:01 UTC, realbigsean commented on beacon_node/network/src/sync/network_context.rs
>  pub enum BlockOrBlob<E: EthSpec> {
Might be time to rename this.. maybe `RangeBlockComponent` because it should be the wrapper for the return type of `RangeBlockComponentRequest`?

2024-10-17 18:01 UTC, realbigsean commented on beacon_node/network/src/sync/network_context.rs
> +        let _blocks_req_id = self.send_blocks_by_range_request(peer_id, request.clone(), id)?;
The `_blocks_req_id` here is unused and `blobs_req_id` is only used to check if a blobs request was made. I don't see these `send_` methods used anywhere else so I think we can return `Result<(), ..>` rather than `Result<BlocksByRangeRequestId, ..>` for blocks. Maybe a bool for blobs. Looks like for custody columns, we care about the count requested but not particular ids

2024-10-17 18:01 UTC, realbigsean commented on beacon_node/network/src/sync/network_context.rs
>      pub fn range_block_and_blob_response(
another rename suggestion `range_block_component_response`

2024-10-17 18:01 UTC, realbigsean commented on beacon_node/network/src/sync/network_context.rs
> +                BlockOrBlob::Block(resp) => match resp {
Can do this here and for blobs and columns as well
```
resp.map(|(blocks, _)| {
    request.add_blocks(blocks);
})
```

2024-10-18 14:07 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
> +        let _blocks_req_id = self.send_blocks_by_range_request(peer_id, request.clone(), id)?;
In a future PR `RangeBlockComponentsRequest` will track individual requests by ID. Left this variable named but unused as a hint that it should be used.

2024-10-18 14:08 UTC, dapplion commented on beacon_node/lighthouse_network/src/service/api_types.rs
> +    pub id: Id,
What name(s) do you have in mind? I can add docs otherwise

2024-10-18 14:28 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
> +                BlockOrBlob::Block(resp) => match resp {
Addressed in 5fa291240

2024-10-18 14:28 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
>      pub fn range_block_and_blob_response(
Addressed in 5fa291240

2024-10-18 14:28 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
>  pub enum BlockOrBlob<E: EthSpec> {
Addressed in 5fa291240

2024-10-18 14:28 UTC, dapplion commented on beacon_node/network/src/sync/network_context/requests/blobs_by_range.rs
> +        // TODO: Should check if index is within bounds
Addressed in 5fa291240

2025-01-10 06:30 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/requests/blocks_by_range.rs
> +        Ok(self.items.len() >= *self.request.count() as usize)
Should we check if a block for the slot already exists in `self.items`, to handle the case where the same block is sent twice? or is this handled elsewhere?

2025-01-10 06:41 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/requests/data_columns_by_range.rs
> +    fn consume(&mut self) -> Vec<Self::Item> {
Looks like this impl can be moved to `ActiveRequestItems`?

2025-01-13 11:00 UTC, dapplion commented on beacon_node/network/src/sync/network_context/requests/blocks_by_range.rs
> +        Ok(self.items.len() >= *self.request.count() as usize)
Added the check for duplicate data

2025-01-13 11:01 UTC, dapplion commented on beacon_node/network/src/sync/network_context/requests/data_columns_by_range.rs
> +    fn consume(&mut self) -> Vec<Self::Item> {
It can't as it uses state within `DataColumnsByRangeRequestItems`

2025-01-13 11:03 UTC, dapplion commented on beacon_node/network/src/sync/block_sidecar_coupling.rs
> -    max_blobs_per_block: usize,
Removed this from the state, since `into_responses_with_blobs` has access to the spec

2025-01-13 11:19 UTC, dapplion commented on beacon_node/network/src/sync/network_context/requests/blocks_by_range.rs
> +        Ok(self.items.len() >= *self.request.count() as usize)
Added the duplicate data check to all by_range requests

2025-01-13 11:19 UTC, dapplion commented
Rebased on latest unstable, @jimmygchen ready for another review

2025-01-22 04:05 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context.rs
> +    components_by_range_requests:
nit: comment above can be updated to include `DataColumnsByRange` or the overall components by range request.

2025-01-22 04:07 UTC, jimmygchen commented on beacon_node/lighthouse_network/src/service/api_types.rs
> +    pub id: Id,
What about `parent_request_id`?

2025-01-22 04:20 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/requests/data_columns_by_range.rs
> +    fn consume(&mut self) -> Vec<Self::Item> {
oh yeah sorry!

2025-01-22 04:23 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context/requests/blobs_by_range.rs
> +        Ok(false)
Do we verify blob inclusion proofs anywhere else?

2025-01-22 04:43 UTC, jimmygchen commented on beacon_node/network/src/sync/tests/range.rs
> +                        request_id: AppRequestId::Sync(SyncRequestId::BlobsByRange(id)),
Just a heads up that I've added data column handling for these tests - if this one gets approved first I'll address it in my PR :)

2025-01-22 05:16 UTC, jimmygchen commented on beacon_node/network/src/sync/manager.rs
> +        block_or_blob: RangeBlockComponent<T::EthSpec>,
I think we can also rename the parameter name to `range_block_component`?

2025-01-22 05:19 UTC, jimmygchen commented on beacon_node/network/src/sync/manager.rs
> +        id: ComponentsByRangeRequestId,
perhaps rename this to `range_request_id`? 
The `id.id` below is a bit confusing to me.

2025-01-22 05:47 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context.rs
> +        // add new request types to the this function. Otherwise, lookup sync can break and lookups
```suggestion
        // add new request types to this function. Otherwise, lookup sync can break and lookups
```

2025-01-22 05:49 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context.rs
>          // TODO(pawan): this would break if a batch contains multiple epochs
I think this comment can e removed?

2025-01-22 05:51 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context.rs
> +        block_or_blob: RangeBlockComponent<T::EthSpec>,
Should we rename this to `block_component` or `range_block_component`?

2025-01-22 05:53 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context.rs
> +    ) -> Option<RpcResponseResult<Vec<Arc<DataColumnSidecar<T::EthSpec>>>>> {
Could replace `Vec<..>` with `DataColumnSidecarList`?

2025-01-22 05:54 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context.rs
> +            ("data_columns_by_root", self.blocks_by_root_requests.len()),
```suggestion
            ("data_columns_by_root", self.data_columns_by_root_requests.len()),
```

2025-01-22 05:55 UTC, jimmygchen commented on beacon_node/network/src/sync/network_context.rs
> +            ("data_columns_by_range", self.blocks_by_range_requests.len()),
```suggestion
            ("data_columns_by_range", self.data_columns_by_range_requests.len()),
```

2025-01-22 05:59 UTC, jimmygchen commented on beacon_node/network/src/router.rs
> +                id @ SyncRequestId::BlocksByRange { .. } => id,
Is it worth matching the `SyncRequestId` for other `_by_range_response` functions too?

2025-01-22 06:01 UTC, jimmygchen requested changes
Looks great! 

The `id` naming was a bit confusing to me at first, but overall the logic is actually simpler than I thought 👍

2025-01-25 09:58 UTC, dapplion commented on beacon_node/lighthouse_network/src/service/api_types.rs
> +    pub id: Id,
Fixed with 11f903022

2025-01-25 10:12 UTC, dapplion commented on beacon_node/lighthouse_network/src/service/api_types.rs
> +    pub id: Id,
Fixed with https://github.com/sigp/lighthouse/pull/6497/commits/11f903022

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/router.rs
> +                id @ SyncRequestId::BlocksByRange { .. } => id,
Not really, I would actually change this to a let Some() match instead of two matches (in a future PR) and leave as is to minimize diff

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/manager.rs
> +        id: ComponentsByRangeRequestId,
Fixed with 20d97941e

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/manager.rs
> +        block_or_blob: RangeBlockComponent<T::EthSpec>,
Fixed with 20d97941e

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
>          // TODO(pawan): this would break if a batch contains multiple epochs
000bc5512

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
> +        block_or_blob: RangeBlockComponent<T::EthSpec>,
Yeah! 000bc5512

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
> +    ) -> Option<RpcResponseResult<Vec<Arc<DataColumnSidecar<T::EthSpec>>>>> {
:+1 000bc5512

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
> +            ("data_columns_by_root", self.blocks_by_root_requests.len()),
Uff nice find! d99232a97

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
> +            ("data_columns_by_range", self.blocks_by_range_requests.len()),
d99232a97

2025-01-25 10:12 UTC, dapplion commented on beacon_node/network/src/sync/network_context/requests/blobs_by_range.rs
> +        Ok(false)
Missing check! Added in d72b61d7a for both blob and columns

2025-01-25 10:14 UTC, dapplion commented on beacon_node/network/src/sync/network_context.rs
> +    components_by_range_requests:
Done

2025-02-03 18:04 UTC, realbigsean approved these changes
Nice, couldn't find any issues

2025-02-05 06:23 UTC, jimmygchen commented on beacon_node/lighthouse_network/src/service/api_types.rs
> +    pub id: Id,
Nice, much easier to read. Thanks for the docs

2025-02-05 06:34 UTC, jimmygchen approved these changes
Looks great! Thanks

2025-02-05 07:08 UTC, merged