Additional light client metrics
sigp/lighthouse pull request #6545
Opened 2024-10-28 20:18 UTC by eserilev

## Issue Addressed

Add some additional light client metrics plus one small bugfix to the get light client updates endpoint

2024-10-28 22:23 UTC, dapplion approved these changes
LGTM!

2024-11-05 04:47 UTC, jimmygchen commented on beacon_node/beacon_chain/src/metrics.rs
> +            "light_client_server_cache_processing_requests",
Small nit to prefix the metric with `beacon_` for consistency with other beacon chain metrics and to make it easier to distinguish BN metrics in Grafana queries:

```suggestion
            "beacon_light_client_server_cache_processing_requests",
```

2024-11-05 04:47 UTC, jimmygchen commented on beacon_node/beacon_chain/src/metrics.rs
> +            "light_client_server_cache_processing_successes",
```suggestion
            "beacon_light_client_server_cache_processing_successes",
```

2024-11-05 04:48 UTC, jimmygchen requested changes
Thanks, the change looks good to me! Just a small nit on the metric name.

2024-11-07 04:50 UTC, jimmygchen approved these changes
Looks great, thanks!

2024-11-07 05:02 UTC, jimmygchen commented
@mergify queue

2024-11-15 06:29 UTC, michaelsproul commented
@mergify requeue

2024-11-15 07:09 UTC, merged