[WIP] Add cli flag for HTTP API token path (VC)
sigp/lighthouse pull request #6577
Opened 2024-11-09 03:12 UTC by syjn99

## Issue Addressed

#6563

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

2024-11-09 03:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sigp/lighthouse?pullRequest=6577) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sigp/lighthouse?pullRequest=6577) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=6577) it.</sub>

2024-11-14 02:08 UTC, michaelsproul requested changes
Thanks for the pull request!

This looks good on the whole, just a few minor tweaks and then we can merge

2024-11-14 02:08 UTC, michaelsproul commented on validator_client/src/cli.rs
> +                .conflicts_with("datadir")
This should not conflict with `datadir`.

It should have `requires("http")` instead

2024-11-14 02:08 UTC, michaelsproul commented on validator_client/src/config.rs
> +    pub http_token_path: PathBuf,
I think this field should be inside `validator_http_api::Config`

2024-11-18 10:32 UTC, syjn99 commented
@michaelsproul 
Fixed things you mentioned! Sorry for delay, enjoyed Devcon a lot 🙇‍♂️

2024-11-20 02:51 UTC, chong-he reviewed
Did some manual testing and it works well!

Edit: need to edit the `cli.rs` file as well

2024-11-20 02:51 UTC, chong-he commented on book/src/help_vc.md
> +          not exist.
Small nitpick, The last sentence is a bit of ambiguous, I think the description is clear enough without the last sentence, hence suggesting to remove it.
```suggestion
          {validators-dir}/api-token.txt. 
```

2024-11-20 05:30 UTC, chong-he commented on book/src/help_vc.md
> +          not exist.
Edit: Need to change in the `cli.rs` too

2024-11-24 06:50 UTC, syjn99 commented
@michaelsproul @chong-he 
Could you please check this one more time? I applied reviews, fixed things that broke CI jobs.

2024-12-03 11:24 UTC, syjn99 commented
@michaelsproul It seems that there are some flaky tests for `make test-network`. I'm not sure but it might be related to #6646.

2024-12-13 05:42 UTC, jimmygchen approved these changes
Looks good to me, thanks for the PR!

2024-12-13 06:33 UTC, michaelsproul approved these changes

2024-12-16 04:33 UTC, jimmygchen commented
@mergify queue

2024-12-16 04:34 UTC, michaelsproul commented
@mergify dequeue

2024-12-16 04:48 UTC, jimmygchen commented
@mergify requeue

2024-12-16 05:43 UTC, merged