Add documentation for VC API `/lighthouse/beacon/health`
sigp/lighthouse pull request #6653
Opened 2024-12-03 05:53 UTC by macladson

## Proposed Changes

Changes the endpoint to get fallback health information from `/lighthouse/ui/fallback_health` to `/lighthouse/beacon/health`. This more accurately describes that the endpoint is related to the connected beacon nodes and also matched the `/lighthouse/beacon/update` endpoint being added in #6551.

Adds documentation for both fallback health and the endpoint to the Lighthouse book.

## Additional Info

I am not marking this as a breaking change since this endpoint is very new and has yet to be documented.

2024-12-03 14:16 UTC, chong-he requested changes, later dismissed
Looks good. I have tested the endpoint too and it is working, just got a question as commented below.

2024-12-03 14:16 UTC, chong-he commented on book/src/redundancy.md
> +to  determine which node is the "Healthiest". In general, the validator client will prefer nodes
```suggestion
to determine which node is the "Healthiest". In general, the validator client will prefer nodes
```

2024-12-03 14:16 UTC, chong-he commented on book/src/api-vc-endpoints.md
> +
A small suggestion to add the command here.
```suggestion
Command:

```bash
DATADIR=/var/lib/lighthouse
curl -X GET http://localhost:5062/lighthouse/beacon/health \
 -H "Authorization: Bearer $(cat ${DATADIR}/validators/api-token.txt)" | jq
```

2024-12-03 14:16 UTC, chong-he commented on book/src/api-vc-endpoints.md
> +                "index": 0,
What does this `index` refer to? 

Says we have `--beacon-nodes http://localhost:5052,http://localhost:5053`. My understanding is `user_index` is the order of the endpoint set in this flag; so for endpoint 5052, `user_index=0` and for endpoint 5053, `user_index=1` .

Say endpoint 5052 is offline/out of sync, and endpoint 5053 is now returned first in the list in GET `/lighthouse/beacon/health`. Should the `index` for endpoint 5053 be 0 or 1 in this case? I may be misunderstood this field. I thought it represents the "current index/current rank" of the beacon node list. But I am seeing `index=1` for endpoint 5053 that's now returned first in the list.

2024-12-04 09:44 UTC, macladson commented on book/src/api-vc-endpoints.md
> +                "index": 0,
Ah good question. `index` and `user_index` both always refers to the user ordering from `--beacon-nodes` (and soon `/lighthouse/beacon/update`) and so will not change even if the nodes are reordered due to health. The reason why `index` and `user_index` exist twice is an artifact of their underlying Rust representation (a bit annoying, but it helps reduce complexity). I could write a custom serializer to remove it, but I don't really think it is worth it. My guess is that almost nobody will actually interact with this API directly, but I think it perhaps has some utility in Siren (where we are free to make the actual current ordering very clear.

By the way, the actual functional order of the nodes isn't explicitly listed in the health info, but it can be inferred by:
1. Nodes are sorted by lowest `tier` first.
2. In the case where more than one node shares a tier, they are then ordered based on `user_index`.

2024-12-04 12:44 UTC, chong-he commented on book/src/api-vc-endpoints.md
> +                "index": 0,
Thanks for the explanation! All good, I was having a misunderstanding that the `index` was referring to the current rank.

2025-02-06 04:45 UTC, michaelsproul commented
CI is failing

2025-03-27 12:22 UTC, chong-he commented
Thank you for [bdc16e6](https://github.com/sigp/lighthouse/pull/6653/commits/bdc16e633da10a6ece1951acafa63461dc65c92d), I missed those files in a recent PR

2025-03-27 12:39 UTC, macladson commented
> Thank you for [bdc16e6](https://github.com/sigp/lighthouse/pull/6653/commits/bdc16e633da10a6ece1951acafa63461dc65c92d), I missed those files in a recent PR
> 
> Edit: I mean the file names should be `archived_merge_migration.md` and `archived_key_management.md`

Yeah I noticed the naming was a bit off for those files. I think naming them to be consistent with the rest of the files is out of scope for this PR so feel free to make a separate one for it :pray:

2025-04-30 01:36 UTC, michaelsproul approved these changes
LGTM

2025-04-30 02:07 UTC, merged