fix: correct datadir disk usage reporting in lighthouse.rs
sigp/lighthouse pull request #6741
Opened 2024-12-26 01:42 UTC by crStiv

# Fix datadir disk usage reporting in lighthouse.rs

## Description

This pull request updates `lighthouse.rs` to fix the disk usage metrics. Previously, the disk usage was calculated for the root directory (`/`). The new implementation correctly retrieves and uses the `LIGHTHOUSE_DATADIR` environment variable to calculate disk usage for the appropriate data directory. If the environment variable is not set, it defaults to `/`.

### Fixes #6687

## Proposed Changes

- Modify the `disk_usage` calculation to use the `LIGHTHOUSE_DATADIR` environment variable.
- Add a fallback to the root directory if `LIGHTHOUSE_DATADIR` is not specified.
- Update the error handling to provide clearer error messages if disk usage information cannot be retrieved.

## Additional Info

- This change introduces a behavior that depends on the `LIGHTHOUSE_DATADIR` environment variable. Reviewers should ensure the variable is correctly set in environments where this change is deployed.
- Future consideration: Test cases could be added to validate behavior when `LIGHTHOUSE_DATADIR` is missing or set to invalid paths.

## Allow edits by maintainers

Yes.

---
Please ensure contributions adhere to the repository's contributing guidelines and security policy.

2024-12-26 01:46 UTC, michaelsproul commented
This should not require the addition of a new environment variable. Lighthouse already knows the data directory from the `--datadir` CLI flag.

2024-12-26 01:51 UTC, crStiv commented
@michaelsproul this one seems to be better

2024-12-27 01:54 UTC, michaelsproul commented
That doesn't work @crStiv. Are you writing this PR with AI?

2024-12-27 23:45 UTC, crStiv commented
> That doesn't work @crStiv. Are you writing this PR with AI?

Made an update, this one should be alright.  I used chatgpt to help me create a pull request description

2024-12-28 03:03 UTC, michaelsproul requested changes

2024-12-28 03:03 UTC, michaelsproul commented on common/eth2/src/lighthouse.rs
> +        let args: Vec<String> = std::env::args().collect();
We shouldn't be re-parsing the CLI args like this. They are already parsed by clap and available in the config

2024-12-29 01:24 UTC, michaelsproul commented
CI is failing. You can check that the code compiles locally with `make lint`, and there are other makefile targets for running the tests

2025-02-13 04:06 UTC, closed without merging

2025-02-13 04:07 UTC, michaelsproul commented
Closing as stale/broken